return {
  version = "1.1",
  luaversion = "5.1",
  tiledversion = "0.17.1",
  orientation = "orthogonal",
  renderorder = "right-down",
  width = 500,
  height = 50,
  tilewidth = 25,
  tileheight = 25,
  nextobjectid = 1107,
  properties = {},
  tilesets = {
    {
      name = "tiles",
      firstgid = 1,
      tilewidth = 25,
      tileheight = 25,
      spacing = 0,
      margin = 0,
      tileoffset = {
        x = 0,
        y = 0
      },
      properties = {},
      terrains = {},
      tilecount = 14,
      tiles = {
        {
          id = 0,
          image = "G:/Feevale/Mapas projeto/tiles/coinTile.png",
          width = 25,
          height = 25
        },
        {
          id = 1,
          image = "G:/Feevale/Mapas projeto/tiles/darkTile.png",
          width = 25,
          height = 25
        },
        {
          id = 2,
          image = "G:/Feevale/Mapas projeto/tiles/endGameTile.png",
          width = 25,
          height = 25
        },
        {
          id = 3,
          image = "G:/Feevale/Mapas projeto/tiles/endZeroGravityTile.png",
          width = 25,
          height = 25
        },
        {
          id = 4,
          image = "G:/Feevale/Mapas projeto/tiles/fatalTile.png",
          width = 25,
          height = 25
        },
        {
          id = 5,
          image = "G:/Feevale/Mapas projeto/tiles/groundTile.png",
          width = 25,
          height = 25
        },
        {
          id = 6,
          image = "G:/Feevale/Mapas projeto/tiles/lightTile.png",
          width = 25,
          height = 25
        },
        {
          id = 7,
          image = "G:/Feevale/Mapas projeto/tiles/portal1Tile.png",
          width = 25,
          height = 25
        },
        {
          id = 8,
          image = "G:/Feevale/Mapas projeto/tiles/portal2Tile.png",
          width = 25,
          height = 25
        },
        {
          id = 9,
          image = "G:/Feevale/Mapas projeto/tiles/portal3Tile.png",
          width = 25,
          height = 25
        },
        {
          id = 10,
          image = "G:/Feevale/Mapas projeto/tiles/portal4Tile.png",
          width = 25,
          height = 25
        },
        {
          id = 11,
          image = "G:/Feevale/Mapas projeto/tiles/powerUpTile.png",
          width = 25,
          height = 25
        },
        {
          id = 12,
          image = "G:/Feevale/Mapas projeto/tiles/spikeTile.png",
          width = 25,
          height = 25
        },
        {
          id = 13,
          image = "G:/Feevale/Mapas projeto/tiles/startZeroGravityTile.png",
          width = 25,
          height = 25
        }
      }
    },
    {
      name = "tiles",
      firstgid = 15,
      tilewidth = 25,
      tileheight = 25,
      spacing = 0,
      margin = 0,
      tileoffset = {
        x = 0,
        y = 0
      },
      properties = {},
      terrains = {},
      tilecount = 14,
      tiles = {
        {
          id = 0,
          image = "E:/tiles/coinTile.png",
          width = 25,
          height = 25
        },
        {
          id = 1,
          image = "E:/tiles/darkTile.png",
          width = 25,
          height = 25
        },
        {
          id = 2,
          image = "E:/tiles/endGameTile.png",
          width = 25,
          height = 25
        },
        {
          id = 3,
          image = "E:/tiles/endZeroGravityTile.png",
          width = 25,
          height = 25
        },
        {
          id = 4,
          image = "E:/tiles/fatalTile.png",
          width = 25,
          height = 25
        },
        {
          id = 5,
          image = "E:/tiles/groundTile.png",
          width = 25,
          height = 25
        },
        {
          id = 6,
          image = "E:/tiles/lightTile.png",
          width = 25,
          height = 25
        },
        {
          id = 7,
          image = "E:/tiles/portal1Tile.png",
          width = 25,
          height = 25
        },
        {
          id = 8,
          image = "E:/tiles/portal2Tile.png",
          width = 25,
          height = 25
        },
        {
          id = 9,
          image = "E:/tiles/portal3Tile.png",
          width = 25,
          height = 25
        },
        {
          id = 10,
          image = "E:/tiles/portal4Tile.png",
          width = 25,
          height = 25
        },
        {
          id = 11,
          image = "E:/tiles/powerUpTile.png",
          width = 25,
          height = 25
        },
        {
          id = 12,
          image = "E:/tiles/spikeTile.png",
          width = 25,
          height = 25
        },
        {
          id = 13,
          image = "E:/tiles/startZeroGravityTile.png",
          width = 25,
          height = 25
        }
      }
    }
  },
  layers = {
    {
      type = "objectgroup",
      name = "Object Layer 1",
      visible = true,
      opacity = 1,
      offsetx = 166,
      offsety = 128,
      draworder = "topdown",
      properties = {},
      objects = {
        {
          id = 283,
          name = "",
          type = "G",
          shape = "rectangle",
          x = -234.5,
          y = 703.25,
          width = 3212.5,
          height = 128.25,
          rotation = 0,
          gid = 6,
          visible = true,
          properties = {}
        },
        {
          id = 376,
          name = "",
          type = "G",
          shape = "rectangle",
          x = 4483.25,
          y = 728.25,
          width = 6763.25,
          height = 228.25,
          rotation = 0,
          gid = 6,
          visible = true,
          properties = {}
        },
        {
          id = 622,
          name = "",
          type = "F",
          shape = "rectangle",
          x = 3971.5,
          y = 734.5,
          width = 587.5,
          height = 109.5,
          rotation = 0,
          gid = 5,
          visible = true,
          properties = {}
        },
        {
          id = 632,
          name = "",
          type = "G",
          shape = "rectangle",
          x = 1977.75,
          y = 575,
          width = 68.75,
          height = 90.5,
          rotation = 0,
          gid = 6,
          visible = true,
          properties = {}
        },
        {
          id = 640,
          name = "",
          type = "G",
          shape = "rectangle",
          x = 4733.25,
          y = 500,
          width = 325,
          height = 50,
          rotation = 0,
          gid = 6,
          visible = true,
          properties = {}
        },
        {
          id = 644,
          name = "",
          type = "G",
          shape = "rectangle",
          x = 4808.25,
          y = 450,
          width = 250,
          height = 50,
          rotation = 0,
          gid = 6,
          visible = true,
          properties = {}
        },
        {
          id = 656,
          name = "",
          type = "G",
          shape = "rectangle",
          x = 4908.25,
          y = 400,
          width = 150,
          height = 50,
          rotation = 0,
          gid = 6,
          visible = true,
          properties = {}
        },
        {
          id = 700,
          name = "",
          type = "S",
          shape = "rectangle",
          x = 5058.25,
          y = 500,
          width = 25,
          height = 25,
          rotation = 0,
          gid = 13,
          visible = true,
          properties = {}
        },
        {
          id = 701,
          name = "",
          type = "S",
          shape = "rectangle",
          x = 5083.25,
          y = 500,
          width = 25,
          height = 25,
          rotation = 0,
          gid = 13,
          visible = true,
          properties = {}
        },
        {
          id = 702,
          name = "",
          type = "S",
          shape = "rectangle",
          x = 5108.25,
          y = 500,
          width = 25,
          height = 25,
          rotation = 0,
          gid = 13,
          visible = true,
          properties = {}
        },
        {
          id = 703,
          name = "",
          type = "S",
          shape = "rectangle",
          x = 5133.25,
          y = 500,
          width = 25,
          height = 25,
          rotation = 0,
          gid = 13,
          visible = true,
          properties = {}
        },
        {
          id = 704,
          name = "",
          type = "S",
          shape = "rectangle",
          x = 5158.25,
          y = 500,
          width = 25,
          height = 25,
          rotation = 0,
          gid = 13,
          visible = true,
          properties = {}
        },
        {
          id = 707,
          name = "",
          type = "S",
          shape = "rectangle",
          x = 5183.25,
          y = 500,
          width = 25,
          height = 25,
          rotation = 0,
          gid = 13,
          visible = true,
          properties = {}
        },
        {
          id = 708,
          name = "",
          type = "S",
          shape = "rectangle",
          x = 5208.25,
          y = 500,
          width = 25,
          height = 25,
          rotation = 0,
          gid = 13,
          visible = true,
          properties = {}
        },
        {
          id = 709,
          name = "",
          type = "S",
          shape = "rectangle",
          x = 5233.25,
          y = 500,
          width = 25,
          height = 25,
          rotation = 0,
          gid = 13,
          visible = true,
          properties = {}
        },
        {
          id = 710,
          name = "",
          type = "S",
          shape = "rectangle",
          x = 5258.25,
          y = 500,
          width = 25,
          height = 25,
          rotation = 0,
          gid = 13,
          visible = true,
          properties = {}
        },
        {
          id = 711,
          name = "",
          type = "S",
          shape = "rectangle",
          x = 5283.25,
          y = 500,
          width = 25,
          height = 25,
          rotation = 0,
          gid = 13,
          visible = true,
          properties = {}
        },
        {
          id = 712,
          name = "",
          type = "S",
          shape = "rectangle",
          x = 5308.25,
          y = 500,
          width = 25,
          height = 25,
          rotation = 0,
          gid = 13,
          visible = true,
          properties = {}
        },
        {
          id = 713,
          name = "",
          type = "S",
          shape = "rectangle",
          x = 5333.25,
          y = 500,
          width = 25,
          height = 25,
          rotation = 0,
          gid = 13,
          visible = true,
          properties = {}
        },
        {
          id = 714,
          name = "",
          type = "S",
          shape = "rectangle",
          x = 5358.25,
          y = 500,
          width = 25,
          height = 25,
          rotation = 0,
          gid = 13,
          visible = true,
          properties = {}
        },
        {
          id = 715,
          name = "",
          type = "S",
          shape = "rectangle",
          x = 5383.25,
          y = 500,
          width = 25,
          height = 25,
          rotation = 0,
          gid = 13,
          visible = true,
          properties = {}
        },
        {
          id = 716,
          name = "",
          type = "S",
          shape = "rectangle",
          x = 5408.25,
          y = 500,
          width = 25,
          height = 25,
          rotation = 0,
          gid = 13,
          visible = true,
          properties = {}
        },
        {
          id = 717,
          name = "",
          type = "S",
          shape = "rectangle",
          x = 5433.25,
          y = 500,
          width = 25,
          height = 25,
          rotation = 0,
          gid = 13,
          visible = true,
          properties = {}
        },
        {
          id = 718,
          name = "",
          type = "S",
          shape = "rectangle",
          x = 5458.25,
          y = 500,
          width = 25,
          height = 25,
          rotation = 0,
          gid = 13,
          visible = true,
          properties = {}
        },
        {
          id = 719,
          name = "",
          type = "S",
          shape = "rectangle",
          x = 5483.25,
          y = 500,
          width = 25,
          height = 25,
          rotation = 0,
          gid = 13,
          visible = true,
          properties = {}
        },
        {
          id = 720,
          name = "",
          type = "S",
          shape = "rectangle",
          x = 5508.25,
          y = 500,
          width = 25,
          height = 25,
          rotation = 0,
          gid = 13,
          visible = true,
          properties = {}
        },
        {
          id = 721,
          name = "",
          type = "S",
          shape = "rectangle",
          x = 5533.25,
          y = 500,
          width = 25,
          height = 25,
          rotation = 0,
          gid = 13,
          visible = true,
          properties = {}
        },
        {
          id = 722,
          name = "",
          type = "S",
          shape = "rectangle",
          x = 5558.25,
          y = 500,
          width = 25,
          height = 25,
          rotation = 0,
          gid = 13,
          visible = true,
          properties = {}
        },
        {
          id = 723,
          name = "",
          type = "S",
          shape = "rectangle",
          x = 5583.25,
          y = 500,
          width = 25,
          height = 25,
          rotation = 0,
          gid = 13,
          visible = true,
          properties = {}
        },
        {
          id = 724,
          name = "",
          type = "S",
          shape = "rectangle",
          x = 5608.25,
          y = 500,
          width = 25,
          height = 25,
          rotation = 0,
          gid = 13,
          visible = true,
          properties = {}
        },
        {
          id = 725,
          name = "",
          type = "S",
          shape = "rectangle",
          x = 5633.25,
          y = 500,
          width = 25,
          height = 25,
          rotation = 0,
          gid = 13,
          visible = true,
          properties = {}
        },
        {
          id = 726,
          name = "",
          type = "S",
          shape = "rectangle",
          x = 5658.25,
          y = 500,
          width = 25,
          height = 25,
          rotation = 0,
          gid = 13,
          visible = true,
          properties = {}
        },
        {
          id = 727,
          name = "",
          type = "S",
          shape = "rectangle",
          x = 5683.25,
          y = 500,
          width = 25,
          height = 25,
          rotation = 0,
          gid = 13,
          visible = true,
          properties = {}
        },
        {
          id = 728,
          name = "",
          type = "S",
          shape = "rectangle",
          x = 5708.25,
          y = 500,
          width = 25,
          height = 25,
          rotation = 0,
          gid = 13,
          visible = true,
          properties = {}
        },
        {
          id = 729,
          name = "",
          type = "S",
          shape = "rectangle",
          x = 5733.25,
          y = 500,
          width = 25,
          height = 25,
          rotation = 0,
          gid = 13,
          visible = true,
          properties = {}
        },
        {
          id = 730,
          name = "",
          type = "S",
          shape = "rectangle",
          x = 5758.25,
          y = 500,
          width = 25,
          height = 25,
          rotation = 0,
          gid = 13,
          visible = true,
          properties = {}
        },
        {
          id = 733,
          name = "",
          type = "G",
          shape = "rectangle",
          x = 5158.25,
          y = 400,
          width = 75,
          height = 25,
          rotation = 0,
          gid = 6,
          visible = true,
          properties = {}
        },
        {
          id = 759,
          name = "",
          type = "G",
          shape = "rectangle",
          x = 5783.25,
          y = 500,
          width = 150,
          height = 125,
          rotation = 0,
          gid = 6,
          visible = true,
          properties = {}
        },
        {
          id = 991,
          name = "",
          type = "G",
          shape = "rectangle",
          x = 5508.25,
          y = 400,
          width = 75,
          height = 25,
          rotation = 0,
          gid = 6,
          visible = true,
          properties = {}
        },
        {
          id = 994,
          name = "",
          type = "EG",
          shape = "rectangle",
          x = 10575,
          y = 500,
          width = 25,
          height = 400,
          rotation = 0,
          gid = 3,
          visible = true,
          properties = {}
        },
        {
          id = 1026,
          name = "",
          type = "PU1",
          shape = "rectangle",
          x = 6433.25,
          y = 475,
          width = 25,
          height = 25,
          rotation = 0,
          gid = 12,
          visible = true,
          properties = {}
        },
        {
          id = 1062,
          name = "",
          type = "G",
          shape = "rectangle",
          x = 800,
          y = 575,
          width = 25,
          height = 25,
          rotation = 0,
          gid = 6,
          visible = true,
          properties = {}
        },
        {
          id = 1063,
          name = "",
          type = "G",
          shape = "rectangle",
          x = 1168.75,
          y = 575,
          width = 25,
          height = 25,
          rotation = 0,
          gid = 6,
          visible = true,
          properties = {}
        },
        {
          id = 1064,
          name = "",
          type = "G",
          shape = "rectangle",
          x = 1350,
          y = 575,
          width = 25,
          height = 25,
          rotation = 0,
          gid = 6,
          visible = true,
          properties = {}
        },
        {
          id = 1065,
          name = "",
          type = "G",
          shape = "rectangle",
          x = 2250,
          y = 575,
          width = 215.25,
          height = 65.5,
          rotation = 0,
          gid = 6,
          visible = true,
          properties = {}
        },
        {
          id = 1066,
          name = "",
          type = "G",
          shape = "rectangle",
          x = 2371.5,
          y = 512.5,
          width = 93.75,
          height = 50,
          rotation = 0,
          gid = 6,
          visible = true,
          properties = {}
        },
        {
          id = 1067,
          name = "",
          type = "G",
          shape = "rectangle",
          x = 2550,
          y = 475,
          width = 75,
          height = 25,
          rotation = 0,
          gid = 6,
          visible = true,
          properties = {}
        },
        {
          id = 1069,
          name = "",
          type = "G",
          shape = "rectangle",
          x = 2725,
          y = 475,
          width = 75,
          height = 25,
          rotation = 0,
          gid = 6,
          visible = true,
          properties = {}
        },
        {
          id = 1070,
          name = "",
          type = "G",
          shape = "rectangle",
          x = 2977,
          y = 703.25,
          width = 175,
          height = 253.25,
          rotation = 0,
          gid = 6,
          visible = true,
          properties = {}
        },
        {
          id = 1071,
          name = "",
          type = "G",
          shape = "rectangle",
          x = 3152,
          y = 703.25,
          width = 882,
          height = 203.25,
          rotation = 0,
          gid = 6,
          visible = true,
          properties = {}
        },
        {
          id = 1075,
          name = "",
          type = "G",
          shape = "rectangle",
          x = 5683.25,
          y = 400,
          width = 102.75,
          height = 25,
          rotation = 0,
          gid = 6,
          visible = true,
          properties = {}
        },
        {
          id = 1078,
          name = "",
          type = "G",
          shape = "rectangle",
          x = 6739.5,
          y = 500,
          width = 150,
          height = 50,
          rotation = 0,
          gid = 6,
          visible = true,
          properties = {}
        },
        {
          id = 1079,
          name = "",
          type = "G",
          shape = "rectangle",
          x = 7664.5,
          y = 500,
          width = 177.75,
          height = 200,
          rotation = 0,
          gid = 6,
          visible = true,
          properties = {}
        },
        {
          id = 1080,
          name = "",
          type = "PU2",
          shape = "rectangle",
          x = 7489.5,
          y = 475,
          width = 25,
          height = 25,
          rotation = 0,
          gid = 12,
          visible = true,
          properties = {}
        },
        {
          id = 1081,
          name = "",
          type = "G",
          shape = "rectangle",
          x = 2902,
          y = 575,
          width = 75,
          height = 59.25,
          rotation = 0,
          gid = 6,
          visible = true,
          properties = {}
        },
        {
          id = 1083,
          name = "",
          type = "L",
          shape = "rectangle",
          x = 3393.75,
          y = 506.25,
          width = 25,
          height = 295,
          rotation = 0,
          gid = 7,
          visible = true,
          properties = {}
        },
        {
          id = 1084,
          name = "",
          type = "T",
          shape = "rectangle",
          x = 771.5,
          y = 578.25,
          width = 9.75,
          height = 437.5,
          rotation = 0,
          gid = 9,
          visible = true,
          properties = {
            ["tutorialStep"] = 1
          }
        },
        {
          id = 1085,
          name = "",
          type = "D",
          shape = "rectangle",
          x = 3662.5,
          y = 500,
          width = 25,
          height = 290.5,
          rotation = 0,
          gid = 26,
          visible = true,
          properties = {}
        },
        {
          id = 1086,
          name = "",
          type = "D",
          shape = "rectangle",
          x = 4113.5,
          y = 525,
          width = 300,
          height = 25,
          rotation = 0,
          gid = 26,
          visible = true,
          properties = {}
        },
        {
          id = 1087,
          name = "",
          type = "L",
          shape = "rectangle",
          x = 5333.25,
          y = 400,
          width = 75,
          height = 25,
          rotation = 0,
          gid = 7,
          visible = true,
          properties = {}
        },
        {
          id = 1088,
          name = "",
          type = "T",
          shape = "rectangle",
          x = 1921.5,
          y = 578.25,
          width = 9.75,
          height = 437.5,
          rotation = 0,
          gid = 9,
          visible = true,
          properties = {
            ["tutorialStep"] = 3
          }
        },
        {
          id = 1089,
          name = "",
          type = "T",
          shape = "rectangle",
          x = 1459,
          y = 578.25,
          width = 9.75,
          height = 437.5,
          rotation = 0,
          gid = 9,
          visible = true,
          properties = {
            ["tutorialStep"] = 2
          }
        },
        {
          id = 1090,
          name = "",
          type = "T",
          shape = "rectangle",
          x = 3325,
          y = 500,
          width = 9.75,
          height = 437.5,
          rotation = 0,
          gid = 9,
          visible = true,
          properties = {
            ["tutorialStep"] = 4
          }
        },
        {
          id = 1091,
          name = "",
          type = "T",
          shape = "rectangle",
          x = 3587.5,
          y = 506.25,
          width = 9.75,
          height = 437.5,
          rotation = 0,
          gid = 9,
          visible = true,
          properties = {
            ["tutorialStep"] = 5
          }
        },
        {
          id = 1092,
          name = "",
          type = "T",
          shape = "rectangle",
          x = 6306.25,
          y = 500,
          width = 9.75,
          height = 437.5,
          rotation = 0,
          gid = 9,
          visible = true,
          properties = {
            ["tutorialStep"] = 6
          }
        },
        {
          id = 1093,
          name = "",
          type = "T",
          shape = "rectangle",
          x = 3587.5,
          y = 506.25,
          width = 9.75,
          height = 437.5,
          rotation = 0,
          gid = 9,
          visible = true,
          properties = {
            ["tutorialStep"] = 5
          }
        },
        {
          id = 1095,
          name = "",
          type = "T",
          shape = "rectangle",
          x = 8081.25,
          y = 500,
          width = 9.75,
          height = 437.5,
          rotation = 0,
          gid = 9,
          visible = true,
          properties = {
            ["tutorialStep"] = 7
          }
        },
        {
          id = 1097,
          name = "",
          type = "C",
          shape = "rectangle",
          x = 8168.75,
          y = 468.75,
          width = 25,
          height = 25,
          rotation = 0,
          gid = 1,
          visible = true,
          properties = {}
        },
        {
          id = 1099,
          name = "",
          type = "T",
          shape = "rectangle",
          x = 8681.25,
          y = 500,
          width = 9.75,
          height = 437.5,
          rotation = 0,
          gid = 9,
          visible = true,
          properties = {
            ["tutorialStep"] = 8
          }
        },
        {
          id = 1100,
          name = "",
          type = "G",
          shape = "rectangle",
          x = 8743.75,
          y = 231.25,
          width = 2509,
          height = 200,
          rotation = 0,
          gid = 6,
          visible = true,
          properties = {}
        },
        {
          id = 1101,
          name = "",
          type = "G",
          shape = "rectangle",
          x = 9087.5,
          y = 500,
          width = 115.25,
          height = 50,
          rotation = 0,
          gid = 6,
          visible = true,
          properties = {}
        },
        {
          id = 1102,
          name = "",
          type = "G",
          shape = "rectangle",
          x = 9516.5,
          y = 359.5,
          width = 209,
          height = 128.25,
          rotation = 0,
          gid = 6,
          visible = true,
          properties = {}
        },
        {
          id = 1103,
          name = "",
          type = "G",
          shape = "rectangle",
          x = 9931.25,
          y = 500,
          width = 215.25,
          height = 50,
          rotation = 0,
          gid = 6,
          visible = true,
          properties = {}
        },
        {
          id = 1104,
          name = "",
          type = "EZG",
          shape = "rectangle",
          x = 10006.3,
          y = 481.25,
          width = 25,
          height = 253,
          rotation = 0,
          gid = 18,
          visible = true,
          properties = {}
        },
        {
          id = 1105,
          name = "",
          type = "SZG",
          shape = "rectangle",
          x = 8756.25,
          y = 503.25,
          width = 25,
          height = 275,
          rotation = 0,
          gid = 22,
          visible = true,
          properties = {}
        },
        {
          id = 1106,
          name = "",
          type = "G",
          shape = "rectangle",
          x = 9202.25,
          y = 500,
          width = 138,
          height = 109.25,
          rotation = 0,
          gid = 6,
          visible = true,
          properties = {}
        }
      }
    }
  }
}
