return {
  version = "1.1",
  luaversion = "5.1",
  tiledversion = "0.17.1",
  orientation = "orthogonal",
  renderorder = "right-down",
  width = 500,
  height = 50,
  tilewidth = 25,
  tileheight = 25,
  nextobjectid = 1083,
  properties = {},
  tilesets = {
    {
      name = "tiles",
      firstgid = 1,
      tilewidth = 25,
      tileheight = 25,
      spacing = 0,
      margin = 0,
      tileoffset = {
        x = 0,
        y = 0
      },
      properties = {},
      terrains = {},
      tilecount = 14,
      tiles = {
        {
          id = 0,
          image = "E:/tiles/coinTile.png",
          width = 25,
          height = 25
        },
        {
          id = 1,
          image = "E:/tiles/darkTile.png",
          width = 25,
          height = 25
        },
        {
          id = 2,
          image = "E:/tiles/endGameTile.png",
          width = 25,
          height = 25
        },
        {
          id = 3,
          image = "E:/tiles/endZeroGravityTile.png",
          width = 25,
          height = 25
        },
        {
          id = 4,
          image = "E:/tiles/fatalTile.png",
          width = 25,
          height = 25
        },
        {
          id = 5,
          image = "E:/tiles/groundTile.png",
          width = 25,
          height = 25
        },
        {
          id = 6,
          image = "E:/tiles/lightTile.png",
          width = 25,
          height = 25
        },
        {
          id = 7,
          image = "E:/tiles/portal1Tile.png",
          width = 25,
          height = 25
        },
        {
          id = 8,
          image = "E:/tiles/portal2Tile.png",
          width = 25,
          height = 25
        },
        {
          id = 9,
          image = "E:/tiles/portal3Tile.png",
          width = 25,
          height = 25
        },
        {
          id = 10,
          image = "E:/tiles/portal4Tile.png",
          width = 25,
          height = 25
        },
        {
          id = 11,
          image = "E:/tiles/powerUpTile.png",
          width = 25,
          height = 25
        },
        {
          id = 12,
          image = "E:/tiles/spikeTile.png",
          width = 25,
          height = 25
        },
        {
          id = 13,
          image = "E:/tiles/startZeroGravityTile.png",
          width = 25,
          height = 25
        }
      }
    }
  },
  layers = {
    {
      type = "objectgroup",
      name = "Object Layer 1",
      visible = true,
      opacity = 1,
      offsetx = 166,
      offsety = 128,
      draworder = "topdown",
      properties = {},
      objects = {
        {
          id = 283,
          name = "",
          type = "G",
          shape = "rectangle",
          x = -253.5,
          y = 625,
          width = 2693.75,
          height = 50,
          rotation = 0,
          gid = 6,
          visible = true,
          properties = {}
        },
        {
          id = 376,
          name = "",
          type = "G",
          shape = "rectangle",
          x = 3120.75,
          y = 550,
          width = 3727.75,
          height = 50,
          rotation = 0,
          gid = 6,
          visible = true,
          properties = {}
        },
        {
          id = 622,
          name = "",
          type = "F",
          shape = "rectangle",
          x = 3034,
          y = 643.75,
          width = 131.25,
          height = 50,
          rotation = 0,
          gid = 5,
          visible = true,
          properties = {}
        },
        {
          id = 632,
          name = "",
          type = "G",
          shape = "rectangle",
          x = 1325,
          y = 575,
          width = 75,
          height = 100,
          rotation = 0,
          gid = 6,
          visible = true,
          properties = {}
        },
        {
          id = 640,
          name = "",
          type = "G",
          shape = "rectangle",
          x = 3370.75,
          y = 500,
          width = 325,
          height = 50,
          rotation = 0,
          gid = 6,
          visible = true,
          properties = {}
        },
        {
          id = 644,
          name = "",
          type = "G",
          shape = "rectangle",
          x = 3445.75,
          y = 450,
          width = 250,
          height = 50,
          rotation = 0,
          gid = 6,
          visible = true,
          properties = {}
        },
        {
          id = 656,
          name = "",
          type = "G",
          shape = "rectangle",
          x = 3545.75,
          y = 400,
          width = 150,
          height = 50,
          rotation = 0,
          gid = 6,
          visible = true,
          properties = {}
        },
        {
          id = 700,
          name = "",
          type = "S",
          shape = "rectangle",
          x = 3695.75,
          y = 500,
          width = 25,
          height = 25,
          rotation = 0,
          gid = 13,
          visible = true,
          properties = {}
        },
        {
          id = 701,
          name = "",
          type = "S",
          shape = "rectangle",
          x = 3720.75,
          y = 500,
          width = 25,
          height = 25,
          rotation = 0,
          gid = 13,
          visible = true,
          properties = {}
        },
        {
          id = 702,
          name = "",
          type = "S",
          shape = "rectangle",
          x = 3745.75,
          y = 500,
          width = 25,
          height = 25,
          rotation = 0,
          gid = 13,
          visible = true,
          properties = {}
        },
        {
          id = 703,
          name = "",
          type = "S",
          shape = "rectangle",
          x = 3770.75,
          y = 500,
          width = 25,
          height = 25,
          rotation = 0,
          gid = 13,
          visible = true,
          properties = {}
        },
        {
          id = 704,
          name = "",
          type = "S",
          shape = "rectangle",
          x = 3795.75,
          y = 500,
          width = 25,
          height = 25,
          rotation = 0,
          gid = 13,
          visible = true,
          properties = {}
        },
        {
          id = 707,
          name = "",
          type = "S",
          shape = "rectangle",
          x = 3820.75,
          y = 500,
          width = 25,
          height = 25,
          rotation = 0,
          gid = 13,
          visible = true,
          properties = {}
        },
        {
          id = 708,
          name = "",
          type = "S",
          shape = "rectangle",
          x = 3845.75,
          y = 500,
          width = 25,
          height = 25,
          rotation = 0,
          gid = 13,
          visible = true,
          properties = {}
        },
        {
          id = 709,
          name = "",
          type = "S",
          shape = "rectangle",
          x = 3870.75,
          y = 500,
          width = 25,
          height = 25,
          rotation = 0,
          gid = 13,
          visible = true,
          properties = {}
        },
        {
          id = 710,
          name = "",
          type = "S",
          shape = "rectangle",
          x = 3895.75,
          y = 500,
          width = 25,
          height = 25,
          rotation = 0,
          gid = 13,
          visible = true,
          properties = {}
        },
        {
          id = 711,
          name = "",
          type = "S",
          shape = "rectangle",
          x = 3920.75,
          y = 500,
          width = 25,
          height = 25,
          rotation = 0,
          gid = 13,
          visible = true,
          properties = {}
        },
        {
          id = 712,
          name = "",
          type = "S",
          shape = "rectangle",
          x = 3945.75,
          y = 500,
          width = 25,
          height = 25,
          rotation = 0,
          gid = 13,
          visible = true,
          properties = {}
        },
        {
          id = 713,
          name = "",
          type = "S",
          shape = "rectangle",
          x = 3970.75,
          y = 500,
          width = 25,
          height = 25,
          rotation = 0,
          gid = 13,
          visible = true,
          properties = {}
        },
        {
          id = 714,
          name = "",
          type = "S",
          shape = "rectangle",
          x = 3995.75,
          y = 500,
          width = 25,
          height = 25,
          rotation = 0,
          gid = 13,
          visible = true,
          properties = {}
        },
        {
          id = 715,
          name = "",
          type = "S",
          shape = "rectangle",
          x = 4020.75,
          y = 500,
          width = 25,
          height = 25,
          rotation = 0,
          gid = 13,
          visible = true,
          properties = {}
        },
        {
          id = 716,
          name = "",
          type = "S",
          shape = "rectangle",
          x = 4045.75,
          y = 500,
          width = 25,
          height = 25,
          rotation = 0,
          gid = 13,
          visible = true,
          properties = {}
        },
        {
          id = 717,
          name = "",
          type = "S",
          shape = "rectangle",
          x = 4070.75,
          y = 500,
          width = 25,
          height = 25,
          rotation = 0,
          gid = 13,
          visible = true,
          properties = {}
        },
        {
          id = 718,
          name = "",
          type = "S",
          shape = "rectangle",
          x = 4095.75,
          y = 500,
          width = 25,
          height = 25,
          rotation = 0,
          gid = 13,
          visible = true,
          properties = {}
        },
        {
          id = 719,
          name = "",
          type = "S",
          shape = "rectangle",
          x = 4120.75,
          y = 500,
          width = 25,
          height = 25,
          rotation = 0,
          gid = 13,
          visible = true,
          properties = {}
        },
        {
          id = 720,
          name = "",
          type = "S",
          shape = "rectangle",
          x = 4145.75,
          y = 500,
          width = 25,
          height = 25,
          rotation = 0,
          gid = 13,
          visible = true,
          properties = {}
        },
        {
          id = 721,
          name = "",
          type = "S",
          shape = "rectangle",
          x = 4170.75,
          y = 500,
          width = 25,
          height = 25,
          rotation = 0,
          gid = 13,
          visible = true,
          properties = {}
        },
        {
          id = 722,
          name = "",
          type = "S",
          shape = "rectangle",
          x = 4195.75,
          y = 500,
          width = 25,
          height = 25,
          rotation = 0,
          gid = 13,
          visible = true,
          properties = {}
        },
        {
          id = 723,
          name = "",
          type = "S",
          shape = "rectangle",
          x = 4220.75,
          y = 500,
          width = 25,
          height = 25,
          rotation = 0,
          gid = 13,
          visible = true,
          properties = {}
        },
        {
          id = 724,
          name = "",
          type = "S",
          shape = "rectangle",
          x = 4245.75,
          y = 500,
          width = 25,
          height = 25,
          rotation = 0,
          gid = 13,
          visible = true,
          properties = {}
        },
        {
          id = 725,
          name = "",
          type = "S",
          shape = "rectangle",
          x = 4270.75,
          y = 500,
          width = 25,
          height = 25,
          rotation = 0,
          gid = 13,
          visible = true,
          properties = {}
        },
        {
          id = 726,
          name = "",
          type = "S",
          shape = "rectangle",
          x = 4295.75,
          y = 500,
          width = 25,
          height = 25,
          rotation = 0,
          gid = 13,
          visible = true,
          properties = {}
        },
        {
          id = 727,
          name = "",
          type = "S",
          shape = "rectangle",
          x = 4320.75,
          y = 500,
          width = 25,
          height = 25,
          rotation = 0,
          gid = 13,
          visible = true,
          properties = {}
        },
        {
          id = 728,
          name = "",
          type = "S",
          shape = "rectangle",
          x = 4345.75,
          y = 500,
          width = 25,
          height = 25,
          rotation = 0,
          gid = 13,
          visible = true,
          properties = {}
        },
        {
          id = 729,
          name = "",
          type = "S",
          shape = "rectangle",
          x = 4370.75,
          y = 500,
          width = 25,
          height = 25,
          rotation = 0,
          gid = 13,
          visible = true,
          properties = {}
        },
        {
          id = 730,
          name = "",
          type = "S",
          shape = "rectangle",
          x = 4395.75,
          y = 500,
          width = 25,
          height = 25,
          rotation = 0,
          gid = 13,
          visible = true,
          properties = {}
        },
        {
          id = 733,
          name = "",
          type = "G",
          shape = "rectangle",
          x = 3795.75,
          y = 400,
          width = 75,
          height = 25,
          rotation = 0,
          gid = 6,
          visible = true,
          properties = {}
        },
        {
          id = 759,
          name = "",
          type = "G",
          shape = "rectangle",
          x = 4420.75,
          y = 500,
          width = 150,
          height = 125,
          rotation = 0,
          gid = 6,
          visible = true,
          properties = {}
        },
        {
          id = 798,
          name = "",
          type = "C",
          shape = "rectangle",
          x = 1350,
          y = 431.25,
          width = 25,
          height = 25,
          rotation = 0,
          gid = 1,
          visible = true,
          properties = {}
        },
        {
          id = 799,
          name = "",
          type = "C",
          shape = "rectangle",
          x = 3070.75,
          y = 412.5,
          width = 25,
          height = 25,
          rotation = 0,
          gid = 1,
          visible = true,
          properties = {}
        },
        {
          id = 802,
          name = "",
          type = "C",
          shape = "rectangle",
          x = 3620.75,
          y = 337.5,
          width = 25,
          height = 25,
          rotation = 0,
          gid = 1,
          visible = true,
          properties = {}
        },
        {
          id = 803,
          name = "",
          type = "C",
          shape = "rectangle",
          x = 3908.25,
          y = 300,
          width = 25,
          height = 25,
          rotation = 0,
          gid = 1,
          visible = true,
          properties = {}
        },
        {
          id = 804,
          name = "",
          type = "C",
          shape = "rectangle",
          x = 4083.25,
          y = 300,
          width = 25,
          height = 25,
          rotation = 0,
          gid = 1,
          visible = true,
          properties = {}
        },
        {
          id = 805,
          name = "",
          type = "C",
          shape = "rectangle",
          x = 4258.25,
          y = 300,
          width = 25,
          height = 25,
          rotation = 0,
          gid = 1,
          visible = true,
          properties = {}
        },
        {
          id = 806,
          name = "",
          type = "C",
          shape = "rectangle",
          x = 4520.75,
          y = 356.25,
          width = 25,
          height = 25,
          rotation = 0,
          gid = 1,
          visible = true,
          properties = {}
        },
        {
          id = 991,
          name = "",
          type = "G",
          shape = "rectangle",
          x = 4145.75,
          y = 400,
          width = 75,
          height = 25,
          rotation = 0,
          gid = 6,
          visible = true,
          properties = {}
        },
        {
          id = 994,
          name = "",
          type = "EG",
          shape = "rectangle",
          x = 6314.5,
          y = 500,
          width = 25,
          height = 400,
          rotation = 0,
          gid = 3,
          visible = true,
          properties = {}
        },
        {
          id = 1026,
          name = "",
          type = "PU1",
          shape = "rectangle",
          x = 4764.5,
          y = 475,
          width = 25,
          height = 25,
          rotation = 0,
          gid = 12,
          visible = true,
          properties = {}
        },
        {
          id = 1062,
          name = "",
          type = "G",
          shape = "rectangle",
          x = 425,
          y = 575,
          width = 25,
          height = 25,
          rotation = 0,
          gid = 6,
          visible = true,
          properties = {}
        },
        {
          id = 1063,
          name = "",
          type = "G",
          shape = "rectangle",
          x = 825,
          y = 575,
          width = 25,
          height = 25,
          rotation = 0,
          gid = 6,
          visible = true,
          properties = {}
        },
        {
          id = 1064,
          name = "",
          type = "G",
          shape = "rectangle",
          x = 975,
          y = 575,
          width = 25,
          height = 25,
          rotation = 0,
          gid = 6,
          visible = true,
          properties = {}
        },
        {
          id = 1065,
          name = "",
          type = "G",
          shape = "rectangle",
          x = 1737.5,
          y = 575,
          width = 200,
          height = 100,
          rotation = 0,
          gid = 6,
          visible = true,
          properties = {}
        },
        {
          id = 1066,
          name = "",
          type = "G",
          shape = "rectangle",
          x = 1846.5,
          y = 500,
          width = 91,
          height = 75,
          rotation = 0,
          gid = 6,
          visible = true,
          properties = {}
        },
        {
          id = 1067,
          name = "",
          type = "G",
          shape = "rectangle",
          x = 2037.5,
          y = 450,
          width = 75,
          height = 25,
          rotation = 0,
          gid = 6,
          visible = true,
          properties = {}
        },
        {
          id = 1069,
          name = "",
          type = "G",
          shape = "rectangle",
          x = 2212.5,
          y = 475,
          width = 75,
          height = 25,
          rotation = 0,
          gid = 6,
          visible = true,
          properties = {}
        },
        {
          id = 1070,
          name = "",
          type = "G",
          shape = "rectangle",
          x = 2439.5,
          y = 625,
          width = 175,
          height = 175,
          rotation = 0,
          gid = 6,
          visible = true,
          properties = {}
        },
        {
          id = 1071,
          name = "",
          type = "G",
          shape = "rectangle",
          x = 2609,
          y = 625,
          width = 430.5,
          height = 125,
          rotation = 0,
          gid = 6,
          visible = true,
          properties = {}
        },
        {
          id = 1074,
          name = "",
          type = "G",
          shape = "rectangle",
          x = 3970.75,
          y = 400,
          width = 75,
          height = 25,
          rotation = 0,
          gid = 6,
          visible = true,
          properties = {}
        },
        {
          id = 1075,
          name = "",
          type = "G",
          shape = "rectangle",
          x = 4320.75,
          y = 400,
          width = 102.75,
          height = 25,
          rotation = 0,
          gid = 6,
          visible = true,
          properties = {}
        },
        {
          id = 1076,
          name = "",
          type = "C",
          shape = "rectangle",
          x = 2156.25,
          y = 362.5,
          width = 25,
          height = 25,
          rotation = 0,
          gid = 1,
          visible = true,
          properties = {}
        },
        {
          id = 1078,
          name = "",
          type = "G",
          shape = "rectangle",
          x = 5039.5,
          y = 500,
          width = 150,
          height = 50,
          rotation = 0,
          gid = 6,
          visible = true,
          properties = {}
        },
        {
          id = 1079,
          name = "",
          type = "G",
          shape = "rectangle",
          x = 5964.5,
          y = 500,
          width = 177.75,
          height = 200,
          rotation = 0,
          gid = 6,
          visible = true,
          properties = {}
        },
        {
          id = 1080,
          name = "",
          type = "PU2",
          shape = "rectangle",
          x = 5789.5,
          y = 475,
          width = 25,
          height = 25,
          rotation = 0,
          gid = 12,
          visible = true,
          properties = {}
        },
        {
          id = 1081,
          name = "",
          type = "G",
          shape = "rectangle",
          x = 2364.5,
          y = 575,
          width = 75,
          height = 59.25,
          rotation = 0,
          gid = 6,
          visible = true,
          properties = {}
        },
        {
          id = 1082,
          name = "",
          type = "C",
          shape = "rectangle",
          x = 825,
          y = 487.5,
          width = 25,
          height = 25,
          rotation = 0,
          gid = 1,
          visible = true,
          properties = {}
        }
      }
    }
  }
}
