return {
  version = "1.1",
  luaversion = "5.1",
  tiledversion = "0.17.1",
  orientation = "orthogonal",
  renderorder = "right-down",
  width = 500,
  height = 50,
  tilewidth = 25,
  tileheight = 25,
  nextobjectid = 1158,
  properties = {},
  tilesets = {
    {
      name = "tiles",
      firstgid = 1,
      tilewidth = 25,
      tileheight = 25,
      spacing = 0,
      margin = 0,
      tileoffset = {
        x = 0,
        y = 0
      },
      properties = {},
      terrains = {},
      tilecount = 14,
      tiles = {
        {
          id = 0,
          image = "E:/tiles/coinTile.png",
          width = 25,
          height = 25
        },
        {
          id = 1,
          image = "E:/tiles/darkTile.png",
          width = 25,
          height = 25
        },
        {
          id = 2,
          image = "E:/tiles/endGameTile.png",
          width = 25,
          height = 25
        },
        {
          id = 3,
          image = "E:/tiles/endZeroGravityTile.png",
          width = 25,
          height = 25
        },
        {
          id = 4,
          image = "E:/tiles/fatalTile.png",
          width = 25,
          height = 25
        },
        {
          id = 5,
          image = "E:/tiles/groundTile.png",
          width = 25,
          height = 25
        },
        {
          id = 6,
          image = "E:/tiles/lightTile.png",
          width = 25,
          height = 25
        },
        {
          id = 7,
          image = "E:/tiles/portal1Tile.png",
          width = 25,
          height = 25
        },
        {
          id = 8,
          image = "E:/tiles/portal2Tile.png",
          width = 25,
          height = 25
        },
        {
          id = 9,
          image = "E:/tiles/portal3Tile.png",
          width = 25,
          height = 25
        },
        {
          id = 10,
          image = "E:/tiles/portal4Tile.png",
          width = 25,
          height = 25
        },
        {
          id = 11,
          image = "E:/tiles/powerUpTile.png",
          width = 25,
          height = 25
        },
        {
          id = 12,
          image = "E:/tiles/spikeTile.png",
          width = 25,
          height = 25
        },
        {
          id = 13,
          image = "E:/tiles/startZeroGravityTile.png",
          width = 25,
          height = 25
        }
      }
    }
  },
  layers = {
    {
      type = "objectgroup",
      name = "Object Layer 1",
      visible = true,
      opacity = 1,
      offsetx = 166,
      offsety = 128,
      draworder = "topdown",
      properties = {},
      objects = {
        {
          id = 283,
          name = "",
          type = "G",
          shape = "rectangle",
          x = -253.5,
          y = 878.25,
          width = 2700,
          height = 303.25,
          rotation = 0,
          gid = 6,
          visible = true,
          properties = {}
        },
        {
          id = 632,
          name = "",
          type = "G",
          shape = "rectangle",
          x = 790.25,
          y = 575,
          width = 100,
          height = 65.5,
          rotation = 0,
          gid = 6,
          visible = true,
          properties = {}
        },
        {
          id = 798,
          name = "",
          type = "C",
          shape = "rectangle",
          x = 1356.25,
          y = 368.25,
          width = 25,
          height = 25,
          rotation = 0,
          gid = 1,
          visible = true,
          properties = {}
        },
        {
          id = 994,
          name = "",
          type = "EG",
          shape = "rectangle",
          x = 7337.5,
          y = 537.5,
          width = 25,
          height = 259.25,
          rotation = 0,
          gid = 3,
          visible = true,
          properties = {}
        },
        {
          id = 1062,
          name = "",
          type = "G",
          shape = "rectangle",
          x = 393.75,
          y = 575,
          width = 25,
          height = 25,
          rotation = 0,
          gid = 6,
          visible = true,
          properties = {}
        },
        {
          id = 1065,
          name = "",
          type = "G",
          shape = "rectangle",
          x = 1600,
          y = 575,
          width = 200,
          height = 75,
          rotation = 0,
          gid = 6,
          visible = true,
          properties = {}
        },
        {
          id = 1066,
          name = "",
          type = "G",
          shape = "rectangle",
          x = 1725,
          y = 500,
          width = 75,
          height = 50,
          rotation = 0,
          gid = 6,
          visible = true,
          properties = {}
        },
        {
          id = 1067,
          name = "",
          type = "G",
          shape = "rectangle",
          x = 1900,
          y = 475,
          width = 471.5,
          height = 446.75,
          rotation = 0,
          gid = 6,
          visible = true,
          properties = {}
        },
        {
          id = 1076,
          name = "",
          type = "C",
          shape = "rectangle",
          x = 1843.75,
          y = 412.5,
          width = 25,
          height = 25,
          rotation = 0,
          gid = 1,
          visible = true,
          properties = {}
        },
        {
          id = 1083,
          name = "",
          type = "G",
          shape = "rectangle",
          x = 475,
          y = 468.75,
          width = 215.25,
          height = 25,
          rotation = 0,
          gid = 6,
          visible = true,
          properties = {}
        },
        {
          id = 1084,
          name = "",
          type = "P2",
          shape = "rectangle",
          x = 475,
          y = 443.75,
          width = 50,
          height = 75,
          rotation = 0,
          gid = 10,
          visible = true,
          properties = {}
        },
        {
          id = 1085,
          name = "",
          type = "C",
          shape = "rectangle",
          x = 600,
          y = 418.75,
          width = 25,
          height = 25,
          rotation = 0,
          gid = 1,
          visible = true,
          properties = {}
        },
        {
          id = 1086,
          name = "",
          type = "G",
          shape = "rectangle",
          x = 887.5,
          y = 575,
          width = 90.25,
          height = 128,
          rotation = 0,
          gid = 6,
          visible = true,
          properties = {}
        },
        {
          id = 1087,
          name = "",
          type = "G",
          shape = "rectangle",
          x = 1068.75,
          y = 464.75,
          width = 50,
          height = 25,
          rotation = 0,
          gid = 6,
          visible = true,
          properties = {}
        },
        {
          id = 1088,
          name = "",
          type = "G",
          shape = "rectangle",
          x = 1200,
          y = 431.25,
          width = 50,
          height = 25,
          rotation = 0,
          gid = 6,
          visible = true,
          properties = {}
        },
        {
          id = 1089,
          name = "",
          type = "G",
          shape = "rectangle",
          x = 1343.75,
          y = 425,
          width = 50,
          height = 25,
          rotation = 0,
          gid = 6,
          visible = true,
          properties = {}
        },
        {
          id = 1090,
          name = "",
          type = "G",
          shape = "rectangle",
          x = 1481.25,
          y = 400,
          width = 50,
          height = 25,
          rotation = 0,
          gid = 6,
          visible = true,
          properties = {}
        },
        {
          id = 1091,
          name = "",
          type = "G",
          shape = "rectangle",
          x = 1612.5,
          y = 393.75,
          width = 50,
          height = 25,
          rotation = 0,
          gid = 6,
          visible = true,
          properties = {}
        },
        {
          id = 1093,
          name = "",
          type = "L",
          shape = "rectangle",
          x = 1800,
          y = 475,
          width = 100,
          height = 25,
          rotation = 0,
          gid = 7,
          visible = true,
          properties = {}
        },
        {
          id = 1094,
          name = "",
          type = "D",
          shape = "rectangle",
          x = 2006.25,
          y = 575,
          width = 25,
          height = 100,
          rotation = 0,
          gid = 12,
          visible = true,
          properties = {}
        },
        {
          id = 1095,
          name = "",
          type = "L",
          shape = "rectangle",
          x = 2225,
          y = 575,
          width = 25,
          height = 100,
          rotation = 0,
          gid = 7,
          visible = true,
          properties = {}
        },
        {
          id = 1096,
          name = "",
          type = "L",
          shape = "rectangle",
          x = 2550,
          y = 525,
          width = 300,
          height = 25,
          rotation = 0,
          gid = 7,
          visible = true,
          properties = {}
        },
        {
          id = 1097,
          name = "",
          type = "D",
          shape = "rectangle",
          x = 2774,
          y = 392.25,
          width = 75,
          height = 25,
          rotation = 0,
          gid = 12,
          visible = true,
          properties = {}
        },
        {
          id = 1098,
          name = "",
          type = "L",
          shape = "rectangle",
          x = 2918.75,
          y = 306.25,
          width = 77.75,
          height = 25,
          rotation = 0,
          gid = 7,
          visible = true,
          properties = {}
        },
        {
          id = 1100,
          name = "",
          type = "D",
          shape = "rectangle",
          x = 2927.75,
          y = 543.75,
          width = 293.75,
          height = 25,
          rotation = 0,
          gid = 12,
          visible = true,
          properties = {}
        },
        {
          id = 1101,
          name = "",
          type = "D",
          shape = "rectangle",
          x = 3062.5,
          y = 237.5,
          width = 140.25,
          height = 25,
          rotation = 0,
          gid = 12,
          visible = true,
          properties = {}
        },
        {
          id = 1102,
          name = "",
          type = "P1",
          shape = "rectangle",
          x = 3337.5,
          y = 125,
          width = 50,
          height = 75,
          rotation = 0,
          gid = 10,
          visible = true,
          properties = {}
        },
        {
          id = 1103,
          name = "",
          type = "G",
          shape = "rectangle",
          x = 3281.25,
          y = 840.75,
          width = 1459,
          height = 312.5,
          rotation = 0,
          gid = 6,
          visible = true,
          properties = {}
        },
        {
          id = 1104,
          name = "",
          type = "C",
          shape = "rectangle",
          x = 3450,
          y = 43.75,
          width = 25,
          height = 25,
          rotation = 0,
          gid = 1,
          visible = true,
          properties = {}
        },
        {
          id = 1105,
          name = "",
          type = "G",
          shape = "rectangle",
          x = 3281.25,
          y = 315.75,
          width = 159,
          height = 75,
          rotation = 0,
          gid = 6,
          visible = true,
          properties = {}
        },
        {
          id = 1106,
          name = "",
          type = "G",
          shape = "rectangle",
          x = 3437.5,
          y = 362.5,
          width = 71.5,
          height = 84.25,
          rotation = 0,
          gid = 6,
          visible = true,
          properties = {}
        },
        {
          id = 1107,
          name = "",
          type = "G",
          shape = "rectangle",
          x = 3506.25,
          y = 362.5,
          width = 59,
          height = 53,
          rotation = 0,
          gid = 6,
          visible = true,
          properties = {}
        },
        {
          id = 1108,
          name = "",
          type = "G",
          shape = "rectangle",
          x = 3687.5,
          y = 284.5,
          width = 546.5,
          height = 325,
          rotation = 0,
          gid = 6,
          visible = true,
          properties = {}
        },
        {
          id = 1109,
          name = "",
          type = "G",
          shape = "rectangle",
          x = 3309,
          y = 143.75,
          width = 193.75,
          height = 21.75,
          rotation = 0,
          gid = 6,
          visible = true,
          properties = {}
        },
        {
          id = 1110,
          name = "",
          type = "F",
          shape = "rectangle",
          x = 2443.75,
          y = 781.25,
          width = 840.25,
          height = 50,
          rotation = 0,
          gid = 5,
          visible = true,
          properties = {}
        },
        {
          id = 1113,
          name = "",
          type = "G",
          shape = "rectangle",
          x = 4231.25,
          y = 284.5,
          width = 3721.5,
          height = 156.25,
          rotation = 0,
          gid = 6,
          visible = true,
          properties = {}
        },
        {
          id = 1114,
          name = "",
          type = "G",
          shape = "rectangle",
          x = 4393.75,
          y = 531.25,
          width = 152.75,
          height = 109.25,
          rotation = 0,
          gid = 6,
          visible = true,
          properties = {}
        },
        {
          id = 1115,
          name = "",
          type = "G",
          shape = "rectangle",
          x = 4715.25,
          y = 378.25,
          width = 250,
          height = 97,
          rotation = 0,
          gid = 6,
          visible = true,
          properties = {}
        },
        {
          id = 1116,
          name = "",
          type = "G",
          shape = "rectangle",
          x = 4900,
          y = 675,
          width = 3052.75,
          height = 140.75,
          rotation = 0,
          gid = 6,
          visible = true,
          properties = {}
        },
        {
          id = 1117,
          name = "",
          type = "D",
          shape = "rectangle",
          x = 4393.75,
          y = 425,
          width = 25,
          height = 140.5,
          rotation = 0,
          gid = 12,
          visible = true,
          properties = {}
        },
        {
          id = 1118,
          name = "",
          type = "L",
          shape = "rectangle",
          x = 4687.5,
          y = 528.25,
          width = 25,
          height = 93.75,
          rotation = 0,
          gid = 7,
          visible = true,
          properties = {}
        },
        {
          id = 1119,
          name = "",
          type = "G",
          shape = "rectangle",
          x = 4687.5,
          y = 434.5,
          width = 27.75,
          height = 153.25,
          rotation = 0,
          gid = 6,
          visible = true,
          properties = {}
        },
        {
          id = 1120,
          name = "",
          type = "G",
          shape = "rectangle",
          x = 4943.75,
          y = 437.5,
          width = 25,
          height = 153.25,
          rotation = 0,
          gid = 6,
          visible = true,
          properties = {}
        },
        {
          id = 1122,
          name = "",
          type = "D",
          shape = "rectangle",
          x = 4943.75,
          y = 534.5,
          width = 25,
          height = 100,
          rotation = 0,
          gid = 12,
          visible = true,
          properties = {}
        },
        {
          id = 1123,
          name = "",
          type = "F",
          shape = "rectangle",
          x = 4740.25,
          y = 843.75,
          width = 206.25,
          height = 159.25,
          rotation = 0,
          gid = 5,
          visible = true,
          properties = {}
        },
        {
          id = 1124,
          name = "",
          type = "G",
          shape = "rectangle",
          x = 3281.25,
          y = -40.5,
          width = 952.75,
          height = 237.5,
          rotation = 0,
          gid = 6,
          visible = true,
          properties = {}
        },
        {
          id = 1125,
          name = "",
          type = "C",
          shape = "rectangle",
          x = 3618.75,
          y = 318.75,
          width = 25,
          height = 25,
          rotation = 0,
          gid = 1,
          visible = true,
          properties = {}
        },
        {
          id = 1126,
          name = "",
          type = "G",
          shape = "rectangle",
          x = 3387.5,
          y = 128.25,
          width = 115.25,
          height = 50,
          rotation = 0,
          gid = 6,
          visible = true,
          properties = {}
        },
        {
          id = 1127,
          name = "",
          type = "C",
          shape = "rectangle",
          x = 4831.25,
          y = 450,
          width = 25,
          height = 25,
          rotation = 0,
          gid = 1,
          visible = true,
          properties = {}
        },
        {
          id = 1128,
          name = "",
          type = "S",
          shape = "rectangle",
          x = 3875,
          y = 531.25,
          width = 25,
          height = 25,
          rotation = 0,
          gid = 5,
          visible = true,
          properties = {}
        },
        {
          id = 1129,
          name = "",
          type = "S",
          shape = "rectangle",
          x = 3900,
          y = 531.25,
          width = 25,
          height = 25,
          rotation = 0,
          gid = 5,
          visible = true,
          properties = {}
        },
        {
          id = 1130,
          name = "",
          type = "S",
          shape = "rectangle",
          x = 3925,
          y = 531.25,
          width = 25,
          height = 25,
          rotation = 0,
          gid = 5,
          visible = true,
          properties = {}
        },
        {
          id = 1131,
          name = "",
          type = "S",
          shape = "rectangle",
          x = 3950,
          y = 531.25,
          width = 25,
          height = 25,
          rotation = 0,
          gid = 5,
          visible = true,
          properties = {}
        },
        {
          id = 1132,
          name = "",
          type = "G",
          shape = "rectangle",
          x = 3687.5,
          y = 362.5,
          width = 115.25,
          height = 403,
          rotation = 0,
          gid = 6,
          visible = true,
          properties = {}
        },
        {
          id = 1133,
          name = "",
          type = "G",
          shape = "rectangle",
          x = 4059,
          y = 362.5,
          width = 175,
          height = 403,
          rotation = 0,
          gid = 6,
          visible = true,
          properties = {}
        },
        {
          id = 1134,
          name = "",
          type = "C",
          shape = "rectangle",
          x = 3912.5,
          y = 425,
          width = 25,
          height = 25,
          rotation = 0,
          gid = 1,
          visible = true,
          properties = {}
        },
        {
          id = 1135,
          name = "",
          type = "G",
          shape = "rectangle",
          x = 3359,
          y = 362.5,
          width = 81.25,
          height = 121.75,
          rotation = 0,
          gid = 6,
          visible = true,
          properties = {}
        },
        {
          id = 1138,
          name = "",
          type = "G",
          shape = "rectangle",
          x = 5502.75,
          y = 537.5,
          width = 150,
          height = 46.75,
          rotation = 0,
          gid = 6,
          visible = true,
          properties = {}
        },
        {
          id = 1139,
          name = "",
          type = "S",
          shape = "rectangle",
          x = 5606.25,
          y = 493.75,
          width = 25,
          height = 25,
          rotation = 0,
          gid = 5,
          visible = true,
          properties = {}
        },
        {
          id = 1140,
          name = "",
          type = "S",
          shape = "rectangle",
          x = 5543.75,
          y = 493.75,
          width = 25,
          height = 25,
          rotation = 0,
          gid = 5,
          visible = true,
          properties = {}
        },
        {
          id = 1141,
          name = "",
          type = "S",
          shape = "rectangle",
          x = 5512.5,
          y = 493.75,
          width = 25,
          height = 25,
          rotation = 0,
          gid = 5,
          visible = true,
          properties = {}
        },
        {
          id = 1142,
          name = "",
          type = "S",
          shape = "rectangle",
          x = 5575,
          y = 493.75,
          width = 25,
          height = 25,
          rotation = 0,
          gid = 5,
          visible = true,
          properties = {}
        },
        {
          id = 1143,
          name = "",
          type = "PU1",
          shape = "rectangle",
          x = 5218.75,
          y = 525,
          width = 25,
          height = 25,
          rotation = 0,
          gid = 12,
          visible = true,
          properties = {}
        },
        {
          id = 1144,
          name = "",
          type = "G",
          shape = "rectangle",
          x = 4900,
          y = 847,
          width = 184,
          height = 312.75,
          rotation = 0,
          gid = 6,
          visible = true,
          properties = {}
        },
        {
          id = 1145,
          name = "",
          type = "SZG",
          shape = "rectangle",
          x = 6056.25,
          y = 540.75,
          width = 25,
          height = 256.25,
          rotation = 0,
          gid = 8,
          visible = true,
          properties = {}
        },
        {
          id = 1146,
          name = "",
          type = "PU4",
          shape = "rectangle",
          x = 3550,
          y = 443.75,
          width = 25,
          height = 25,
          rotation = 0,
          gid = 12,
          visible = true,
          properties = {}
        },
        {
          id = 1147,
          name = "",
          type = "PU3",
          shape = "rectangle",
          x = 4325,
          y = 400,
          width = 25,
          height = 25,
          rotation = 0,
          gid = 12,
          visible = true,
          properties = {}
        },
        {
          id = 1149,
          name = "",
          type = "G",
          shape = "rectangle",
          x = 6275,
          y = 537.5,
          width = 215.25,
          height = 71.75,
          rotation = 0,
          gid = 6,
          visible = true,
          properties = {}
        },
        {
          id = 1150,
          name = "",
          type = "EZG",
          shape = "rectangle",
          x = 7125,
          y = 537.5,
          width = 25,
          height = 253,
          rotation = 0,
          gid = 4,
          visible = true,
          properties = {}
        },
        {
          id = 1151,
          name = "",
          type = "G",
          shape = "rectangle",
          x = 6484,
          y = 534.5,
          width = 68.75,
          height = 156.25,
          rotation = 0,
          gid = 6,
          visible = true,
          properties = {}
        },
        {
          id = 1152,
          name = "",
          type = "G",
          shape = "rectangle",
          x = 6800,
          y = 459.5,
          width = 121.5,
          height = 56.25,
          rotation = 0,
          gid = 6,
          visible = true,
          properties = {}
        },
        {
          id = 1153,
          name = "",
          type = "C",
          shape = "rectangle",
          x = 5562.5,
          y = 418.75,
          width = 25,
          height = 25,
          rotation = 0,
          gid = 1,
          visible = true,
          properties = {}
        },
        {
          id = 1154,
          name = "",
          type = "C",
          shape = "rectangle",
          x = 6693.75,
          y = 412.5,
          width = 25,
          height = 25,
          rotation = 0,
          gid = 1,
          visible = true,
          properties = {}
        },
        {
          id = 1155,
          name = "",
          type = "P2",
          shape = "rectangle",
          x = 6800,
          y = 406.25,
          width = 50,
          height = 75,
          rotation = 0,
          gid = 10,
          visible = true,
          properties = {}
        },
        {
          id = 1156,
          name = "",
          type = "G",
          shape = "rectangle",
          x = 6800,
          y = 331.25,
          width = 121.5,
          height = 47,
          rotation = 0,
          gid = 6,
          visible = true,
          properties = {}
        },
        {
          id = 1157,
          name = "",
          type = "C",
          shape = "rectangle",
          x = 6875,
          y = 381.25,
          width = 25,
          height = 25,
          rotation = 0,
          gid = 1,
          visible = true,
          properties = {}
        }
      }
    }
  }
}
