return {
  version = "1.1",
  luaversion = "5.1",
  tiledversion = "0.17.1",
  orientation = "orthogonal",
  renderorder = "right-down",
  width = 500,
  height = 50,
  tilewidth = 25,
  tileheight = 25,
  nextobjectid = 1082,
  properties = {},
  tilesets = {
    {
      name = "tiles",
      firstgid = 1,
      tilewidth = 25,
      tileheight = 25,
      spacing = 0,
      margin = 0,
      tileoffset = {
        x = 0,
        y = 0
      },
      properties = {},
      terrains = {},
      tilecount = 14,
      tiles = {
        {
          id = 0,
          image = "E:/tiles/coinTile.png",
          width = 25,
          height = 25
        },
        {
          id = 1,
          image = "E:/tiles/darkTile.png",
          width = 25,
          height = 25
        },
        {
          id = 2,
          image = "E:/tiles/endGameTile.png",
          width = 25,
          height = 25
        },
        {
          id = 3,
          image = "E:/tiles/endZeroGravityTile.png",
          width = 25,
          height = 25
        },
        {
          id = 4,
          image = "E:/tiles/fatalTile.png",
          width = 25,
          height = 25
        },
        {
          id = 5,
          image = "E:/tiles/groundTile.png",
          width = 25,
          height = 25
        },
        {
          id = 6,
          image = "E:/tiles/lightTile.png",
          width = 25,
          height = 25
        },
        {
          id = 7,
          image = "E:/tiles/portal1Tile.png",
          width = 25,
          height = 25
        },
        {
          id = 8,
          image = "E:/tiles/portal2Tile.png",
          width = 25,
          height = 25
        },
        {
          id = 9,
          image = "E:/tiles/portal3Tile.png",
          width = 25,
          height = 25
        },
        {
          id = 10,
          image = "E:/tiles/portal4Tile.png",
          width = 25,
          height = 25
        },
        {
          id = 11,
          image = "E:/tiles/powerUpTile.png",
          width = 25,
          height = 25
        },
        {
          id = 12,
          image = "E:/tiles/spikeTile.png",
          width = 25,
          height = 25
        },
        {
          id = 13,
          image = "E:/tiles/startZeroGravityTile.png",
          width = 25,
          height = 25
        }
      }
    }
  },
  layers = {
    {
      type = "objectgroup",
      name = "Object Layer 1",
      visible = true,
      opacity = 1,
      offsetx = 166,
      offsety = 128,
      draworder = "topdown",
      properties = {},
      objects = {
        {
          id = 283,
          name = "",
          type = "G",
          shape = "rectangle",
          x = 25,
          y = 625,
          width = 2250,
          height = 50,
          rotation = 0,
          gid = 6,
          visible = true,
          properties = {}
        },
        {
          id = 376,
          name = "",
          type = "G",
          shape = "rectangle",
          x = 2931.25,
          y = 550,
          width = 3727.75,
          height = 50,
          rotation = 0,
          gid = 6,
          visible = true,
          properties = {}
        },
        {
          id = 622,
          name = "",
          type = "F",
          shape = "rectangle",
          x = 2852.75,
          y = 600,
          width = 78.5,
          height = 50,
          rotation = 0,
          gid = 5,
          visible = true,
          properties = {}
        },
        {
          id = 632,
          name = "",
          type = "G",
          shape = "rectangle",
          x = 1325,
          y = 575,
          width = 50,
          height = 50,
          rotation = 0,
          gid = 6,
          visible = true,
          properties = {}
        },
        {
          id = 640,
          name = "",
          type = "G",
          shape = "rectangle",
          x = 3081.25,
          y = 500,
          width = 325,
          height = 50,
          rotation = 0,
          gid = 6,
          visible = true,
          properties = {}
        },
        {
          id = 644,
          name = "",
          type = "G",
          shape = "rectangle",
          x = 3156.25,
          y = 450,
          width = 250,
          height = 50,
          rotation = 0,
          gid = 6,
          visible = true,
          properties = {}
        },
        {
          id = 656,
          name = "",
          type = "G",
          shape = "rectangle",
          x = 3256.25,
          y = 400,
          width = 150,
          height = 50,
          rotation = 0,
          gid = 6,
          visible = true,
          properties = {}
        },
        {
          id = 700,
          name = "",
          type = "S",
          shape = "rectangle",
          x = 3406.25,
          y = 500,
          width = 25,
          height = 25,
          rotation = 0,
          gid = 13,
          visible = true,
          properties = {}
        },
        {
          id = 701,
          name = "",
          type = "S",
          shape = "rectangle",
          x = 3431.25,
          y = 500,
          width = 25,
          height = 25,
          rotation = 0,
          gid = 13,
          visible = true,
          properties = {}
        },
        {
          id = 702,
          name = "",
          type = "S",
          shape = "rectangle",
          x = 3456.25,
          y = 500,
          width = 25,
          height = 25,
          rotation = 0,
          gid = 13,
          visible = true,
          properties = {}
        },
        {
          id = 703,
          name = "",
          type = "S",
          shape = "rectangle",
          x = 3481.25,
          y = 500,
          width = 25,
          height = 25,
          rotation = 0,
          gid = 13,
          visible = true,
          properties = {}
        },
        {
          id = 704,
          name = "",
          type = "S",
          shape = "rectangle",
          x = 3506.25,
          y = 500,
          width = 25,
          height = 25,
          rotation = 0,
          gid = 13,
          visible = true,
          properties = {}
        },
        {
          id = 707,
          name = "",
          type = "S",
          shape = "rectangle",
          x = 3531.25,
          y = 500,
          width = 25,
          height = 25,
          rotation = 0,
          gid = 13,
          visible = true,
          properties = {}
        },
        {
          id = 708,
          name = "",
          type = "S",
          shape = "rectangle",
          x = 3556.25,
          y = 500,
          width = 25,
          height = 25,
          rotation = 0,
          gid = 13,
          visible = true,
          properties = {}
        },
        {
          id = 709,
          name = "",
          type = "S",
          shape = "rectangle",
          x = 3581.25,
          y = 500,
          width = 25,
          height = 25,
          rotation = 0,
          gid = 13,
          visible = true,
          properties = {}
        },
        {
          id = 710,
          name = "",
          type = "S",
          shape = "rectangle",
          x = 3606.25,
          y = 500,
          width = 25,
          height = 25,
          rotation = 0,
          gid = 13,
          visible = true,
          properties = {}
        },
        {
          id = 711,
          name = "",
          type = "S",
          shape = "rectangle",
          x = 3631.25,
          y = 500,
          width = 25,
          height = 25,
          rotation = 0,
          gid = 13,
          visible = true,
          properties = {}
        },
        {
          id = 712,
          name = "",
          type = "S",
          shape = "rectangle",
          x = 3656.25,
          y = 500,
          width = 25,
          height = 25,
          rotation = 0,
          gid = 13,
          visible = true,
          properties = {}
        },
        {
          id = 713,
          name = "",
          type = "S",
          shape = "rectangle",
          x = 3681.25,
          y = 500,
          width = 25,
          height = 25,
          rotation = 0,
          gid = 13,
          visible = true,
          properties = {}
        },
        {
          id = 714,
          name = "",
          type = "S",
          shape = "rectangle",
          x = 3706.25,
          y = 500,
          width = 25,
          height = 25,
          rotation = 0,
          gid = 13,
          visible = true,
          properties = {}
        },
        {
          id = 715,
          name = "",
          type = "S",
          shape = "rectangle",
          x = 3731.25,
          y = 500,
          width = 25,
          height = 25,
          rotation = 0,
          gid = 13,
          visible = true,
          properties = {}
        },
        {
          id = 716,
          name = "",
          type = "S",
          shape = "rectangle",
          x = 3756.25,
          y = 500,
          width = 25,
          height = 25,
          rotation = 0,
          gid = 13,
          visible = true,
          properties = {}
        },
        {
          id = 717,
          name = "",
          type = "S",
          shape = "rectangle",
          x = 3781.25,
          y = 500,
          width = 25,
          height = 25,
          rotation = 0,
          gid = 13,
          visible = true,
          properties = {}
        },
        {
          id = 718,
          name = "",
          type = "S",
          shape = "rectangle",
          x = 3806.25,
          y = 500,
          width = 25,
          height = 25,
          rotation = 0,
          gid = 13,
          visible = true,
          properties = {}
        },
        {
          id = 719,
          name = "",
          type = "S",
          shape = "rectangle",
          x = 3831.25,
          y = 500,
          width = 25,
          height = 25,
          rotation = 0,
          gid = 13,
          visible = true,
          properties = {}
        },
        {
          id = 720,
          name = "",
          type = "S",
          shape = "rectangle",
          x = 3856.25,
          y = 500,
          width = 25,
          height = 25,
          rotation = 0,
          gid = 13,
          visible = true,
          properties = {}
        },
        {
          id = 721,
          name = "",
          type = "S",
          shape = "rectangle",
          x = 3881.25,
          y = 500,
          width = 25,
          height = 25,
          rotation = 0,
          gid = 13,
          visible = true,
          properties = {}
        },
        {
          id = 722,
          name = "",
          type = "S",
          shape = "rectangle",
          x = 3906.25,
          y = 500,
          width = 25,
          height = 25,
          rotation = 0,
          gid = 13,
          visible = true,
          properties = {}
        },
        {
          id = 723,
          name = "",
          type = "S",
          shape = "rectangle",
          x = 3931.25,
          y = 500,
          width = 25,
          height = 25,
          rotation = 0,
          gid = 13,
          visible = true,
          properties = {}
        },
        {
          id = 724,
          name = "",
          type = "S",
          shape = "rectangle",
          x = 3956.25,
          y = 500,
          width = 25,
          height = 25,
          rotation = 0,
          gid = 13,
          visible = true,
          properties = {}
        },
        {
          id = 725,
          name = "",
          type = "S",
          shape = "rectangle",
          x = 3981.25,
          y = 500,
          width = 25,
          height = 25,
          rotation = 0,
          gid = 13,
          visible = true,
          properties = {}
        },
        {
          id = 726,
          name = "",
          type = "S",
          shape = "rectangle",
          x = 4006.25,
          y = 500,
          width = 25,
          height = 25,
          rotation = 0,
          gid = 13,
          visible = true,
          properties = {}
        },
        {
          id = 727,
          name = "",
          type = "S",
          shape = "rectangle",
          x = 4031.25,
          y = 500,
          width = 25,
          height = 25,
          rotation = 0,
          gid = 13,
          visible = true,
          properties = {}
        },
        {
          id = 728,
          name = "",
          type = "S",
          shape = "rectangle",
          x = 4056.25,
          y = 500,
          width = 25,
          height = 25,
          rotation = 0,
          gid = 13,
          visible = true,
          properties = {}
        },
        {
          id = 729,
          name = "",
          type = "S",
          shape = "rectangle",
          x = 4081.25,
          y = 500,
          width = 25,
          height = 25,
          rotation = 0,
          gid = 13,
          visible = true,
          properties = {}
        },
        {
          id = 730,
          name = "",
          type = "S",
          shape = "rectangle",
          x = 4106.25,
          y = 500,
          width = 25,
          height = 25,
          rotation = 0,
          gid = 13,
          visible = true,
          properties = {}
        },
        {
          id = 733,
          name = "",
          type = "G",
          shape = "rectangle",
          x = 3506.25,
          y = 400,
          width = 75,
          height = 25,
          rotation = 0,
          gid = 6,
          visible = true,
          properties = {}
        },
        {
          id = 759,
          name = "",
          type = "G",
          shape = "rectangle",
          x = 4131.25,
          y = 500,
          width = 150,
          height = 125,
          rotation = 0,
          gid = 6,
          visible = true,
          properties = {}
        },
        {
          id = 798,
          name = "",
          type = "C",
          shape = "rectangle",
          x = 1337.5,
          y = 450,
          width = 25,
          height = 25,
          rotation = 0,
          gid = 1,
          visible = true,
          properties = {}
        },
        {
          id = 799,
          name = "",
          type = "C",
          shape = "rectangle",
          x = 2881.25,
          y = 412.5,
          width = 25,
          height = 25,
          rotation = 0,
          gid = 1,
          visible = true,
          properties = {}
        },
        {
          id = 802,
          name = "",
          type = "C",
          shape = "rectangle",
          x = 3331.25,
          y = 337.5,
          width = 25,
          height = 25,
          rotation = 0,
          gid = 1,
          visible = true,
          properties = {}
        },
        {
          id = 803,
          name = "",
          type = "C",
          shape = "rectangle",
          x = 3618.75,
          y = 300,
          width = 25,
          height = 25,
          rotation = 0,
          gid = 1,
          visible = true,
          properties = {}
        },
        {
          id = 804,
          name = "",
          type = "C",
          shape = "rectangle",
          x = 3793.75,
          y = 300,
          width = 25,
          height = 25,
          rotation = 0,
          gid = 1,
          visible = true,
          properties = {}
        },
        {
          id = 805,
          name = "",
          type = "C",
          shape = "rectangle",
          x = 3968.75,
          y = 300,
          width = 25,
          height = 25,
          rotation = 0,
          gid = 1,
          visible = true,
          properties = {}
        },
        {
          id = 806,
          name = "",
          type = "C",
          shape = "rectangle",
          x = 4231.25,
          y = 356.25,
          width = 25,
          height = 25,
          rotation = 0,
          gid = 1,
          visible = true,
          properties = {}
        },
        {
          id = 991,
          name = "",
          type = "G",
          shape = "rectangle",
          x = 3856.25,
          y = 400,
          width = 75,
          height = 25,
          rotation = 0,
          gid = 6,
          visible = true,
          properties = {}
        },
        {
          id = 994,
          name = "",
          type = "EG",
          shape = "rectangle",
          x = 6125,
          y = 500,
          width = 25,
          height = 400,
          rotation = 0,
          gid = 3,
          visible = true,
          properties = {}
        },
        {
          id = 1026,
          name = "",
          type = "PU1",
          shape = "rectangle",
          x = 4575,
          y = 475,
          width = 25,
          height = 25,
          rotation = 0,
          gid = 12,
          visible = true,
          properties = {}
        },
        {
          id = 1062,
          name = "",
          type = "G",
          shape = "rectangle",
          x = 425,
          y = 575,
          width = 25,
          height = 25,
          rotation = 0,
          gid = 6,
          visible = true,
          properties = {}
        },
        {
          id = 1063,
          name = "",
          type = "G",
          shape = "rectangle",
          x = 825,
          y = 575,
          width = 25,
          height = 25,
          rotation = 0,
          gid = 6,
          visible = true,
          properties = {}
        },
        {
          id = 1064,
          name = "",
          type = "G",
          shape = "rectangle",
          x = 950,
          y = 575,
          width = 25,
          height = 25,
          rotation = 0,
          gid = 6,
          visible = true,
          properties = {}
        },
        {
          id = 1065,
          name = "",
          type = "G",
          shape = "rectangle",
          x = 1600,
          y = 575,
          width = 200,
          height = 75,
          rotation = 0,
          gid = 6,
          visible = true,
          properties = {}
        },
        {
          id = 1066,
          name = "",
          type = "G",
          shape = "rectangle",
          x = 1725,
          y = 500,
          width = 75,
          height = 50,
          rotation = 0,
          gid = 6,
          visible = true,
          properties = {}
        },
        {
          id = 1067,
          name = "",
          type = "G",
          shape = "rectangle",
          x = 1900,
          y = 475,
          width = 75,
          height = 25,
          rotation = 0,
          gid = 6,
          visible = true,
          properties = {}
        },
        {
          id = 1069,
          name = "",
          type = "G",
          shape = "rectangle",
          x = 2075,
          y = 475,
          width = 75,
          height = 25,
          rotation = 0,
          gid = 6,
          visible = true,
          properties = {}
        },
        {
          id = 1070,
          name = "",
          type = "G",
          shape = "rectangle",
          x = 2275,
          y = 625,
          width = 175,
          height = 175,
          rotation = 0,
          gid = 6,
          visible = true,
          properties = {}
        },
        {
          id = 1071,
          name = "",
          type = "G",
          shape = "rectangle",
          x = 2450,
          y = 625,
          width = 400,
          height = 125,
          rotation = 0,
          gid = 6,
          visible = true,
          properties = {}
        },
        {
          id = 1074,
          name = "",
          type = "G",
          shape = "rectangle",
          x = 3681.25,
          y = 400,
          width = 75,
          height = 25,
          rotation = 0,
          gid = 6,
          visible = true,
          properties = {}
        },
        {
          id = 1075,
          name = "",
          type = "G",
          shape = "rectangle",
          x = 4031.25,
          y = 400,
          width = 102.75,
          height = 25,
          rotation = 0,
          gid = 6,
          visible = true,
          properties = {}
        },
        {
          id = 1076,
          name = "",
          type = "C",
          shape = "rectangle",
          x = 2012.5,
          y = 387.5,
          width = 25,
          height = 25,
          rotation = 0,
          gid = 1,
          visible = true,
          properties = {}
        },
        {
          id = 1078,
          name = "",
          type = "G",
          shape = "rectangle",
          x = 4850,
          y = 500,
          width = 150,
          height = 50,
          rotation = 0,
          gid = 6,
          visible = true,
          properties = {}
        },
        {
          id = 1079,
          name = "",
          type = "G",
          shape = "rectangle",
          x = 5775,
          y = 500,
          width = 177.75,
          height = 200,
          rotation = 0,
          gid = 6,
          visible = true,
          properties = {}
        },
        {
          id = 1080,
          name = "",
          type = "PU2",
          shape = "rectangle",
          x = 5600,
          y = 475,
          width = 25,
          height = 25,
          rotation = 0,
          gid = 12,
          visible = true,
          properties = {}
        },
        {
          id = 1081,
          name = "",
          type = "G",
          shape = "rectangle",
          x = 2200,
          y = 575,
          width = 75,
          height = 59.25,
          rotation = 0,
          gid = 6,
          visible = true,
          properties = {}
        }
      }
    }
  }
}
