return {
  version = "1.1",
  luaversion = "5.1",
  tiledversion = "0.17.1",
  orientation = "orthogonal",
  renderorder = "right-down",
  width = 500,
  height = 50,
  tilewidth = 25,
  tileheight = 25,
  nextobjectid = 1221,
  properties = {},
  tilesets = {
    {
      name = "tiles",
      firstgid = 1,
      tilewidth = 25,
      tileheight = 25,
      spacing = 0,
      margin = 0,
      tileoffset = {
        x = 0,
        y = 0
      },
      properties = {},
      terrains = {},
      tilecount = 14,
      tiles = {
        {
          id = 0,
          image = "tiledFiles/tiles/coinTile.png",
          width = 25,
          height = 25
        },
        {
          id = 1,
          image = "tiledFiles/tiles/darkTile.png",
          width = 25,
          height = 25
        },
        {
          id = 2,
          image = "tiledFiles/tiles/endGameTile.png",
          width = 25,
          height = 25
        },
        {
          id = 3,
          image = "tiledFiles/tiles/endZeroGravityTile.png",
          width = 25,
          height = 25
        },
        {
          id = 4,
          image = "tiledFiles/tiles/fatalTile.png",
          width = 25,
          height = 25
        },
        {
          id = 5,
          image = "tiledFiles/tiles/groundTile.png",
          width = 25,
          height = 25
        },
        {
          id = 6,
          image = "tiledFiles/tiles/lightTile.png",
          width = 25,
          height = 25
        },
        {
          id = 7,
          image = "tiledFiles/tiles/portal1Tile.png",
          width = 25,
          height = 25
        },
        {
          id = 8,
          image = "tiledFiles/tiles/portal2Tile.png",
          width = 25,
          height = 25
        },
        {
          id = 9,
          image = "tiledFiles/tiles/portal3Tile.png",
          width = 25,
          height = 25
        },
        {
          id = 10,
          image = "tiledFiles/tiles/portal4Tile.png",
          width = 25,
          height = 25
        },
        {
          id = 11,
          image = "tiledFiles/tiles/powerUpTile.png",
          width = 25,
          height = 25
        },
        {
          id = 12,
          image = "tiledFiles/tiles/spikeTile.png",
          width = 25,
          height = 25
        },
        {
          id = 13,
          image = "tiledFiles/tiles/startZeroGravityTile.png",
          width = 25,
          height = 25
        }
      }
    }
  },
  layers = {
    {
      type = "objectgroup",
      name = "Object Layer 1",
      visible = true,
      opacity = 1,
      offsetx = 166,
      offsety = 128,
      draworder = "topdown",
      properties = {},
      objects = {
        {
          id = 283,
          name = "",
          type = "G",
          shape = "rectangle",
          x = -53.5,
          y = 865.75,
          width = 1018.75,
          height = 290.75,
          rotation = 0,
          gid = 6,
          visible = true,
          properties = {}
        },
        {
          id = 994,
          name = "",
          type = "EG",
          shape = "rectangle",
          x = 8331.25,
          y = 406.5,
          width = 25,
          height = 375,
          rotation = 0,
          gid = 3,
          visible = true,
          properties = {}
        },
        {
          id = 1082,
          name = "",
          type = "C",
          shape = "rectangle",
          x = 500,
          y = 450.25,
          width = 25,
          height = 25,
          rotation = 0,
          gid = 1,
          visible = true,
          properties = {}
        },
        {
          id = 1083,
          name = "",
          type = "G",
          shape = "rectangle",
          x = 850,
          y = 351.25,
          width = 1115.25,
          height = 228,
          rotation = 0,
          gid = 6,
          visible = true,
          properties = {}
        },
        {
          id = 1085,
          name = "",
          type = "G",
          shape = "rectangle",
          x = 1327.75,
          y = 865.75,
          width = 947.25,
          height = 290.75,
          rotation = 0,
          gid = 6,
          visible = true,
          properties = {}
        },
        {
          id = 1089,
          name = "",
          type = "F",
          shape = "rectangle",
          x = 965.25,
          y = 859.5,
          width = 362.5,
          height = 134.5,
          rotation = 0,
          gid = 5,
          visible = true,
          properties = {}
        },
        {
          id = 1090,
          name = "",
          type = "C",
          shape = "rectangle",
          x = 1218.75,
          y = 493.75,
          width = 25,
          height = 25,
          rotation = 0,
          gid = 1,
          visible = true,
          properties = {}
        },
        {
          id = 1091,
          name = "",
          type = "L",
          shape = "rectangle",
          x = 1575,
          y = 575,
          width = 25,
          height = 225,
          rotation = 0,
          gid = 7,
          visible = true,
          properties = {}
        },
        {
          id = 1092,
          name = "",
          type = "D",
          shape = "rectangle",
          x = 1825,
          y = 575,
          width = 25,
          height = 225,
          rotation = 0,
          gid = 12,
          visible = true,
          properties = {}
        },
        {
          id = 1095,
          name = "",
          type = "G",
          shape = "rectangle",
          x = 2246.5,
          y = 865.75,
          width = 306.25,
          height = 390.75,
          rotation = 0,
          gid = 6,
          visible = true,
          properties = {}
        },
        {
          id = 1096,
          name = "",
          type = "G",
          shape = "rectangle",
          x = 1943.75,
          y = 276.25,
          width = 1752.75,
          height = 153,
          rotation = 0,
          gid = 6,
          visible = true,
          properties = {}
        },
        {
          id = 1098,
          name = "",
          type = "L",
          shape = "rectangle",
          x = 2250,
          y = 475,
          width = 25,
          height = 200,
          rotation = 0,
          gid = 7,
          visible = true,
          properties = {}
        },
        {
          id = 1099,
          name = "",
          type = "C",
          shape = "rectangle",
          x = 2206.25,
          y = 462.5,
          width = 25,
          height = 25,
          rotation = 0,
          gid = 1,
          visible = true,
          properties = {}
        },
        {
          id = 1100,
          name = "",
          type = "G",
          shape = "rectangle",
          x = 3271.5,
          y = 865.75,
          width = 846.75,
          height = 390.75,
          rotation = 0,
          gid = 6,
          visible = true,
          properties = {}
        },
        {
          id = 1101,
          name = "",
          type = "L",
          shape = "rectangle",
          x = 2550,
          y = 500,
          width = 325,
          height = 25,
          rotation = 0,
          gid = 7,
          visible = true,
          properties = {}
        },
        {
          id = 1102,
          name = "",
          type = "F",
          shape = "rectangle",
          x = 2550,
          y = 778.25,
          width = 727.75,
          height = 153.25,
          rotation = 0,
          gid = 5,
          visible = true,
          properties = {}
        },
        {
          id = 1105,
          name = "",
          type = "G",
          shape = "rectangle",
          x = 3609.25,
          y = 475,
          width = 84,
          height = 50,
          rotation = 0,
          gid = 6,
          visible = true,
          properties = {}
        },
        {
          id = 1109,
          name = "",
          type = "C",
          shape = "rectangle",
          x = 2900,
          y = 437.5,
          width = 25,
          height = 25,
          rotation = 0,
          gid = 1,
          visible = true,
          properties = {}
        },
        {
          id = 1111,
          name = "",
          type = "G",
          shape = "rectangle",
          x = 4634.25,
          y = 506.25,
          width = 75,
          height = 25,
          rotation = 0,
          gid = 6,
          visible = true,
          properties = {}
        },
        {
          id = 1115,
          name = "",
          type = "G",
          shape = "rectangle",
          x = 4209.25,
          y = 525,
          width = 75,
          height = 25,
          rotation = 0,
          gid = 6,
          visible = true,
          properties = {}
        },
        {
          id = 1120,
          name = "",
          type = "S",
          shape = "rectangle",
          x = 3750,
          y = 625,
          width = 25,
          height = 25,
          rotation = 0,
          gid = 13,
          visible = true,
          properties = {}
        },
        {
          id = 1124,
          name = "",
          type = "S",
          shape = "rectangle",
          x = 3725,
          y = 625,
          width = 25,
          height = 25,
          rotation = 0,
          gid = 13,
          visible = true,
          properties = {}
        },
        {
          id = 1127,
          name = "",
          type = "S",
          shape = "rectangle",
          x = 3700,
          y = 625,
          width = 25,
          height = 25,
          rotation = 0,
          gid = 13,
          visible = true,
          properties = {}
        },
        {
          id = 1145,
          name = "",
          type = "G",
          shape = "rectangle",
          x = 4815.5,
          y = 790.75,
          width = 596.5,
          height = 293.75,
          rotation = 0,
          gid = 6,
          visible = true,
          properties = {}
        },
        {
          id = 1147,
          name = "",
          type = "C",
          shape = "rectangle",
          x = 4334.25,
          y = 437.5,
          width = 25,
          height = 25,
          rotation = 0,
          gid = 1,
          visible = true,
          properties = {}
        },
        {
          id = 1148,
          name = "",
          type = "C",
          shape = "rectangle",
          x = 4606.25,
          y = 437.5,
          width = 25,
          height = 25,
          rotation = 0,
          gid = 1,
          visible = true,
          properties = {}
        },
        {
          id = 1149,
          name = "",
          type = "L",
          shape = "rectangle",
          x = 850,
          y = 575,
          width = 25,
          height = 225,
          rotation = 0,
          gid = 7,
          visible = true,
          properties = {}
        },
        {
          id = 1151,
          name = "",
          type = "G",
          shape = "rectangle",
          x = 2875,
          y = 500,
          width = 70,
          height = 25,
          rotation = 0,
          gid = 6,
          visible = true,
          properties = {}
        },
        {
          id = 1152,
          name = "",
          type = "D",
          shape = "rectangle",
          x = 2943.75,
          y = 500,
          width = 327.75,
          height = 25,
          rotation = 0,
          gid = 12,
          visible = true,
          properties = {}
        },
        {
          id = 1153,
          name = "",
          type = "S",
          shape = "rectangle",
          x = 2875,
          y = 475,
          width = 25,
          height = 25,
          rotation = 0,
          gid = 5,
          visible = true,
          properties = {}
        },
        {
          id = 1154,
          name = "",
          type = "S",
          shape = "rectangle",
          x = 2910,
          y = 475,
          width = 25,
          height = 25,
          rotation = 0,
          gid = 5,
          visible = true,
          properties = {}
        },
        {
          id = 1156,
          name = "",
          type = "L",
          shape = "rectangle",
          x = 1125,
          y = 600,
          width = 50,
          height = 25,
          rotation = 0,
          gid = 7,
          visible = true,
          properties = {}
        },
        {
          id = 1157,
          name = "",
          type = "D",
          shape = "rectangle",
          x = 3609.25,
          y = 428.25,
          width = 84,
          height = 153,
          rotation = 0,
          gid = 12,
          visible = true,
          properties = {}
        },
        {
          id = 1158,
          name = "",
          type = "D",
          shape = "rectangle",
          x = 4412.5,
          y = 497,
          width = 75,
          height = 25,
          rotation = 0,
          gid = 12,
          visible = true,
          properties = {}
        },
        {
          id = 1159,
          name = "",
          type = "L",
          shape = "rectangle",
          x = 5006.75,
          y = 409.25,
          width = 112.5,
          height = 25,
          rotation = 0,
          gid = 7,
          visible = true,
          properties = {}
        },
        {
          id = 1160,
          name = "",
          type = "D",
          shape = "rectangle",
          x = 5134,
          y = 337.5,
          width = 118.75,
          height = 25,
          rotation = 0,
          gid = 12,
          visible = true,
          properties = {}
        },
        {
          id = 1162,
          name = "",
          type = "G",
          shape = "rectangle",
          x = 5252.75,
          y = 418.75,
          width = 400,
          height = 178,
          rotation = 0,
          gid = 6,
          visible = true,
          properties = {}
        },
        {
          id = 1163,
          name = "",
          type = "G",
          shape = "rectangle",
          x = 5131.25,
          y = 50,
          width = 652.75,
          height = 178,
          rotation = 0,
          gid = 6,
          visible = true,
          properties = {}
        },
        {
          id = 1164,
          name = "",
          type = "G",
          shape = "rectangle",
          x = 5415.25,
          y = 168.75,
          width = 131.25,
          height = 25,
          rotation = 0,
          gid = 6,
          visible = true,
          properties = {}
        },
        {
          id = 1165,
          name = "",
          type = "P1",
          shape = "rectangle",
          x = 5443.75,
          y = 143.75,
          width = 50,
          height = 75,
          rotation = 0,
          gid = 10,
          visible = true,
          properties = {}
        },
        {
          id = 1166,
          name = "",
          type = "C",
          shape = "rectangle",
          x = 5512.5,
          y = 139.5,
          width = 25,
          height = 25,
          rotation = 0,
          gid = 1,
          visible = true,
          properties = {}
        },
        {
          id = 1167,
          name = "",
          type = "PU3",
          shape = "rectangle",
          x = 5575,
          y = 231.25,
          width = 25,
          height = 25,
          rotation = 0,
          gid = 12,
          visible = true,
          properties = {}
        },
        {
          id = 1168,
          name = "",
          type = "G",
          shape = "rectangle",
          x = 5784,
          y = 415.75,
          width = 497.25,
          height = 543.75,
          rotation = 0,
          gid = 6,
          visible = true,
          properties = {}
        },
        {
          id = 1169,
          name = "",
          type = "G",
          shape = "rectangle",
          x = 5411.5,
          y = 790.75,
          width = 3403.75,
          height = 215.75,
          rotation = 0,
          gid = 6,
          visible = true,
          properties = {}
        },
        {
          id = 1170,
          name = "",
          type = "S",
          shape = "rectangle",
          x = 5412.5,
          y = 575,
          width = 25,
          height = 25,
          rotation = 0,
          gid = 5,
          visible = true,
          properties = {}
        },
        {
          id = 1171,
          name = "",
          type = "S",
          shape = "rectangle",
          x = 5447.5,
          y = 575,
          width = 25,
          height = 25,
          rotation = 0,
          gid = 5,
          visible = true,
          properties = {}
        },
        {
          id = 1173,
          name = "",
          type = "S",
          shape = "rectangle",
          x = 5483,
          y = 575,
          width = 25,
          height = 25,
          rotation = 0,
          gid = 5,
          visible = true,
          properties = {}
        },
        {
          id = 1175,
          name = "",
          type = "S",
          shape = "rectangle",
          x = 5518.25,
          y = 575,
          width = 25,
          height = 25,
          rotation = 0,
          gid = 5,
          visible = true,
          properties = {}
        },
        {
          id = 1177,
          name = "",
          type = "S",
          shape = "rectangle",
          x = 5553.75,
          y = 575,
          width = 25,
          height = 25,
          rotation = 0,
          gid = 5,
          visible = true,
          properties = {}
        },
        {
          id = 1180,
          name = "",
          type = "S",
          shape = "rectangle",
          x = 5589.25,
          y = 575,
          width = 25,
          height = 25,
          rotation = 0,
          gid = 5,
          visible = true,
          properties = {}
        },
        {
          id = 1181,
          name = "",
          type = "S",
          shape = "rectangle",
          x = 5624.75,
          y = 575,
          width = 25,
          height = 25,
          rotation = 0,
          gid = 5,
          visible = true,
          properties = {}
        },
        {
          id = 1183,
          name = "",
          type = "L",
          shape = "rectangle",
          x = 5412.5,
          y = 550,
          width = 240.25,
          height = 28,
          rotation = 0,
          gid = 7,
          visible = true,
          properties = {}
        },
        {
          id = 1184,
          name = "",
          type = "G",
          shape = "rectangle",
          x = 6281.25,
          y = 15.75,
          width = 2527.75,
          height = 143.75,
          rotation = 0,
          gid = 6,
          visible = true,
          properties = {}
        },
        {
          id = 1185,
          name = "",
          type = "SZG",
          shape = "rectangle",
          x = 6375,
          y = 578.25,
          width = 25,
          height = 562.5,
          rotation = 0,
          gid = 8,
          visible = true,
          properties = {}
        },
        {
          id = 1186,
          name = "",
          type = "EZG",
          shape = "rectangle",
          x = 7925,
          y = 403.25,
          width = 25,
          height = 125,
          rotation = 0,
          gid = 4,
          visible = true,
          properties = {}
        },
        {
          id = 1187,
          name = "",
          type = "G",
          shape = "rectangle",
          x = 6793.75,
          y = 575,
          width = 125,
          height = 134.25,
          rotation = 0,
          gid = 6,
          visible = true,
          properties = {}
        },
        {
          id = 1188,
          name = "",
          type = "G",
          shape = "rectangle",
          x = 7112.5,
          y = 431.25,
          width = 125,
          height = 109.25,
          rotation = 0,
          gid = 6,
          visible = true,
          properties = {}
        },
        {
          id = 1189,
          name = "",
          type = "G",
          shape = "rectangle",
          x = 7112.5,
          y = 131.25,
          width = 125,
          height = 115.5,
          rotation = 0,
          gid = 6,
          visible = true,
          properties = {}
        },
        {
          id = 1190,
          name = "",
          type = "G",
          shape = "rectangle",
          x = 7375,
          y = 593.75,
          width = 125,
          height = 115.5,
          rotation = 0,
          gid = 6,
          visible = true,
          properties = {}
        },
        {
          id = 1191,
          name = "",
          type = "G",
          shape = "rectangle",
          x = 7393.75,
          y = 290.75,
          width = 125,
          height = 103.25,
          rotation = 0,
          gid = 6,
          visible = true,
          properties = {}
        },
        {
          id = 1192,
          name = "",
          type = "G",
          shape = "rectangle",
          x = 7112.5,
          y = 237.5,
          width = 125,
          height = 25,
          rotation = 0,
          gid = 6,
          visible = true,
          properties = {}
        },
        {
          id = 1193,
          name = "",
          type = "P2",
          shape = "rectangle",
          x = 7112.5,
          y = 212.5,
          width = 50,
          height = 84.25,
          rotation = 0,
          gid = 10,
          visible = true,
          properties = {}
        },
        {
          id = 1194,
          name = "",
          type = "C",
          shape = "rectangle",
          x = 7187.5,
          y = 187.5,
          width = 25,
          height = 25,
          rotation = 0,
          gid = 1,
          visible = true,
          properties = {}
        },
        {
          id = 1197,
          name = "",
          type = "L",
          shape = "rectangle",
          x = 7212.5,
          y = 325,
          width = 25,
          height = 90.5,
          rotation = 0,
          gid = 7,
          visible = true,
          properties = {}
        },
        {
          id = 1198,
          name = "",
          type = "L",
          shape = "rectangle",
          x = 7212.5,
          y = 578.25,
          width = 25,
          height = 150,
          rotation = 0,
          gid = 7,
          visible = true,
          properties = {}
        },
        {
          id = 1199,
          name = "",
          type = "D",
          shape = "rectangle",
          x = 7112.5,
          y = 578.25,
          width = 25,
          height = 150.25,
          rotation = 0,
          gid = 12,
          visible = true,
          properties = {}
        },
        {
          id = 1200,
          name = "",
          type = "D",
          shape = "rectangle",
          x = 7112.5,
          y = 322,
          width = 25,
          height = 84.75,
          rotation = 0,
          gid = 12,
          visible = true,
          properties = {}
        },
        {
          id = 1205,
          name = "",
          type = "S",
          shape = "rectangle",
          x = 7421.5,
          y = 481.25,
          width = 25,
          height = 25,
          rotation = 0,
          gid = 5,
          visible = true,
          properties = {}
        },
        {
          id = 1206,
          name = "",
          type = "S",
          shape = "rectangle",
          x = 7457,
          y = 481.25,
          width = 25,
          height = 25,
          rotation = 0,
          gid = 5,
          visible = true,
          properties = {}
        },
        {
          id = 1207,
          name = "",
          type = "S",
          shape = "rectangle",
          x = 7386.5,
          y = 481.25,
          width = 25,
          height = 25,
          rotation = 0,
          gid = 5,
          visible = true,
          properties = {}
        },
        {
          id = 1208,
          name = "",
          type = "S",
          shape = "rectangle",
          x = 7405.25,
          y = 190.75,
          width = 25,
          height = 25,
          rotation = 0,
          gid = 5,
          visible = true,
          properties = {}
        },
        {
          id = 1209,
          name = "",
          type = "S",
          shape = "rectangle",
          x = 7475.75,
          y = 190.75,
          width = 25,
          height = 25,
          rotation = 0,
          gid = 5,
          visible = true,
          properties = {}
        },
        {
          id = 1210,
          name = "",
          type = "S",
          shape = "rectangle",
          x = 7440.25,
          y = 190.75,
          width = 25,
          height = 25,
          rotation = 0,
          gid = 5,
          visible = true,
          properties = {}
        },
        {
          id = 1211,
          name = "",
          type = "PU3",
          shape = "rectangle",
          x = 7162.5,
          y = 293.75,
          width = 25,
          height = 25,
          rotation = 0,
          gid = 12,
          visible = true,
          properties = {}
        },
        {
          id = 1212,
          name = "",
          type = "G",
          shape = "rectangle",
          x = 7600,
          y = 97,
          width = 125,
          height = 84.5,
          rotation = 0,
          gid = 6,
          visible = true,
          properties = {}
        },
        {
          id = 1213,
          name = "",
          type = "G",
          shape = "rectangle",
          x = 7725,
          y = 178.25,
          width = 125,
          height = 169,
          rotation = 0,
          gid = 6,
          visible = true,
          properties = {}
        },
        {
          id = 1214,
          name = "",
          type = "G",
          shape = "rectangle",
          x = 7850,
          y = 278.25,
          width = 352.75,
          height = 266,
          rotation = 0,
          gid = 6,
          visible = true,
          properties = {}
        },
        {
          id = 1216,
          name = "",
          type = "G",
          shape = "rectangle",
          x = 7725,
          y = 575,
          width = 1090.25,
          height = 169,
          rotation = 0,
          gid = 6,
          visible = true,
          properties = {}
        },
        {
          id = 1217,
          name = "",
          type = "G",
          shape = "rectangle",
          x = 7600,
          y = 575,
          width = 125,
          height = 84.5,
          rotation = 0,
          gid = 6,
          visible = true,
          properties = {}
        },
        {
          id = 1218,
          name = "",
          type = "F",
          shape = "rectangle",
          x = 4109,
          y = 822,
          width = 725,
          height = 207,
          rotation = 0,
          gid = 5,
          visible = true,
          properties = {}
        },
        {
          id = 1219,
          name = "",
          type = "D",
          shape = "rectangle",
          x = 5627,
          y = 240.75,
          width = 25,
          height = 193.75,
          rotation = 0,
          gid = 12,
          visible = true,
          properties = {}
        },
        {
          id = 1220,
          name = "",
          type = "L",
          shape = "rectangle",
          x = 6143.75,
          y = 575,
          width = 25,
          height = 159.25,
          rotation = 0,
          gid = 7,
          visible = true,
          properties = {}
        }
      }
    }
  }
}
