return {
  version = "1.1",
  luaversion = "5.1",
  tiledversion = "0.17.1",
  orientation = "orthogonal",
  renderorder = "right-down",
  width = 500,
  height = 50,
  tilewidth = 25,
  tileheight = 25,
  nextobjectid = 1149,
  properties = {},
  tilesets = {
    {
      name = "tiles",
      firstgid = 1,
      tilewidth = 25,
      tileheight = 25,
      spacing = 0,
      margin = 0,
      tileoffset = {
        x = 0,
        y = 0
      },
      properties = {},
      terrains = {},
      tilecount = 14,
      tiles = {
        {
          id = 0,
          image = "E:/tiles/coinTile.png",
          width = 25,
          height = 25
        },
        {
          id = 1,
          image = "E:/tiles/darkTile.png",
          width = 25,
          height = 25
        },
        {
          id = 2,
          image = "E:/tiles/endGameTile.png",
          width = 25,
          height = 25
        },
        {
          id = 3,
          image = "E:/tiles/endZeroGravityTile.png",
          width = 25,
          height = 25
        },
        {
          id = 4,
          image = "E:/tiles/fatalTile.png",
          width = 25,
          height = 25
        },
        {
          id = 5,
          image = "E:/tiles/groundTile.png",
          width = 25,
          height = 25
        },
        {
          id = 6,
          image = "E:/tiles/lightTile.png",
          width = 25,
          height = 25
        },
        {
          id = 7,
          image = "E:/tiles/portal1Tile.png",
          width = 25,
          height = 25
        },
        {
          id = 8,
          image = "E:/tiles/portal2Tile.png",
          width = 25,
          height = 25
        },
        {
          id = 9,
          image = "E:/tiles/portal3Tile.png",
          width = 25,
          height = 25
        },
        {
          id = 10,
          image = "E:/tiles/portal4Tile.png",
          width = 25,
          height = 25
        },
        {
          id = 11,
          image = "E:/tiles/powerUpTile.png",
          width = 25,
          height = 25
        },
        {
          id = 12,
          image = "E:/tiles/spikeTile.png",
          width = 25,
          height = 25
        },
        {
          id = 13,
          image = "E:/tiles/startZeroGravityTile.png",
          width = 25,
          height = 25
        }
      }
    }
  },
  layers = {
    {
      type = "objectgroup",
      name = "Object Layer 1",
      visible = true,
      opacity = 1,
      offsetx = 166,
      offsety = 128,
      draworder = "topdown",
      properties = {},
      objects = {
        {
          id = 283,
          name = "",
          type = "G",
          shape = "rectangle",
          x = 25,
          y = 865.75,
          width = 1127.75,
          height = 290.75,
          rotation = 0,
          gid = 6,
          visible = true,
          properties = {}
        },
        {
          id = 994,
          name = "",
          type = "EG",
          shape = "rectangle",
          x = 4693.75,
          y = 431.25,
          width = 25,
          height = 400,
          rotation = 0,
          gid = 3,
          visible = true,
          properties = {}
        },
        {
          id = 1082,
          name = "",
          type = "C",
          shape = "rectangle",
          x = 500,
          y = 450.25,
          width = 25,
          height = 25,
          rotation = 0,
          gid = 1,
          visible = true,
          properties = {}
        },
        {
          id = 1083,
          name = "",
          type = "G",
          shape = "rectangle",
          x = 850,
          y = 351.25,
          width = 1115.25,
          height = 228,
          rotation = 0,
          gid = 6,
          visible = true,
          properties = {}
        },
        {
          id = 1085,
          name = "",
          type = "G",
          shape = "rectangle",
          x = 1302.75,
          y = 865.75,
          width = 972.25,
          height = 290.75,
          rotation = 0,
          gid = 6,
          visible = true,
          properties = {}
        },
        {
          id = 1089,
          name = "",
          type = "F",
          shape = "rectangle",
          x = 1150,
          y = 800,
          width = 150,
          height = 75,
          rotation = 0,
          gid = 5,
          visible = true,
          properties = {}
        },
        {
          id = 1090,
          name = "",
          type = "C",
          shape = "rectangle",
          x = 1212.5,
          y = 468.75,
          width = 25,
          height = 25,
          rotation = 0,
          gid = 1,
          visible = true,
          properties = {}
        },
        {
          id = 1091,
          name = "",
          type = "L",
          shape = "rectangle",
          x = 1575,
          y = 575,
          width = 25,
          height = 225,
          rotation = 0,
          gid = 7,
          visible = true,
          properties = {}
        },
        {
          id = 1092,
          name = "",
          type = "D",
          shape = "rectangle",
          x = 1825,
          y = 575,
          width = 25,
          height = 225,
          rotation = 0,
          gid = 12,
          visible = true,
          properties = {}
        },
        {
          id = 1095,
          name = "",
          type = "G",
          shape = "rectangle",
          x = 2246.5,
          y = 865.75,
          width = 306.25,
          height = 390.75,
          rotation = 0,
          gid = 6,
          visible = true,
          properties = {}
        },
        {
          id = 1096,
          name = "",
          type = "G",
          shape = "rectangle",
          x = 1943.75,
          y = 276.25,
          width = 1752.75,
          height = 153,
          rotation = 0,
          gid = 6,
          visible = true,
          properties = {}
        },
        {
          id = 1098,
          name = "",
          type = "L",
          shape = "rectangle",
          x = 2250,
          y = 475,
          width = 25,
          height = 200,
          rotation = 0,
          gid = 7,
          visible = true,
          properties = {}
        },
        {
          id = 1099,
          name = "",
          type = "C",
          shape = "rectangle",
          x = 2206.25,
          y = 462.5,
          width = 25,
          height = 25,
          rotation = 0,
          gid = 1,
          visible = true,
          properties = {}
        },
        {
          id = 1100,
          name = "",
          type = "G",
          shape = "rectangle",
          x = 2925,
          y = 865.75,
          width = 777.75,
          height = 390.75,
          rotation = 0,
          gid = 6,
          visible = true,
          properties = {}
        },
        {
          id = 1101,
          name = "",
          type = "L",
          shape = "rectangle",
          x = 2550,
          y = 500,
          width = 375,
          height = 25,
          rotation = 0,
          gid = 7,
          visible = true,
          properties = {}
        },
        {
          id = 1102,
          name = "",
          type = "F",
          shape = "rectangle",
          x = 2550,
          y = 700,
          width = 377.75,
          height = 75,
          rotation = 0,
          gid = 5,
          visible = true,
          properties = {}
        },
        {
          id = 1105,
          name = "",
          type = "G",
          shape = "rectangle",
          x = 3193.75,
          y = 475,
          width = 84,
          height = 50,
          rotation = 0,
          gid = 6,
          visible = true,
          properties = {}
        },
        {
          id = 1108,
          name = "",
          type = "L",
          shape = "rectangle",
          x = 3193.75,
          y = 425,
          width = 84,
          height = 150,
          rotation = 0,
          gid = 7,
          visible = true,
          properties = {}
        },
        {
          id = 1109,
          name = "",
          type = "C",
          shape = "rectangle",
          x = 2737.5,
          y = 462.5,
          width = 25,
          height = 25,
          rotation = 0,
          gid = 1,
          visible = true,
          properties = {}
        },
        {
          id = 1111,
          name = "",
          type = "L",
          shape = "rectangle",
          x = 4218.75,
          y = 525,
          width = 75,
          height = 25,
          rotation = 0,
          gid = 6,
          visible = true,
          properties = {}
        },
        {
          id = 1112,
          name = "",
          type = "D",
          shape = "rectangle",
          x = 3993.75,
          y = 493.75,
          width = 75,
          height = 25,
          rotation = 0,
          gid = 6,
          visible = true,
          properties = {}
        },
        {
          id = 1115,
          name = "",
          type = "L",
          shape = "rectangle",
          x = 3793.75,
          y = 525,
          width = 75,
          height = 25,
          rotation = 0,
          gid = 6,
          visible = true,
          properties = {}
        },
        {
          id = 1116,
          name = "",
          type = "S",
          shape = "rectangle",
          x = 3925,
          y = 625,
          width = 25,
          height = 25,
          rotation = 0,
          gid = 13,
          visible = true,
          properties = {}
        },
        {
          id = 1117,
          name = "",
          type = "S",
          shape = "rectangle",
          x = 4350,
          y = 625,
          width = 25,
          height = 25,
          rotation = 0,
          gid = 13,
          visible = true,
          properties = {}
        },
        {
          id = 1118,
          name = "",
          type = "S",
          shape = "rectangle",
          x = 3875,
          y = 625,
          width = 25,
          height = 25,
          rotation = 0,
          gid = 13,
          visible = true,
          properties = {}
        },
        {
          id = 1119,
          name = "",
          type = "S",
          shape = "rectangle",
          x = 4000,
          y = 625,
          width = 25,
          height = 25,
          rotation = 0,
          gid = 13,
          visible = true,
          properties = {}
        },
        {
          id = 1120,
          name = "",
          type = "S",
          shape = "rectangle",
          x = 3750,
          y = 625,
          width = 25,
          height = 25,
          rotation = 0,
          gid = 13,
          visible = true,
          properties = {}
        },
        {
          id = 1121,
          name = "",
          type = "S",
          shape = "rectangle",
          x = 4150,
          y = 625,
          width = 25,
          height = 25,
          rotation = 0,
          gid = 13,
          visible = true,
          properties = {}
        },
        {
          id = 1122,
          name = "",
          type = "S",
          shape = "rectangle",
          x = 3900,
          y = 625,
          width = 25,
          height = 25,
          rotation = 0,
          gid = 13,
          visible = true,
          properties = {}
        },
        {
          id = 1123,
          name = "",
          type = "S",
          shape = "rectangle",
          x = 4375,
          y = 625,
          width = 25,
          height = 25,
          rotation = 0,
          gid = 13,
          visible = true,
          properties = {}
        },
        {
          id = 1124,
          name = "",
          type = "S",
          shape = "rectangle",
          x = 3725,
          y = 625,
          width = 25,
          height = 25,
          rotation = 0,
          gid = 13,
          visible = true,
          properties = {}
        },
        {
          id = 1125,
          name = "",
          type = "S",
          shape = "rectangle",
          x = 4200,
          y = 625,
          width = 25,
          height = 25,
          rotation = 0,
          gid = 13,
          visible = true,
          properties = {}
        },
        {
          id = 1126,
          name = "",
          type = "S",
          shape = "rectangle",
          x = 4250,
          y = 625,
          width = 25,
          height = 25,
          rotation = 0,
          gid = 13,
          visible = true,
          properties = {}
        },
        {
          id = 1127,
          name = "",
          type = "S",
          shape = "rectangle",
          x = 3700,
          y = 625,
          width = 25,
          height = 25,
          rotation = 0,
          gid = 13,
          visible = true,
          properties = {}
        },
        {
          id = 1128,
          name = "",
          type = "S",
          shape = "rectangle",
          x = 4125,
          y = 625,
          width = 25,
          height = 25,
          rotation = 0,
          gid = 13,
          visible = true,
          properties = {}
        },
        {
          id = 1129,
          name = "",
          type = "S",
          shape = "rectangle",
          x = 4300,
          y = 625,
          width = 25,
          height = 25,
          rotation = 0,
          gid = 13,
          visible = true,
          properties = {}
        },
        {
          id = 1130,
          name = "",
          type = "S",
          shape = "rectangle",
          x = 4025,
          y = 625,
          width = 25,
          height = 25,
          rotation = 0,
          gid = 13,
          visible = true,
          properties = {}
        },
        {
          id = 1131,
          name = "",
          type = "S",
          shape = "rectangle",
          x = 3975,
          y = 625,
          width = 25,
          height = 25,
          rotation = 0,
          gid = 13,
          visible = true,
          properties = {}
        },
        {
          id = 1132,
          name = "",
          type = "S",
          shape = "rectangle",
          x = 3800,
          y = 625,
          width = 25,
          height = 25,
          rotation = 0,
          gid = 13,
          visible = true,
          properties = {}
        },
        {
          id = 1133,
          name = "",
          type = "S",
          shape = "rectangle",
          x = 4100,
          y = 625,
          width = 25,
          height = 25,
          rotation = 0,
          gid = 13,
          visible = true,
          properties = {}
        },
        {
          id = 1134,
          name = "",
          type = "S",
          shape = "rectangle",
          x = 4050,
          y = 625,
          width = 25,
          height = 25,
          rotation = 0,
          gid = 13,
          visible = true,
          properties = {}
        },
        {
          id = 1135,
          name = "",
          type = "S",
          shape = "rectangle",
          x = 4275,
          y = 625,
          width = 25,
          height = 25,
          rotation = 0,
          gid = 13,
          visible = true,
          properties = {}
        },
        {
          id = 1136,
          name = "",
          type = "S",
          shape = "rectangle",
          x = 3950,
          y = 625,
          width = 25,
          height = 25,
          rotation = 0,
          gid = 13,
          visible = true,
          properties = {}
        },
        {
          id = 1137,
          name = "",
          type = "S",
          shape = "rectangle",
          x = 4175,
          y = 625,
          width = 25,
          height = 25,
          rotation = 0,
          gid = 13,
          visible = true,
          properties = {}
        },
        {
          id = 1138,
          name = "",
          type = "S",
          shape = "rectangle",
          x = 4325,
          y = 625,
          width = 25,
          height = 25,
          rotation = 0,
          gid = 13,
          visible = true,
          properties = {}
        },
        {
          id = 1139,
          name = "",
          type = "S",
          shape = "rectangle",
          x = 4075,
          y = 625,
          width = 25,
          height = 25,
          rotation = 0,
          gid = 13,
          visible = true,
          properties = {}
        },
        {
          id = 1141,
          name = "",
          type = "S",
          shape = "rectangle",
          x = 4225,
          y = 625,
          width = 25,
          height = 25,
          rotation = 0,
          gid = 13,
          visible = true,
          properties = {}
        },
        {
          id = 1142,
          name = "",
          type = "S",
          shape = "rectangle",
          x = 3850,
          y = 625,
          width = 25,
          height = 25,
          rotation = 0,
          gid = 13,
          visible = true,
          properties = {}
        },
        {
          id = 1143,
          name = "",
          type = "S",
          shape = "rectangle",
          x = 3775,
          y = 625,
          width = 25,
          height = 25,
          rotation = 0,
          gid = 13,
          visible = true,
          properties = {}
        },
        {
          id = 1144,
          name = "",
          type = "S",
          shape = "rectangle",
          x = 3825,
          y = 625,
          width = 25,
          height = 25,
          rotation = 0,
          gid = 13,
          visible = true,
          properties = {}
        },
        {
          id = 1145,
          name = "",
          type = "G",
          shape = "rectangle",
          x = 4400,
          y = 790.75,
          width = 596.5,
          height = 359.5,
          rotation = 0,
          gid = 6,
          visible = true,
          properties = {}
        },
        {
          id = 1147,
          name = "",
          type = "C",
          shape = "rectangle",
          x = 3918.75,
          y = 437.5,
          width = 25,
          height = 25,
          rotation = 0,
          gid = 1,
          visible = true,
          properties = {}
        },
        {
          id = 1148,
          name = "",
          type = "C",
          shape = "rectangle",
          x = 4162.5,
          y = 443.75,
          width = 25,
          height = 25,
          rotation = 0,
          gid = 1,
          visible = true,
          properties = {}
        }
      }
    }
  }
}
