return {
  version = "1.1",
  luaversion = "5.1",
  tiledversion = "0.17.1",
  orientation = "orthogonal",
  renderorder = "right-down",
  width = 500,
  height = 50,
  tilewidth = 25,
  tileheight = 25,
  nextobjectid = 1283,
  properties = {},
  tilesets = {
    {
      name = "tiles",
      firstgid = 1,
      tilewidth = 25,
      tileheight = 25,
      spacing = 0,
      margin = 0,
      tileoffset = {
        x = 0,
        y = 0
      },
      properties = {},
      terrains = {},
      tilecount = 14,
      tiles = {
        {
          id = 0,
          image = "G:/Feevale/Mapas projeto/tiles/coinTile.png",
          width = 25,
          height = 25
        },
        {
          id = 1,
          image = "G:/Feevale/Mapas projeto/tiles/darkTile.png",
          width = 25,
          height = 25
        },
        {
          id = 2,
          image = "G:/Feevale/Mapas projeto/tiles/endGameTile.png",
          width = 25,
          height = 25
        },
        {
          id = 3,
          image = "G:/Feevale/Mapas projeto/tiles/endGameTile.png",
          width = 25,
          height = 25
        },
        {
          id = 4,
          image = "G:/Feevale/Mapas projeto/tiles/fatalTile.png",
          width = 25,
          height = 25
        },
        {
          id = 5,
          image = "G:/Feevale/Mapas projeto/tiles/groundTile.png",
          width = 25,
          height = 25
        },
        {
          id = 6,
          image = "G:/Feevale/Mapas projeto/tiles/lightTile.png",
          width = 25,
          height = 25
        },
        {
          id = 7,
          image = "G:/Feevale/Mapas projeto/tiles/portal1Tile.png",
          width = 25,
          height = 25
        },
        {
          id = 8,
          image = "G:/Feevale/Mapas projeto/tiles/portal2Tile.png",
          width = 25,
          height = 25
        },
        {
          id = 9,
          image = "G:/Feevale/Mapas projeto/tiles/portal3Tile.png",
          width = 25,
          height = 25
        },
        {
          id = 10,
          image = "G:/Feevale/Mapas projeto/tiles/portal4Tile.png",
          width = 25,
          height = 25
        },
        {
          id = 11,
          image = "G:/Feevale/Mapas projeto/tiles/powerUpTile.png",
          width = 25,
          height = 25
        },
        {
          id = 12,
          image = "G:/Feevale/Mapas projeto/tiles/spikeTile.png",
          width = 25,
          height = 25
        },
        {
          id = 13,
          image = "G:/Feevale/Mapas projeto/tiles/startZeroGravityTile.png",
          width = 25,
          height = 25
        }
      }
    }
  },
  layers = {
    {
      type = "objectgroup",
      name = "Object Layer 1",
      visible = true,
      opacity = 1,
      offsetx = 166,
      offsety = 128,
      draworder = "topdown",
      properties = {},
      objects = {
        {
          id = 283,
          name = "",
          type = "G",
          shape = "rectangle",
          x = 61.6515,
          y = 600.917,
          width = 187.152,
          height = 25,
          rotation = 0,
          gid = 6,
          visible = true,
          properties = {}
        },
        {
          id = 994,
          name = "",
          type = "EG",
          shape = "rectangle",
          x = 5731.09,
          y = 503.682,
          width = 25,
          height = 352.583,
          rotation = 0,
          gid = 3,
          visible = true,
          properties = {}
        },
        {
          id = 1098,
          name = "",
          type = "L",
          shape = "rectangle",
          x = 1301.97,
          y = 749.159,
          width = 77.75,
          height = 25,
          rotation = 0,
          gid = 7,
          visible = true,
          properties = {}
        },
        {
          id = 1110,
          name = "",
          type = "F",
          shape = "rectangle",
          x = -409.75,
          y = 952.765,
          width = 3793.75,
          height = 50,
          rotation = 0,
          gid = 5,
          visible = true,
          properties = {}
        },
        {
          id = 1139,
          name = "",
          type = "S",
          shape = "rectangle",
          x = 3844.67,
          y = 477.917,
          width = 25,
          height = 25,
          rotation = 0,
          gid = 5,
          visible = true,
          properties = {}
        },
        {
          id = 1140,
          name = "",
          type = "S",
          shape = "rectangle",
          x = 3782.17,
          y = 477.917,
          width = 25,
          height = 25,
          rotation = 0,
          gid = 5,
          visible = true,
          properties = {}
        },
        {
          id = 1141,
          name = "",
          type = "S",
          shape = "rectangle",
          x = 3750.92,
          y = 477.917,
          width = 25,
          height = 25,
          rotation = 0,
          gid = 5,
          visible = true,
          properties = {}
        },
        {
          id = 1142,
          name = "",
          type = "S",
          shape = "rectangle",
          x = 3813.42,
          y = 477.917,
          width = 25,
          height = 25,
          rotation = 0,
          gid = 5,
          visible = true,
          properties = {}
        },
        {
          id = 1145,
          name = "",
          type = "SZG",
          shape = "rectangle",
          x = 4158.77,
          y = 501.78,
          width = 25,
          height = 289.583,
          rotation = 0,
          gid = 8,
          visible = true,
          properties = {}
        },
        {
          id = 1158,
          name = "",
          type = "D",
          shape = "rectangle",
          x = 352.22,
          y = 610.159,
          width = 75,
          height = 25,
          rotation = 0,
          gid = 12,
          visible = true,
          properties = {}
        },
        {
          id = 1159,
          name = "",
          type = "L",
          shape = "rectangle",
          x = 503.97,
          y = 662.159,
          width = 77.75,
          height = 25,
          rotation = 0,
          gid = 7,
          visible = true,
          properties = {}
        },
        {
          id = 1160,
          name = "",
          type = "D",
          shape = "rectangle",
          x = 653.22,
          y = 616.159,
          width = 75,
          height = 25,
          rotation = 0,
          gid = 12,
          visible = true,
          properties = {}
        },
        {
          id = 1163,
          name = "",
          type = "G",
          shape = "rectangle",
          x = 1124.65,
          y = 690.917,
          width = 104.152,
          height = 25,
          rotation = 0,
          gid = 6,
          visible = true,
          properties = {}
        },
        {
          id = 1164,
          name = "",
          type = "D",
          shape = "rectangle",
          x = 969.22,
          y = 684.159,
          width = 75,
          height = 25,
          rotation = 0,
          gid = 12,
          visible = true,
          properties = {}
        },
        {
          id = 1165,
          name = "",
          type = "L",
          shape = "rectangle",
          x = 806.97,
          y = 654.159,
          width = 77.75,
          height = 25,
          rotation = 0,
          gid = 7,
          visible = true,
          properties = {}
        },
        {
          id = 1166,
          name = "",
          type = "L",
          shape = "rectangle",
          x = 1280.97,
          y = 610.159,
          width = 77.75,
          height = 25,
          rotation = 0,
          gid = 7,
          visible = true,
          properties = {}
        },
        {
          id = 1167,
          name = "",
          type = "D",
          shape = "rectangle",
          x = 1420.22,
          y = 548.159,
          width = 75,
          height = 25,
          rotation = 0,
          gid = 12,
          visible = true,
          properties = {}
        },
        {
          id = 1168,
          name = "",
          type = "G",
          shape = "rectangle",
          x = 2750.65,
          y = 303.462,
          width = 1399.49,
          height = 173.667,
          rotation = 0,
          gid = 6,
          visible = true,
          properties = {}
        },
        {
          id = 1169,
          name = "",
          type = "G",
          shape = "rectangle",
          x = 1579.65,
          y = 495.917,
          width = 75,
          height = 25,
          rotation = 0,
          gid = 6,
          visible = true,
          properties = {}
        },
        {
          id = 1170,
          name = "",
          type = "G",
          shape = "rectangle",
          x = 1665.48,
          y = 574.917,
          width = 285.819,
          height = 25,
          rotation = 0,
          gid = 6,
          visible = true,
          properties = {}
        },
        {
          id = 1171,
          name = "",
          type = "G",
          shape = "rectangle",
          x = 1950.71,
          y = 575.709,
          width = 25,
          height = 105.333,
          rotation = 0,
          gid = 6,
          visible = true,
          properties = {}
        },
        {
          id = 1172,
          name = "",
          type = "G",
          shape = "rectangle",
          x = 1640.71,
          y = 575.375,
          width = 25,
          height = 104.333,
          rotation = 0,
          gid = 6,
          visible = true,
          properties = {}
        },
        {
          id = 1173,
          name = "",
          type = "G",
          shape = "rectangle",
          x = 1775.65,
          y = 499.25,
          width = 99.4853,
          height = 25,
          rotation = 0,
          gid = 6,
          visible = true,
          properties = {}
        },
        {
          id = 1174,
          name = "",
          type = "P2",
          shape = "rectangle",
          x = 1775.83,
          y = 474.333,
          width = 50,
          height = 75,
          rotation = 0,
          gid = 10,
          visible = true,
          properties = {}
        },
        {
          id = 1175,
          name = "",
          type = "L",
          shape = "rectangle",
          x = 1625.64,
          y = 808.826,
          width = 77.75,
          height = 25,
          rotation = 0,
          gid = 7,
          visible = true,
          properties = {}
        },
        {
          id = 1176,
          name = "",
          type = "D",
          shape = "rectangle",
          x = 1787.89,
          y = 788.826,
          width = 75,
          height = 25,
          rotation = 0,
          gid = 12,
          visible = true,
          properties = {}
        },
        {
          id = 1177,
          name = "",
          type = "D",
          shape = "rectangle",
          x = 1471.89,
          y = 770.826,
          width = 75,
          height = 25,
          rotation = 0,
          gid = 12,
          visible = true,
          properties = {}
        },
        {
          id = 1178,
          name = "",
          type = "D",
          shape = "rectangle",
          x = 2437.56,
          y = 645.493,
          width = 75,
          height = 25,
          rotation = 0,
          gid = 12,
          visible = true,
          properties = {}
        },
        {
          id = 1179,
          name = "",
          type = "L",
          shape = "rectangle",
          x = 2276.64,
          y = 686.826,
          width = 77.75,
          height = 25,
          rotation = 0,
          gid = 7,
          visible = true,
          properties = {}
        },
        {
          id = 1180,
          name = "",
          type = "D",
          shape = "rectangle",
          x = 2254.22,
          y = 539.159,
          width = 75,
          height = 25,
          rotation = 0,
          gid = 12,
          visible = true,
          properties = {}
        },
        {
          id = 1181,
          name = "",
          type = "L",
          shape = "rectangle",
          x = 2101.64,
          y = 505.826,
          width = 77.75,
          height = 25,
          rotation = 0,
          gid = 7,
          visible = true,
          properties = {}
        },
        {
          id = 1186,
          name = "",
          type = "D",
          shape = "rectangle",
          x = 2114.79,
          y = 722.833,
          width = 75,
          height = 25,
          rotation = 0,
          gid = 12,
          visible = true,
          properties = {}
        },
        {
          id = 1187,
          name = "",
          type = "L",
          shape = "rectangle",
          x = 1952.88,
          y = 760.167,
          width = 77.75,
          height = 25,
          rotation = 0,
          gid = 7,
          visible = true,
          properties = {}
        },
        {
          id = 1188,
          name = "",
          type = "G",
          shape = "rectangle",
          x = 1975.32,
          y = 495.462,
          width = 83.4853,
          height = 25,
          rotation = 0,
          gid = 6,
          visible = true,
          properties = {}
        },
        {
          id = 1189,
          name = "",
          type = "G",
          shape = "rectangle",
          x = 2566.32,
          y = 675.462,
          width = 183.819,
          height = 25,
          rotation = 0,
          gid = 6,
          visible = true,
          properties = {}
        },
        {
          id = 1190,
          name = "",
          type = "PU2",
          shape = "rectangle",
          x = 2650,
          y = 638,
          width = 25,
          height = 25,
          rotation = 0,
          gid = 12,
          visible = true,
          properties = {}
        },
        {
          id = 1191,
          name = "",
          type = "G",
          shape = "rectangle",
          x = 2724.65,
          y = 675.462,
          width = 3609.35,
          height = 173.667,
          rotation = 0,
          gid = 6,
          visible = true,
          properties = {}
        },
        {
          id = 1192,
          name = "",
          type = "G",
          shape = "rectangle",
          x = 3200.32,
          y = 502.462,
          width = 125,
          height = 50,
          rotation = 0,
          gid = 6,
          visible = true,
          properties = {}
        },
        {
          id = 1193,
          name = "",
          type = "G",
          shape = "rectangle",
          x = 3200.32,
          y = 377.462,
          width = 125,
          height = 74.5,
          rotation = 0,
          gid = 6,
          visible = true,
          properties = {}
        },
        {
          id = 1194,
          name = "",
          type = "PU1",
          shape = "rectangle",
          x = 3017.5,
          y = 488.5,
          width = 25,
          height = 25,
          rotation = 0,
          gid = 12,
          visible = true,
          properties = {}
        },
        {
          id = 1195,
          name = "",
          type = "G",
          shape = "rectangle",
          x = 3750.32,
          y = 502.462,
          width = 129,
          height = 25,
          rotation = 0,
          gid = 6,
          visible = true,
          properties = {}
        },
        {
          id = 1196,
          name = "",
          type = "G",
          shape = "rectangle",
          x = 3750.32,
          y = 377.462,
          width = 127.5,
          height = 74.5,
          rotation = 0,
          gid = 6,
          visible = true,
          properties = {}
        },
        {
          id = 1197,
          name = "",
          type = "PU1",
          shape = "rectangle",
          x = 3500.5,
          y = 481,
          width = 25,
          height = 25,
          rotation = 0,
          gid = 12,
          visible = true,
          properties = {}
        },
        {
          id = 1198,
          name = "",
          type = "G",
          shape = "rectangle",
          x = 4149.59,
          y = 151.166,
          width = 2178.16,
          height = 173.667,
          rotation = 0,
          gid = 6,
          visible = true,
          properties = {}
        },
        {
          id = 1199,
          name = "",
          type = "G",
          shape = "rectangle",
          x = 4586.15,
          y = 302.129,
          width = 25,
          height = 151.833,
          rotation = 0,
          gid = 6,
          visible = true,
          properties = {}
        },
        {
          id = 1200,
          name = "",
          type = "G",
          shape = "rectangle",
          x = 4633.48,
          y = 284.796,
          width = 25,
          height = 151.833,
          rotation = 0,
          gid = 6,
          visible = true,
          properties = {}
        },
        {
          id = 1201,
          name = "",
          type = "G",
          shape = "rectangle",
          x = 4610.15,
          y = 295.462,
          width = 25,
          height = 151.833,
          rotation = 0,
          gid = 6,
          visible = true,
          properties = {}
        },
        {
          id = 1202,
          name = "",
          type = "G",
          shape = "rectangle",
          x = 4657.48,
          y = 274.796,
          width = 25,
          height = 151.833,
          rotation = 0,
          gid = 6,
          visible = true,
          properties = {}
        },
        {
          id = 1203,
          name = "",
          type = "G",
          shape = "rectangle",
          x = 4682.15,
          y = 267.463,
          width = 25,
          height = 151.833,
          rotation = 0,
          gid = 6,
          visible = true,
          properties = {}
        },
        {
          id = 1204,
          name = "",
          type = "G",
          shape = "rectangle",
          x = 4728.82,
          y = 244.13,
          width = 25,
          height = 151.833,
          rotation = 0,
          gid = 6,
          visible = true,
          properties = {}
        },
        {
          id = 1205,
          name = "",
          type = "G",
          shape = "rectangle",
          x = 4705.48,
          y = 255.463,
          width = 25,
          height = 151.833,
          rotation = 0,
          gid = 6,
          visible = true,
          properties = {}
        },
        {
          id = 1206,
          name = "",
          type = "G",
          shape = "rectangle",
          x = 4776.82,
          y = 224.13,
          width = 25,
          height = 151.833,
          rotation = 0,
          gid = 6,
          visible = true,
          properties = {}
        },
        {
          id = 1207,
          name = "",
          type = "G",
          shape = "rectangle",
          x = 4752.82,
          y = 231.463,
          width = 25,
          height = 151.833,
          rotation = 0,
          gid = 6,
          visible = true,
          properties = {}
        },
        {
          id = 1208,
          name = "",
          type = "G",
          shape = "rectangle",
          x = 4800.15,
          y = 218.797,
          width = 241.667,
          height = 151.833,
          rotation = 0,
          gid = 6,
          visible = true,
          properties = {}
        },
        {
          id = 1209,
          name = "",
          type = "G",
          shape = "rectangle",
          x = 4586.15,
          y = 610.129,
          width = 25,
          height = 163.833,
          rotation = 0,
          gid = 6,
          visible = true,
          properties = {}
        },
        {
          id = 1210,
          name = "",
          type = "G",
          shape = "rectangle",
          x = 4611.15,
          y = 601.129,
          width = 25,
          height = 163.833,
          rotation = 0,
          gid = 6,
          visible = true,
          properties = {}
        },
        {
          id = 1211,
          name = "",
          type = "G",
          shape = "rectangle",
          x = 4636.15,
          y = 594.129,
          width = 25,
          height = 163.833,
          rotation = 0,
          gid = 6,
          visible = true,
          properties = {}
        },
        {
          id = 1212,
          name = "",
          type = "G",
          shape = "rectangle",
          x = 4661.15,
          y = 586.129,
          width = 25,
          height = 163.833,
          rotation = 0,
          gid = 6,
          visible = true,
          properties = {}
        },
        {
          id = 1213,
          name = "",
          type = "G",
          shape = "rectangle",
          x = 4686.15,
          y = 579.129,
          width = 25,
          height = 163.833,
          rotation = 0,
          gid = 6,
          visible = true,
          properties = {}
        },
        {
          id = 1214,
          name = "",
          type = "G",
          shape = "rectangle",
          x = 4711.15,
          y = 572.129,
          width = 25,
          height = 163.833,
          rotation = 0,
          gid = 6,
          visible = true,
          properties = {}
        },
        {
          id = 1215,
          name = "",
          type = "G",
          shape = "rectangle",
          x = 4736.15,
          y = 563.129,
          width = 25,
          height = 163.833,
          rotation = 0,
          gid = 6,
          visible = true,
          properties = {}
        },
        {
          id = 1216,
          name = "",
          type = "G",
          shape = "rectangle",
          x = 4761.15,
          y = 553.129,
          width = 25,
          height = 163.833,
          rotation = 0,
          gid = 6,
          visible = true,
          properties = {}
        },
        {
          id = 1217,
          name = "",
          type = "G",
          shape = "rectangle",
          x = 4786.15,
          y = 542.129,
          width = 25,
          height = 163.833,
          rotation = 0,
          gid = 6,
          visible = true,
          properties = {}
        },
        {
          id = 1218,
          name = "",
          type = "G",
          shape = "rectangle",
          x = 4811.15,
          y = 532.129,
          width = 25,
          height = 163.833,
          rotation = 0,
          gid = 6,
          visible = true,
          properties = {}
        },
        {
          id = 1219,
          name = "",
          type = "G",
          shape = "rectangle",
          x = 4836.15,
          y = 525.129,
          width = 206,
          height = 163.833,
          rotation = 0,
          gid = 6,
          visible = true,
          properties = {}
        },
        {
          id = 1220,
          name = "",
          type = "G",
          shape = "rectangle",
          x = 4536.15,
          y = 624.129,
          width = 25,
          height = 163.833,
          rotation = 0,
          gid = 6,
          visible = true,
          properties = {}
        },
        {
          id = 1221,
          name = "",
          type = "G",
          shape = "rectangle",
          x = 4511.15,
          y = 632.129,
          width = 25,
          height = 163.833,
          rotation = 0,
          gid = 6,
          visible = true,
          properties = {}
        },
        {
          id = 1222,
          name = "",
          type = "G",
          shape = "rectangle",
          x = 4561.15,
          y = 617.129,
          width = 25,
          height = 163.833,
          rotation = 0,
          gid = 6,
          visible = true,
          properties = {}
        },
        {
          id = 1223,
          name = "",
          type = "G",
          shape = "rectangle",
          x = 4486.15,
          y = 639.129,
          width = 25,
          height = 163.833,
          rotation = 0,
          gid = 6,
          visible = true,
          properties = {}
        },
        {
          id = 1224,
          name = "",
          type = "G",
          shape = "rectangle",
          x = 4461.15,
          y = 648.129,
          width = 25,
          height = 163.833,
          rotation = 0,
          gid = 6,
          visible = true,
          properties = {}
        },
        {
          id = 1225,
          name = "",
          type = "G",
          shape = "rectangle",
          x = 4508.48,
          y = 330.796,
          width = 25,
          height = 210.333,
          rotation = 0,
          gid = 6,
          visible = true,
          properties = {}
        },
        {
          id = 1226,
          name = "",
          type = "G",
          shape = "rectangle",
          x = 4651.82,
          y = 270.13,
          width = 25,
          height = 151.833,
          rotation = 0,
          gid = 6,
          visible = true,
          properties = {}
        },
        {
          id = 1227,
          name = "",
          type = "G",
          shape = "rectangle",
          x = 4461.15,
          y = 317.129,
          width = 25,
          height = 199.833,
          rotation = 0,
          gid = 6,
          visible = true,
          properties = {}
        },
        {
          id = 1228,
          name = "",
          type = "G",
          shape = "rectangle",
          x = 4532.48,
          y = 320.796,
          width = 25,
          height = 180.833,
          rotation = 0,
          gid = 6,
          visible = true,
          properties = {}
        },
        {
          id = 1229,
          name = "",
          type = "G",
          shape = "rectangle",
          x = 4580.48,
          y = 301.463,
          width = 25,
          height = 151.833,
          rotation = 0,
          gid = 6,
          visible = true,
          properties = {}
        },
        {
          id = 1230,
          name = "",
          type = "G",
          shape = "rectangle",
          x = 4627.82,
          y = 277.463,
          width = 25,
          height = 151.833,
          rotation = 0,
          gid = 6,
          visible = true,
          properties = {}
        },
        {
          id = 1231,
          name = "",
          type = "G",
          shape = "rectangle",
          x = 4485.15,
          y = 341.462,
          width = 25,
          height = 199.833,
          rotation = 0,
          gid = 6,
          visible = true,
          properties = {}
        },
        {
          id = 1232,
          name = "",
          type = "G",
          shape = "rectangle",
          x = 4603.82,
          y = 290.13,
          width = 25,
          height = 151.833,
          rotation = 0,
          gid = 6,
          visible = true,
          properties = {}
        },
        {
          id = 1233,
          name = "",
          type = "G",
          shape = "rectangle",
          x = 4557.15,
          y = 313.463,
          width = 25,
          height = 187.833,
          rotation = 0,
          gid = 6,
          visible = true,
          properties = {}
        },
        {
          id = 1234,
          name = "",
          type = "G",
          shape = "rectangle",
          x = 5178.82,
          y = 290.13,
          width = 25,
          height = 151.833,
          rotation = 0,
          gid = 6,
          visible = true,
          properties = {}
        },
        {
          id = 1235,
          name = "",
          type = "G",
          shape = "rectangle",
          x = 5132.15,
          y = 279.463,
          width = 25,
          height = 187.833,
          rotation = 0,
          gid = 6,
          visible = true,
          properties = {}
        },
        {
          id = 1236,
          name = "",
          type = "G",
          shape = "rectangle",
          x = 5226.82,
          y = 270.13,
          width = 25,
          height = 151.833,
          rotation = 0,
          gid = 6,
          visible = true,
          properties = {}
        },
        {
          id = 1238,
          name = "",
          type = "G",
          shape = "rectangle",
          x = 5208.48,
          y = 303.796,
          width = 25,
          height = 151.833,
          rotation = 0,
          gid = 6,
          visible = true,
          properties = {}
        },
        {
          id = 1239,
          name = "",
          type = "G",
          shape = "rectangle",
          x = 5185.15,
          y = 295.462,
          width = 25,
          height = 151.833,
          rotation = 0,
          gid = 6,
          visible = true,
          properties = {}
        },
        {
          id = 1241,
          name = "",
          type = "G",
          shape = "rectangle",
          x = 5036.15,
          y = 233.129,
          width = 25,
          height = 199.833,
          rotation = 0,
          gid = 6,
          visible = true,
          properties = {}
        },
        {
          id = 1242,
          name = "",
          type = "G",
          shape = "rectangle",
          x = 5232.48,
          y = 310.796,
          width = 25,
          height = 151.833,
          rotation = 0,
          gid = 6,
          visible = true,
          properties = {}
        },
        {
          id = 1243,
          name = "",
          type = "G",
          shape = "rectangle",
          x = 5083.48,
          y = 255.796,
          width = 25,
          height = 210.333,
          rotation = 0,
          gid = 6,
          visible = true,
          properties = {}
        },
        {
          id = 1244,
          name = "",
          type = "G",
          shape = "rectangle",
          x = 5202.82,
          y = 277.463,
          width = 25,
          height = 151.833,
          rotation = 0,
          gid = 6,
          visible = true,
          properties = {}
        },
        {
          id = 1247,
          name = "",
          type = "G",
          shape = "rectangle",
          x = 5107.48,
          y = 264.796,
          width = 25,
          height = 180.833,
          rotation = 0,
          gid = 6,
          visible = true,
          properties = {}
        },
        {
          id = 1248,
          name = "",
          type = "G",
          shape = "rectangle",
          x = 5155.48,
          y = 289.463,
          width = 25,
          height = 151.833,
          rotation = 0,
          gid = 6,
          visible = true,
          properties = {}
        },
        {
          id = 1250,
          name = "",
          type = "G",
          shape = "rectangle",
          x = 5060.15,
          y = 243.462,
          width = 25,
          height = 199.833,
          rotation = 0,
          gid = 6,
          visible = true,
          properties = {}
        },
        {
          id = 1254,
          name = "",
          type = "G",
          shape = "rectangle",
          x = 5083.48,
          y = 601.796,
          width = 25,
          height = 210.333,
          rotation = 0,
          gid = 6,
          visible = true,
          properties = {}
        },
        {
          id = 1255,
          name = "",
          type = "G",
          shape = "rectangle",
          x = 5133.48,
          y = 642.796,
          width = 25,
          height = 151.833,
          rotation = 0,
          gid = 6,
          visible = true,
          properties = {}
        },
        {
          id = 1256,
          name = "",
          type = "G",
          shape = "rectangle",
          x = 5226.82,
          y = 609.13,
          width = 25,
          height = 151.833,
          rotation = 0,
          gid = 6,
          visible = true,
          properties = {}
        },
        {
          id = 1257,
          name = "",
          type = "G",
          shape = "rectangle",
          x = 5107.48,
          y = 582.796,
          width = 25,
          height = 180.833,
          rotation = 0,
          gid = 6,
          visible = true,
          properties = {}
        },
        {
          id = 1258,
          name = "",
          type = "G",
          shape = "rectangle",
          x = 5060.15,
          y = 582.462,
          width = 25,
          height = 199.833,
          rotation = 0,
          gid = 6,
          visible = true,
          properties = {}
        },
        {
          id = 1260,
          name = "",
          type = "G",
          shape = "rectangle",
          x = 5132.15,
          y = 600.463,
          width = 25,
          height = 187.833,
          rotation = 0,
          gid = 6,
          visible = true,
          properties = {}
        },
        {
          id = 1262,
          name = "",
          type = "G",
          shape = "rectangle",
          x = 5202.82,
          y = 601.463,
          width = 25,
          height = 151.833,
          rotation = 0,
          gid = 6,
          visible = true,
          properties = {}
        },
        {
          id = 1263,
          name = "",
          type = "G",
          shape = "rectangle",
          x = 5155.48,
          y = 578.463,
          width = 25,
          height = 151.833,
          rotation = 0,
          gid = 6,
          visible = true,
          properties = {}
        },
        {
          id = 1264,
          name = "",
          type = "G",
          shape = "rectangle",
          x = 5178.82,
          y = 590.13,
          width = 25,
          height = 151.833,
          rotation = 0,
          gid = 6,
          visible = true,
          properties = {}
        },
        {
          id = 1265,
          name = "",
          type = "G",
          shape = "rectangle",
          x = 5036.15,
          y = 572.129,
          width = 25,
          height = 199.833,
          rotation = 0,
          gid = 6,
          visible = true,
          properties = {}
        },
        {
          id = 1267,
          name = "",
          type = "EZG",
          shape = "rectangle",
          x = 5251.56,
          y = 499.561,
          width = 25,
          height = 253,
          rotation = 0,
          gid = 4,
          visible = true,
          properties = {}
        },
        {
          id = 1268,
          name = "",
          type = "C",
          shape = "rectangle",
          x = 4908.68,
          y = 309.962,
          width = 25,
          height = 25,
          rotation = 0,
          gid = 1,
          visible = true,
          properties = {}
        },
        {
          id = 1269,
          name = "",
          type = "C",
          shape = "rectangle",
          x = 529.182,
          y = 609.962,
          width = 25,
          height = 25,
          rotation = 0,
          gid = 1,
          visible = true,
          properties = {}
        },
        {
          id = 1270,
          name = "",
          type = "C",
          shape = "rectangle",
          x = 930.182,
          y = 603.962,
          width = 25,
          height = 25,
          rotation = 0,
          gid = 1,
          visible = true,
          properties = {}
        },
        {
          id = 1271,
          name = "",
          type = "C",
          shape = "rectangle",
          x = 1367.18,
          y = 501.962,
          width = 25,
          height = 25,
          rotation = 0,
          gid = 1,
          visible = true,
          properties = {}
        },
        {
          id = 1272,
          name = "",
          type = "C",
          shape = "rectangle",
          x = 1436.18,
          y = 700.962,
          width = 25,
          height = 25,
          rotation = 0,
          gid = 1,
          visible = true,
          properties = {}
        },
        {
          id = 1273,
          name = "",
          type = "C",
          shape = "rectangle",
          x = 1836.18,
          y = 463.962,
          width = 25,
          height = 25,
          rotation = 0,
          gid = 1,
          visible = true,
          properties = {}
        },
        {
          id = 1274,
          name = "",
          type = "C",
          shape = "rectangle",
          x = 1904.18,
          y = 706.962,
          width = 25,
          height = 25,
          rotation = 0,
          gid = 1,
          visible = true,
          properties = {}
        },
        {
          id = 1275,
          name = "",
          type = "C",
          shape = "rectangle",
          x = 2423.18,
          y = 588.962,
          width = 25,
          height = 25,
          rotation = 0,
          gid = 1,
          visible = true,
          properties = {}
        },
        {
          id = 1276,
          name = "",
          type = "C",
          shape = "rectangle",
          x = 3249.18,
          y = 430.962,
          width = 25,
          height = 25,
          rotation = 0,
          gid = 1,
          visible = true,
          properties = {}
        },
        {
          id = 1277,
          name = "",
          type = "C",
          shape = "rectangle",
          x = 3803.18,
          y = 426.962,
          width = 25,
          height = 25,
          rotation = 0,
          gid = 1,
          visible = true,
          properties = {}
        },
        {
          id = 1278,
          name = "",
          type = "PU3",
          shape = "rectangle",
          x = 1882.68,
          y = 541.727,
          width = 25,
          height = 25,
          rotation = 0,
          gid = 12,
          visible = true,
          properties = {}
        },
        {
          id = 1279,
          name = "",
          type = "G",
          shape = "rectangle",
          x = 4435.9,
          y = 293.879,
          width = 25,
          height = 199.833,
          rotation = 0,
          gid = 6,
          visible = true,
          properties = {}
        },
        {
          id = 1280,
          name = "",
          type = "G",
          shape = "rectangle",
          x = 4411.9,
          y = 275.129,
          width = 25,
          height = 199.833,
          rotation = 0,
          gid = 6,
          visible = true,
          properties = {}
        },
        {
          id = 1281,
          name = "",
          type = "G",
          shape = "rectangle",
          x = 4393.15,
          y = 256.379,
          width = 25,
          height = 199.833,
          rotation = 0,
          gid = 6,
          visible = true,
          properties = {}
        },
        {
          id = 1282,
          name = "",
          type = "G",
          shape = "rectangle",
          x = 4368.15,
          y = 237.629,
          width = 25,
          height = 199.833,
          rotation = 0,
          gid = 6,
          visible = true,
          properties = {}
        }
      }
    }
  }
}
