return {
  version = "1.1",
  luaversion = "5.1",
  tiledversion = "0.17.1",
  orientation = "orthogonal",
  renderorder = "right-down",
  width = 500,
  height = 50,
  tilewidth = 25,
  tileheight = 25,
  nextobjectid = 1291,
  properties = {},
  tilesets = {
    {
      name = "tiles",
      firstgid = 1,
      tilewidth = 25,
      tileheight = 25,
      spacing = 0,
      margin = 0,
      tileoffset = {
        x = 0,
        y = 0
      },
      properties = {},
      terrains = {},
      tilecount = 14,
      tiles = {
        {
          id = 0,
          image = "tiledFiles/tiles/coinTile.png",
          width = 25,
          height = 25
        },
        {
          id = 1,
          image = "tiledFiles/tiles/darkTile.png",
          width = 25,
          height = 25
        },
        {
          id = 2,
          image = "tiledFiles/tiles/endGameTile.png",
          width = 25,
          height = 25
        },
        {
          id = 3,
          image = "tiledFiles/tiles/endGameTile.png",
          width = 25,
          height = 25
        },
        {
          id = 4,
          image = "tiledFiles/tiles/fatalTile.png",
          width = 25,
          height = 25
        },
        {
          id = 5,
          image = "tiledFiles/tiles/groundTile.png",
          width = 25,
          height = 25
        },
        {
          id = 6,
          image = "tiledFiles/tiles/lightTile.png",
          width = 25,
          height = 25
        },
        {
          id = 7,
          image = "tiledFiles/tiles/portal1Tile.png",
          width = 25,
          height = 25
        },
        {
          id = 8,
          image = "tiledFiles/tiles/portal2Tile.png",
          width = 25,
          height = 25
        },
        {
          id = 9,
          image = "tiledFiles/tiles/portal3Tile.png",
          width = 25,
          height = 25
        },
        {
          id = 10,
          image = "tiledFiles/tiles/portal4Tile.png",
          width = 25,
          height = 25
        },
        {
          id = 11,
          image = "tiledFiles/tiles/powerUpTile.png",
          width = 25,
          height = 25
        },
        {
          id = 12,
          image = "tiledFiles/tiles/spikeTile.png",
          width = 25,
          height = 25
        },
        {
          id = 13,
          image = "tiledFiles/tiles/startZeroGravityTile.png",
          width = 25,
          height = 25
        }
      }
    }
  },
  layers = {
    {
      type = "objectgroup",
      name = "Object Layer 1",
      visible = true,
      opacity = 1,
      offsetx = 166,
      offsety = 128,
      draworder = "topdown",
      properties = {},
      objects = {
        {
          id = 283,
          name = "",
          type = "G",
          shape = "rectangle",
          x = -68.75,
          y = 600,
          width = 664.803,
          height = 25,
          rotation = 0,
          gid = 6,
          visible = true,
          properties = {}
        },
        {
          id = 994,
          name = "",
          type = "EG",
          shape = "rectangle",
          x = 4775,
          y = 502,
          width = 25,
          height = 196.75,
          rotation = 0,
          gid = 3,
          visible = true,
          properties = {}
        },
        {
          id = 1110,
          name = "",
          type = "F",
          shape = "rectangle",
          x = -66,
          y = 952.765,
          width = 3793.75,
          height = 50,
          rotation = 0,
          gid = 5,
          visible = true,
          properties = {}
        },
        {
          id = 1139,
          name = "",
          type = "S",
          shape = "rectangle",
          x = 4438.42,
          y = 477.917,
          width = 25,
          height = 25,
          rotation = 0,
          gid = 5,
          visible = true,
          properties = {}
        },
        {
          id = 1140,
          name = "",
          type = "S",
          shape = "rectangle",
          x = 4375.92,
          y = 477.917,
          width = 25,
          height = 25,
          rotation = 0,
          gid = 5,
          visible = true,
          properties = {}
        },
        {
          id = 1141,
          name = "",
          type = "S",
          shape = "rectangle",
          x = 4344.67,
          y = 477.917,
          width = 25,
          height = 25,
          rotation = 0,
          gid = 5,
          visible = true,
          properties = {}
        },
        {
          id = 1142,
          name = "",
          type = "S",
          shape = "rectangle",
          x = 4407.17,
          y = 477.917,
          width = 25,
          height = 25,
          rotation = 0,
          gid = 5,
          visible = true,
          properties = {}
        },
        {
          id = 1158,
          name = "",
          type = "D",
          shape = "rectangle",
          x = 695.97,
          y = 610.159,
          width = 75,
          height = 25,
          rotation = 0,
          gid = 12,
          visible = true,
          properties = {}
        },
        {
          id = 1159,
          name = "",
          type = "L",
          shape = "rectangle",
          x = 847.72,
          y = 662.159,
          width = 77.75,
          height = 25,
          rotation = 0,
          gid = 7,
          visible = true,
          properties = {}
        },
        {
          id = 1160,
          name = "",
          type = "D",
          shape = "rectangle",
          x = 996.97,
          y = 616.159,
          width = 75,
          height = 25,
          rotation = 0,
          gid = 12,
          visible = true,
          properties = {}
        },
        {
          id = 1163,
          name = "",
          type = "G",
          shape = "rectangle",
          x = 1468.4,
          y = 690.917,
          width = 104.152,
          height = 25,
          rotation = 0,
          gid = 6,
          visible = true,
          properties = {}
        },
        {
          id = 1164,
          name = "",
          type = "D",
          shape = "rectangle",
          x = 1312.97,
          y = 684.159,
          width = 75,
          height = 25,
          rotation = 0,
          gid = 12,
          visible = true,
          properties = {}
        },
        {
          id = 1165,
          name = "",
          type = "L",
          shape = "rectangle",
          x = 1150.72,
          y = 654.159,
          width = 77.75,
          height = 25,
          rotation = 0,
          gid = 7,
          visible = true,
          properties = {}
        },
        {
          id = 1166,
          name = "",
          type = "L",
          shape = "rectangle",
          x = 1624.72,
          y = 610.159,
          width = 77.75,
          height = 25,
          rotation = 0,
          gid = 7,
          visible = true,
          properties = {}
        },
        {
          id = 1167,
          name = "",
          type = "D",
          shape = "rectangle",
          x = 1763.97,
          y = 548.159,
          width = 75,
          height = 25,
          rotation = 0,
          gid = 12,
          visible = true,
          properties = {}
        },
        {
          id = 1168,
          name = "",
          type = "G",
          shape = "rectangle",
          x = 3093.75,
          y = 306.25,
          width = 2190.25,
          height = 209.25,
          rotation = 0,
          gid = 6,
          visible = true,
          properties = {}
        },
        {
          id = 1169,
          name = "",
          type = "G",
          shape = "rectangle",
          x = 1923.4,
          y = 495.917,
          width = 75,
          height = 25,
          rotation = 0,
          gid = 6,
          visible = true,
          properties = {}
        },
        {
          id = 1170,
          name = "",
          type = "G",
          shape = "rectangle",
          x = 2009.23,
          y = 574.917,
          width = 285.819,
          height = 25,
          rotation = 0,
          gid = 6,
          visible = true,
          properties = {}
        },
        {
          id = 1171,
          name = "",
          type = "G",
          shape = "rectangle",
          x = 2294.46,
          y = 575.709,
          width = 25,
          height = 105.333,
          rotation = 0,
          gid = 6,
          visible = true,
          properties = {}
        },
        {
          id = 1172,
          name = "",
          type = "G",
          shape = "rectangle",
          x = 1984.46,
          y = 575.375,
          width = 25,
          height = 104.333,
          rotation = 0,
          gid = 6,
          visible = true,
          properties = {}
        },
        {
          id = 1173,
          name = "",
          type = "G",
          shape = "rectangle",
          x = 2119.4,
          y = 499.25,
          width = 99.4853,
          height = 25,
          rotation = 0,
          gid = 6,
          visible = true,
          properties = {}
        },
        {
          id = 1174,
          name = "",
          type = "P3",
          shape = "rectangle",
          x = 2119.58,
          y = 478.333,
          width = 50,
          height = 112.583,
          rotation = 0,
          gid = 10,
          visible = true,
          properties = {}
        },
        {
          id = 1175,
          name = "",
          type = "L",
          shape = "rectangle",
          x = 1969.39,
          y = 808.826,
          width = 77.75,
          height = 25,
          rotation = 0,
          gid = 7,
          visible = true,
          properties = {}
        },
        {
          id = 1176,
          name = "",
          type = "D",
          shape = "rectangle",
          x = 2131.64,
          y = 788.826,
          width = 75,
          height = 25,
          rotation = 0,
          gid = 12,
          visible = true,
          properties = {}
        },
        {
          id = 1179,
          name = "",
          type = "L",
          shape = "rectangle",
          x = 2620.39,
          y = 686.826,
          width = 77.75,
          height = 25,
          rotation = 0,
          gid = 7,
          visible = true,
          properties = {}
        },
        {
          id = 1180,
          name = "",
          type = "D",
          shape = "rectangle",
          x = 2452.5,
          y = 506.25,
          width = 75,
          height = 25,
          rotation = 0,
          gid = 12,
          visible = true,
          properties = {}
        },
        {
          id = 1186,
          name = "",
          type = "D",
          shape = "rectangle",
          x = 2458.54,
          y = 722.833,
          width = 75,
          height = 25,
          rotation = 0,
          gid = 12,
          visible = true,
          properties = {}
        },
        {
          id = 1187,
          name = "",
          type = "L",
          shape = "rectangle",
          x = 2296.63,
          y = 760.167,
          width = 77.75,
          height = 25,
          rotation = 0,
          gid = 7,
          visible = true,
          properties = {}
        },
        {
          id = 1188,
          name = "",
          type = "G",
          shape = "rectangle",
          x = 2319.07,
          y = 495.462,
          width = 83.4853,
          height = 25,
          rotation = 0,
          gid = 6,
          visible = true,
          properties = {}
        },
        {
          id = 1189,
          name = "",
          type = "G",
          shape = "rectangle",
          x = 2790.25,
          y = 675.462,
          width = 303.639,
          height = 25,
          rotation = 0,
          gid = 6,
          visible = true,
          properties = {}
        },
        {
          id = 1190,
          name = "",
          type = "PU2",
          shape = "rectangle",
          x = 2993.75,
          y = 644,
          width = 25,
          height = 25,
          rotation = 0,
          gid = 12,
          visible = true,
          properties = {}
        },
        {
          id = 1191,
          name = "",
          type = "G",
          shape = "rectangle",
          x = 3091.4,
          y = 675.462,
          width = 2192.6,
          height = 173.667,
          rotation = 0,
          gid = 6,
          visible = true,
          properties = {}
        },
        {
          id = 1192,
          name = "",
          type = "G",
          shape = "rectangle",
          x = 3544.07,
          y = 502.462,
          width = 125,
          height = 50,
          rotation = 0,
          gid = 6,
          visible = true,
          properties = {}
        },
        {
          id = 1193,
          name = "",
          type = "G",
          shape = "rectangle",
          x = 3544.07,
          y = 377.462,
          width = 125,
          height = 74.5,
          rotation = 0,
          gid = 6,
          visible = true,
          properties = {}
        },
        {
          id = 1194,
          name = "",
          type = "PU1",
          shape = "rectangle",
          x = 3361.25,
          y = 492.5,
          width = 25,
          height = 25,
          rotation = 0,
          gid = 12,
          visible = true,
          properties = {}
        },
        {
          id = 1195,
          name = "",
          type = "G",
          shape = "rectangle",
          x = 4344.07,
          y = 502.462,
          width = 129,
          height = 25,
          rotation = 0,
          gid = 6,
          visible = true,
          properties = {}
        },
        {
          id = 1196,
          name = "",
          type = "G",
          shape = "rectangle",
          x = 4344.07,
          y = 341.462,
          width = 39.93,
          height = 38.5,
          rotation = 0,
          gid = 6,
          visible = true,
          properties = {}
        },
        {
          id = 1197,
          name = "",
          type = "PU1",
          shape = "rectangle",
          x = 4094.25,
          y = 492,
          width = 25,
          height = 25,
          rotation = 0,
          gid = 12,
          visible = true,
          properties = {}
        },
        {
          id = 1269,
          name = "",
          type = "C",
          shape = "rectangle",
          x = 872.932,
          y = 630.712,
          width = 25,
          height = 25,
          rotation = 0,
          gid = 1,
          visible = true,
          properties = {}
        },
        {
          id = 1270,
          name = "",
          type = "C",
          shape = "rectangle",
          x = 1273.93,
          y = 585.212,
          width = 25,
          height = 25,
          rotation = 0,
          gid = 1,
          visible = true,
          properties = {}
        },
        {
          id = 1271,
          name = "",
          type = "C",
          shape = "rectangle",
          x = 1710.93,
          y = 501.962,
          width = 25,
          height = 25,
          rotation = 0,
          gid = 1,
          visible = true,
          properties = {}
        },
        {
          id = 1272,
          name = "",
          type = "C",
          shape = "rectangle",
          x = 1779.93,
          y = 688.462,
          width = 25,
          height = 25,
          rotation = 0,
          gid = 1,
          visible = true,
          properties = {}
        },
        {
          id = 1273,
          name = "",
          type = "C",
          shape = "rectangle",
          x = 2179.93,
          y = 469.962,
          width = 25,
          height = 25,
          rotation = 0,
          gid = 1,
          visible = true,
          properties = {}
        },
        {
          id = 1274,
          name = "",
          type = "C",
          shape = "rectangle",
          x = 2247.93,
          y = 694.462,
          width = 25,
          height = 25,
          rotation = 0,
          gid = 1,
          visible = true,
          properties = {}
        },
        {
          id = 1275,
          name = "",
          type = "C",
          shape = "rectangle",
          x = 2750,
          y = 518.75,
          width = 25,
          height = 25,
          rotation = 0,
          gid = 1,
          visible = true,
          properties = {}
        },
        {
          id = 1276,
          name = "",
          type = "C",
          shape = "rectangle",
          x = 3592.93,
          y = 424.712,
          width = 25,
          height = 25,
          rotation = 0,
          gid = 1,
          visible = true,
          properties = {}
        },
        {
          id = 1277,
          name = "",
          type = "C",
          shape = "rectangle",
          x = 4396.93,
          y = 401.962,
          width = 25,
          height = 25,
          rotation = 0,
          gid = 1,
          visible = true,
          properties = {}
        },
        {
          id = 1278,
          name = "",
          type = "PU3",
          shape = "rectangle",
          x = 2226.43,
          y = 541.727,
          width = 25,
          height = 25,
          rotation = 0,
          gid = 12,
          visible = true,
          properties = {}
        },
        {
          id = 1287,
          name = "",
          type = "C",
          shape = "rectangle",
          x = 475,
          y = 568.5,
          width = 25,
          height = 25,
          rotation = 0,
          gid = 1,
          visible = true,
          properties = {}
        },
        {
          id = 1288,
          name = "",
          type = "L",
          shape = "rectangle",
          x = 2593.75,
          y = 537.5,
          width = 77.75,
          height = 25,
          rotation = 0,
          gid = 7,
          visible = true,
          properties = {}
        },
        {
          id = 1289,
          name = "",
          type = "G",
          shape = "rectangle",
          x = 4384,
          y = 323.75,
          width = 87.5,
          height = 38.5,
          rotation = 0,
          gid = 6,
          visible = true,
          properties = {}
        },
        {
          id = 1290,
          name = "",
          type = "G",
          shape = "rectangle",
          x = 1640.25,
          y = 775,
          width = 262.5,
          height = 25,
          rotation = 0,
          gid = 6,
          visible = true,
          properties = {}
        }
      }
    }
  }
}
