return {
  version = "1.1",
  luaversion = "5.1",
  tiledversion = "0.17.1",
  orientation = "orthogonal",
  renderorder = "right-down",
  width = 500,
  height = 50,
  tilewidth = 25,
  tileheight = 25,
  nextobjectid = 1229,
  properties = {},
  tilesets = {
    {
      name = "tiles",
      firstgid = 1,
      tilewidth = 25,
      tileheight = 25,
      spacing = 0,
      margin = 0,
      tileoffset = {
        x = 0,
        y = 0
      },
      properties = {},
      terrains = {},
      tilecount = 14,
      tiles = {
        {
          id = 0,
          image = "G:/Feevale/Mapas projeto/tiles/coinTile.png",
          width = 25,
          height = 25
        },
        {
          id = 1,
          image = "G:/Feevale/Mapas projeto/tiles/darkTile.png",
          width = 25,
          height = 25
        },
        {
          id = 2,
          image = "G:/Feevale/Mapas projeto/tiles/endGameTile.png",
          width = 25,
          height = 25
        },
        {
          id = 3,
          image = "G:/Feevale/Mapas projeto/tiles/endZeroGravityTile.png",
          width = 25,
          height = 25
        },
        {
          id = 4,
          image = "G:/Feevale/Mapas projeto/tiles/fatalTile.png",
          width = 25,
          height = 25
        },
        {
          id = 5,
          image = "G:/Feevale/Mapas projeto/tiles/groundTile.png",
          width = 25,
          height = 25
        },
        {
          id = 6,
          image = "G:/Feevale/Mapas projeto/tiles/lightTile.png",
          width = 25,
          height = 25
        },
        {
          id = 7,
          image = "G:/Feevale/Mapas projeto/tiles/portal1Tile.png",
          width = 25,
          height = 25
        },
        {
          id = 8,
          image = "G:/Feevale/Mapas projeto/tiles/portal2Tile.png",
          width = 25,
          height = 25
        },
        {
          id = 9,
          image = "G:/Feevale/Mapas projeto/tiles/portal3Tile.png",
          width = 25,
          height = 25
        },
        {
          id = 10,
          image = "G:/Feevale/Mapas projeto/tiles/portal4Tile.png",
          width = 25,
          height = 25
        },
        {
          id = 11,
          image = "G:/Feevale/Mapas projeto/tiles/powerUpTile.png",
          width = 25,
          height = 25
        },
        {
          id = 12,
          image = "G:/Feevale/Mapas projeto/tiles/spikeTile.png",
          width = 25,
          height = 25
        },
        {
          id = 13,
          image = "G:/Feevale/Mapas projeto/tiles/startZeroGravityTile.png",
          width = 25,
          height = 25
        }
      }
    },
    {
      name = "tiles",
      firstgid = 15,
      tilewidth = 25,
      tileheight = 25,
      spacing = 0,
      margin = 0,
      tileoffset = {
        x = 0,
        y = 0
      },
      properties = {},
      terrains = {},
      tilecount = 14,
      tiles = {
        {
          id = 0,
          image = "G:/Feevale/Mapas projeto/tiles/coinTile.png",
          width = 25,
          height = 25
        },
        {
          id = 1,
          image = "G:/Feevale/Mapas projeto/tiles/darkTile.png",
          width = 25,
          height = 25
        },
        {
          id = 2,
          image = "G:/Feevale/Mapas projeto/tiles/endGameTile.png",
          width = 25,
          height = 25
        },
        {
          id = 3,
          image = "G:/Feevale/Mapas projeto/tiles/endGameTile.png",
          width = 25,
          height = 25
        },
        {
          id = 4,
          image = "G:/Feevale/Mapas projeto/tiles/fatalTile.png",
          width = 25,
          height = 25
        },
        {
          id = 5,
          image = "G:/Feevale/Mapas projeto/tiles/groundTile.png",
          width = 25,
          height = 25
        },
        {
          id = 6,
          image = "G:/Feevale/Mapas projeto/tiles/lightTile.png",
          width = 25,
          height = 25
        },
        {
          id = 7,
          image = "G:/Feevale/Mapas projeto/tiles/portal1Tile.png",
          width = 25,
          height = 25
        },
        {
          id = 8,
          image = "G:/Feevale/Mapas projeto/tiles/portal2Tile.png",
          width = 25,
          height = 25
        },
        {
          id = 9,
          image = "G:/Feevale/Mapas projeto/tiles/portal3Tile.png",
          width = 25,
          height = 25
        },
        {
          id = 10,
          image = "G:/Feevale/Mapas projeto/tiles/portal4Tile.png",
          width = 25,
          height = 25
        },
        {
          id = 11,
          image = "G:/Feevale/Mapas projeto/tiles/powerUpTile.png",
          width = 25,
          height = 25
        },
        {
          id = 12,
          image = "G:/Feevale/Mapas projeto/tiles/spikeTile.png",
          width = 25,
          height = 25
        },
        {
          id = 13,
          image = "G:/Feevale/Mapas projeto/tiles/startZeroGravityTile.png",
          width = 25,
          height = 25
        }
      }
    }
  },
  layers = {
    {
      type = "objectgroup",
      name = "Object Layer 1",
      visible = true,
      opacity = 1,
      offsetx = 166,
      offsety = 128,
      draworder = "topdown",
      properties = {},
      objects = {
        {
          id = 283,
          name = "",
          type = "G",
          shape = "rectangle",
          x = 2.75,
          y = 875,
          width = 1087.6,
          height = 303.25,
          rotation = 0,
          gid = 6,
          visible = true,
          properties = {}
        },
        {
          id = 994,
          name = "",
          type = "EG",
          shape = "rectangle",
          x = 7156.25,
          y = 537.5,
          width = 25,
          height = 327.25,
          rotation = 0,
          gid = 3,
          visible = true,
          properties = {}
        },
        {
          id = 1096,
          name = "",
          type = "L",
          shape = "rectangle",
          x = 1193.75,
          y = 518.75,
          width = 165.25,
          height = 25,
          rotation = 0,
          gid = 7,
          visible = true,
          properties = {}
        },
        {
          id = 1097,
          name = "",
          type = "D",
          shape = "rectangle",
          x = 1375,
          y = 406.25,
          width = 75,
          height = 25,
          rotation = 0,
          gid = 12,
          visible = true,
          properties = {}
        },
        {
          id = 1098,
          name = "",
          type = "L",
          shape = "rectangle",
          x = 1543.75,
          y = 331.25,
          width = 77.75,
          height = 25,
          rotation = 0,
          gid = 7,
          visible = true,
          properties = {}
        },
        {
          id = 1101,
          name = "",
          type = "D",
          shape = "rectangle",
          x = 1706.25,
          y = 237.5,
          width = 172.25,
          height = 25,
          rotation = 0,
          gid = 12,
          visible = true,
          properties = {}
        },
        {
          id = 1104,
          name = "",
          type = "C",
          shape = "rectangle",
          x = 2093.75,
          y = 71.75,
          width = 25,
          height = 25,
          rotation = 0,
          gid = 1,
          visible = true,
          properties = {}
        },
        {
          id = 1108,
          name = "",
          type = "G",
          shape = "rectangle",
          x = 2331.25,
          y = 284.5,
          width = 202.5,
          height = 218.75,
          rotation = 0,
          gid = 6,
          visible = true,
          properties = {}
        },
        {
          id = 1109,
          name = "",
          type = "G",
          shape = "rectangle",
          x = 1952.75,
          y = 143.75,
          width = 251.75,
          height = 21.75,
          rotation = 0,
          gid = 6,
          visible = true,
          properties = {}
        },
        {
          id = 1110,
          name = "",
          type = "F",
          shape = "rectangle",
          x = 1087.5,
          y = 897,
          width = 1247.58,
          height = 165.75,
          rotation = 0,
          gid = 5,
          visible = true,
          properties = {}
        },
        {
          id = 1113,
          name = "",
          type = "G",
          shape = "rectangle",
          x = 3404,
          y = 209.5,
          width = 4455.25,
          height = 280.25,
          rotation = 0,
          gid = 6,
          visible = true,
          properties = {}
        },
        {
          id = 1116,
          name = "",
          type = "G",
          shape = "rectangle",
          x = 3937.5,
          y = 675,
          width = 711.462,
          height = 140.75,
          rotation = 0,
          gid = 6,
          visible = true,
          properties = {}
        },
        {
          id = 1123,
          name = "",
          type = "F",
          shape = "rectangle",
          x = 2442,
          y = 843.75,
          width = 1505.07,
          height = 159.25,
          rotation = 0,
          gid = 5,
          visible = true,
          properties = {}
        },
        {
          id = 1124,
          name = "",
          type = "G",
          shape = "rectangle",
          x = 1925,
          y = -165.5,
          width = 1210.75,
          height = 237.5,
          rotation = 0,
          gid = 6,
          visible = true,
          properties = {}
        },
        {
          id = 1125,
          name = "",
          type = "C",
          shape = "rectangle",
          x = 2827,
          y = 133.75,
          width = 25,
          height = 25,
          rotation = 0,
          gid = 1,
          visible = true,
          properties = {}
        },
        {
          id = 1126,
          name = "",
          type = "G",
          shape = "rectangle",
          x = 2040.25,
          y = 128.25,
          width = 162.25,
          height = 50,
          rotation = 0,
          gid = 6,
          visible = true,
          properties = {}
        },
        {
          id = 1132,
          name = "",
          type = "G",
          shape = "rectangle",
          x = 2331.25,
          y = 770.5,
          width = 115.25,
          height = 693,
          rotation = 0,
          gid = 6,
          visible = true,
          properties = {}
        },
        {
          id = 1138,
          name = "",
          type = "G",
          shape = "rectangle",
          x = 4821.5,
          y = 687.5,
          width = 106.25,
          height = 196.75,
          rotation = 0,
          gid = 6,
          visible = true,
          properties = {}
        },
        {
          id = 1140,
          name = "",
          type = "S",
          shape = "rectangle",
          x = 4862.5,
          y = 493.75,
          width = 25,
          height = 25,
          rotation = 0,
          gid = 5,
          visible = true,
          properties = {}
        },
        {
          id = 1141,
          name = "",
          type = "S",
          shape = "rectangle",
          x = 4831.25,
          y = 493.75,
          width = 25,
          height = 25,
          rotation = 0,
          gid = 5,
          visible = true,
          properties = {}
        },
        {
          id = 1142,
          name = "",
          type = "S",
          shape = "rectangle",
          x = 4893.75,
          y = 493.75,
          width = 25,
          height = 25,
          rotation = 0,
          gid = 5,
          visible = true,
          properties = {}
        },
        {
          id = 1144,
          name = "",
          type = "G",
          shape = "rectangle",
          x = 3943.75,
          y = 847,
          width = 184,
          height = 312.75,
          rotation = 0,
          gid = 6,
          visible = true,
          properties = {}
        },
        {
          id = 1145,
          name = "",
          type = "SZG",
          shape = "rectangle",
          x = 5350,
          y = 544.75,
          width = 25,
          height = 339.159,
          rotation = 0,
          gid = 8,
          visible = true,
          properties = {}
        },
        {
          id = 1150,
          name = "",
          type = "EZG",
          shape = "rectangle",
          x = 6900,
          y = 537.5,
          width = 25,
          height = 333,
          rotation = 0,
          gid = 4,
          visible = true,
          properties = {}
        },
        {
          id = 1153,
          name = "",
          type = "C",
          shape = "rectangle",
          x = 4881.25,
          y = 418.75,
          width = 25,
          height = 25,
          rotation = 0,
          gid = 1,
          visible = true,
          properties = {}
        },
        {
          id = 1158,
          name = "",
          type = "G",
          shape = "rectangle",
          x = 3128.42,
          y = 131.167,
          width = 309.856,
          height = 529.583,
          rotation = 0,
          gid = 6,
          visible = true,
          properties = {}
        },
        {
          id = 1159,
          name = "",
          type = "G",
          shape = "rectangle",
          x = 2628.92,
          y = 122.5,
          width = 115.25,
          height = 15.6667,
          rotation = 0,
          gid = 6,
          visible = true,
          properties = {}
        },
        {
          id = 1160,
          name = "",
          type = "G",
          shape = "rectangle",
          x = 2753.92,
          y = 253.75,
          width = 173.25,
          height = 15.6667,
          rotation = 0,
          gid = 6,
          visible = true,
          properties = {}
        },
        {
          id = 1161,
          name = "",
          type = "D",
          shape = "rectangle",
          x = 2447,
          y = 405.25,
          width = 117,
          height = 25,
          rotation = 0,
          gid = 12,
          visible = true,
          properties = {}
        },
        {
          id = 1162,
          name = "",
          type = "L",
          shape = "rectangle",
          x = 2562.75,
          y = 405.25,
          width = 116.75,
          height = 25,
          rotation = 0,
          gid = 7,
          visible = true,
          properties = {}
        },
        {
          id = 1163,
          name = "",
          type = "D",
          shape = "rectangle",
          x = 2679,
          y = 405.25,
          width = 117,
          height = 25,
          rotation = 0,
          gid = 12,
          visible = true,
          properties = {}
        },
        {
          id = 1164,
          name = "",
          type = "L",
          shape = "rectangle",
          x = 2794.75,
          y = 405.25,
          width = 116.75,
          height = 25,
          rotation = 0,
          gid = 7,
          visible = true,
          properties = {}
        },
        {
          id = 1165,
          name = "",
          type = "D",
          shape = "rectangle",
          x = 2912,
          y = 405.25,
          width = 117,
          height = 25,
          rotation = 0,
          gid = 12,
          visible = true,
          properties = {}
        },
        {
          id = 1166,
          name = "",
          type = "L",
          shape = "rectangle",
          x = 3027.75,
          y = 405.25,
          width = 116.75,
          height = 25,
          rotation = 0,
          gid = 7,
          visible = true,
          properties = {}
        },
        {
          id = 1167,
          name = "",
          type = "D",
          shape = "rectangle",
          x = 3144,
          y = 405.25,
          width = 117,
          height = 25,
          rotation = 0,
          gid = 12,
          visible = true,
          properties = {}
        },
        {
          id = 1168,
          name = "",
          type = "L",
          shape = "rectangle",
          x = 3259.75,
          y = 405.25,
          width = 116.75,
          height = 25,
          rotation = 0,
          gid = 7,
          visible = true,
          properties = {}
        },
        {
          id = 1169,
          name = "",
          type = "D",
          shape = "rectangle",
          x = 3481.5,
          y = 455.25,
          width = 117,
          height = 25,
          rotation = 0,
          gid = 12,
          visible = true,
          properties = {}
        },
        {
          id = 1170,
          name = "",
          type = "L",
          shape = "rectangle",
          x = 3670.25,
          y = 530.25,
          width = 168.75,
          height = 25,
          rotation = 0,
          gid = 7,
          visible = true,
          properties = {}
        },
        {
          id = 1171,
          name = "",
          type = "G",
          shape = "rectangle",
          x = 5090.25,
          y = 675,
          width = 2749.5,
          height = 140.75,
          rotation = 0,
          gid = 6,
          visible = true,
          properties = {}
        },
        {
          id = 1172,
          name = "",
          type = "D",
          shape = "rectangle",
          x = 4648,
          y = 572,
          width = 176,
          height = 37.75,
          rotation = 0,
          gid = 12,
          visible = true,
          properties = {}
        },
        {
          id = 1173,
          name = "",
          type = "L",
          shape = "rectangle",
          x = 4927.75,
          y = 572,
          width = 162.5,
          height = 41.75,
          rotation = 0,
          gid = 7,
          visible = true,
          properties = {}
        },
        {
          id = 1174,
          name = "",
          type = "G",
          shape = "rectangle",
          x = 5733.75,
          y = 694.816,
          width = 30.0552,
          height = 196.961,
          rotation = 0,
          gid = 20,
          visible = true,
          properties = {}
        },
        {
          id = 1175,
          name = "",
          type = "G",
          shape = "rectangle",
          x = 6475.12,
          y = 684.398,
          width = 30.0552,
          height = 182.535,
          rotation = 0,
          gid = 20,
          visible = true,
          properties = {}
        },
        {
          id = 1176,
          name = "",
          type = "G",
          shape = "rectangle",
          x = 6303.6,
          y = 661.555,
          width = 30.0552,
          height = 240.241,
          rotation = 0,
          gid = 20,
          visible = true,
          properties = {}
        },
        {
          id = 1177,
          name = "",
          type = "G",
          shape = "rectangle",
          x = 6503.97,
          y = 693.615,
          width = 30.0552,
          height = 182.535,
          rotation = 0,
          gid = 20,
          visible = true,
          properties = {}
        },
        {
          id = 1178,
          name = "",
          type = "G",
          shape = "rectangle",
          x = 5823.92,
          y = 665.963,
          width = 30.0552,
          height = 196.961,
          rotation = 0,
          gid = 20,
          visible = true,
          properties = {}
        },
        {
          id = 1179,
          name = "",
          type = "G",
          shape = "rectangle",
          x = 5583.48,
          y = 740.5,
          width = 30.0552,
          height = 196.961,
          rotation = 0,
          gid = 20,
          visible = true,
          properties = {}
        },
        {
          id = 1180,
          name = "",
          type = "G",
          shape = "rectangle",
          x = 5914.08,
          y = 638.312,
          width = 30.0552,
          height = 196.961,
          rotation = 0,
          gid = 20,
          visible = true,
          properties = {}
        },
        {
          id = 1181,
          name = "",
          type = "G",
          shape = "rectangle",
          x = 5703.7,
          y = 703.232,
          width = 30.0552,
          height = 196.961,
          rotation = 0,
          gid = 20,
          visible = true,
          properties = {}
        },
        {
          id = 1182,
          name = "",
          type = "G",
          shape = "rectangle",
          x = 5884.03,
          y = 649.132,
          width = 30.0552,
          height = 196.961,
          rotation = 0,
          gid = 20,
          visible = true,
          properties = {}
        },
        {
          id = 1183,
          name = "",
          type = "G",
          shape = "rectangle",
          x = 5673.64,
          y = 711.647,
          width = 30.0552,
          height = 196.961,
          rotation = 0,
          gid = 20,
          visible = true,
          properties = {}
        },
        {
          id = 1184,
          name = "",
          type = "G",
          shape = "rectangle",
          x = 5763.81,
          y = 683.996,
          width = 30.0552,
          height = 196.961,
          rotation = 0,
          gid = 20,
          visible = true,
          properties = {}
        },
        {
          id = 1185,
          name = "",
          type = "G",
          shape = "rectangle",
          x = 6360.5,
          y = 661.956,
          width = 30.0552,
          height = 217.399,
          rotation = 0,
          gid = 20,
          visible = true,
          properties = {}
        },
        {
          id = 1186,
          name = "",
          type = "G",
          shape = "rectangle",
          x = 5643.59,
          y = 721.265,
          width = 30.0552,
          height = 196.961,
          rotation = 0,
          gid = 20,
          visible = true,
          properties = {}
        },
        {
          id = 1187,
          name = "",
          type = "G",
          shape = "rectangle",
          x = 5944.14,
          y = 626.29,
          width = 30.0552,
          height = 196.961,
          rotation = 0,
          gid = 20,
          visible = true,
          properties = {}
        },
        {
          id = 1189,
          name = "",
          type = "G",
          shape = "rectangle",
          x = 5853.97,
          y = 657.548,
          width = 30.0552,
          height = 196.961,
          rotation = 0,
          gid = 20,
          visible = true,
          properties = {}
        },
        {
          id = 1190,
          name = "",
          type = "G",
          shape = "rectangle",
          x = 6331.65,
          y = 684.798,
          width = 30.0552,
          height = 252.864,
          rotation = 0,
          gid = 20,
          visible = true,
          properties = {}
        },
        {
          id = 1191,
          name = "",
          type = "G",
          shape = "rectangle",
          x = 6446.26,
          y = 670.773,
          width = 30.0552,
          height = 182.535,
          rotation = 0,
          gid = 20,
          visible = true,
          properties = {}
        },
        {
          id = 1192,
          name = "",
          type = "G",
          shape = "rectangle",
          x = 5974.19,
          y = 613.066,
          width = 30.0552,
          height = 196.961,
          rotation = 0,
          gid = 20,
          visible = true,
          properties = {}
        },
        {
          id = 1193,
          name = "",
          type = "G",
          shape = "rectangle",
          x = 6418.2,
          y = 656.747,
          width = 30.0552,
          height = 182.535,
          rotation = 0,
          gid = 20,
          visible = true,
          properties = {}
        },
        {
          id = 1194,
          name = "",
          type = "G",
          shape = "rectangle",
          x = 6390.16,
          y = 683.196,
          width = 30.0552,
          height = 225.814,
          rotation = 0,
          gid = 20,
          visible = true,
          properties = {}
        },
        {
          id = 1195,
          name = "",
          type = "G",
          shape = "rectangle",
          x = 5793.86,
          y = 675.581,
          width = 30.0552,
          height = 196.961,
          rotation = 0,
          gid = 20,
          visible = true,
          properties = {}
        },
        {
          id = 1196,
          name = "",
          type = "G",
          shape = "rectangle",
          x = 5613.53,
          y = 729.68,
          width = 30.0552,
          height = 196.961,
          rotation = 0,
          gid = 20,
          visible = true,
          properties = {}
        },
        {
          id = 1197,
          name = "",
          type = "G",
          shape = "rectangle",
          x = 6034.3,
          y = 592.628,
          width = 247.655,
          height = 196.961,
          rotation = 0,
          gid = 20,
          visible = true,
          properties = {}
        },
        {
          id = 1198,
          name = "",
          type = "G",
          shape = "rectangle",
          x = 6274.74,
          y = 649.132,
          width = 30.0552,
          height = 240.241,
          rotation = 0,
          gid = 20,
          visible = true,
          properties = {}
        },
        {
          id = 1199,
          name = "",
          type = "G",
          shape = "rectangle",
          x = 6004.25,
          y = 601.044,
          width = 30.0552,
          height = 196.961,
          rotation = 0,
          gid = 20,
          visible = true,
          properties = {}
        },
        {
          id = 1200,
          name = "",
          type = "S",
          shape = "rectangle",
          x = 5643.75,
          y = 524.75,
          width = 25,
          height = 25,
          rotation = 0,
          gid = 5,
          visible = true,
          properties = {}
        },
        {
          id = 1201,
          name = "",
          type = "S",
          shape = "rectangle",
          x = 5614.83,
          y = 532.75,
          width = 25,
          height = 25,
          rotation = 0,
          gid = 5,
          visible = true,
          properties = {}
        },
        {
          id = 1202,
          name = "",
          type = "S",
          shape = "rectangle",
          x = 5583.58,
          y = 545.417,
          width = 25,
          height = 25,
          rotation = 0,
          gid = 5,
          visible = true,
          properties = {}
        },
        {
          id = 1203,
          name = "",
          type = "S",
          shape = "rectangle",
          x = 5674,
          y = 516.75,
          width = 25,
          height = 25,
          rotation = 0,
          gid = 5,
          visible = true,
          properties = {}
        },
        {
          id = 1204,
          name = "",
          type = "S",
          shape = "rectangle",
          x = 5703.58,
          y = 507.417,
          width = 25,
          height = 25,
          rotation = 0,
          gid = 5,
          visible = true,
          properties = {}
        },
        {
          id = 1205,
          name = "",
          type = "S",
          shape = "rectangle",
          x = 5764.09,
          y = 487.084,
          width = 25,
          height = 25,
          rotation = 0,
          gid = 5,
          visible = true,
          properties = {}
        },
        {
          id = 1206,
          name = "",
          type = "S",
          shape = "rectangle",
          x = 5734.17,
          y = 498.75,
          width = 25,
          height = 25,
          rotation = 0,
          gid = 5,
          visible = true,
          properties = {}
        },
        {
          id = 1207,
          name = "",
          type = "S",
          shape = "rectangle",
          x = 5794.34,
          y = 478.75,
          width = 25,
          height = 25,
          rotation = 0,
          gid = 5,
          visible = true,
          properties = {}
        },
        {
          id = 1208,
          name = "",
          type = "S",
          shape = "rectangle",
          x = 5823.58,
          y = 470.417,
          width = 25,
          height = 25,
          rotation = 0,
          gid = 5,
          visible = true,
          properties = {}
        },
        {
          id = 1209,
          name = "",
          type = "S",
          shape = "rectangle",
          x = 5944.58,
          y = 432.417,
          width = 25,
          height = 25,
          rotation = 0,
          gid = 5,
          visible = true,
          properties = {}
        },
        {
          id = 1210,
          name = "",
          type = "S",
          shape = "rectangle",
          x = 6004.09,
          y = 410.084,
          width = 25,
          height = 25,
          rotation = 0,
          gid = 5,
          visible = true,
          properties = {}
        },
        {
          id = 1211,
          name = "",
          type = "S",
          shape = "rectangle",
          x = 5975.17,
          y = 423.75,
          width = 25,
          height = 25,
          rotation = 0,
          gid = 5,
          visible = true,
          properties = {}
        },
        {
          id = 1212,
          name = "",
          type = "S",
          shape = "rectangle",
          x = 5884.75,
          y = 451.75,
          width = 25,
          height = 25,
          rotation = 0,
          gid = 5,
          visible = true,
          properties = {}
        },
        {
          id = 1214,
          name = "",
          type = "S",
          shape = "rectangle",
          x = 5853.83,
          y = 460.75,
          width = 25,
          height = 25,
          rotation = 0,
          gid = 5,
          visible = true,
          properties = {}
        },
        {
          id = 1215,
          name = "",
          type = "S",
          shape = "rectangle",
          x = 5915,
          y = 441.75,
          width = 25,
          height = 25,
          rotation = 0,
          gid = 5,
          visible = true,
          properties = {}
        },
        {
          id = 1216,
          name = "",
          type = "S",
          shape = "rectangle",
          x = 6101.87,
          y = 395.5,
          width = 25,
          height = 25,
          rotation = 0,
          gid = 5,
          visible = true,
          properties = {}
        },
        {
          id = 1217,
          name = "",
          type = "S",
          shape = "rectangle",
          x = 6070.62,
          y = 395.5,
          width = 25,
          height = 25,
          rotation = 0,
          gid = 5,
          visible = true,
          properties = {}
        },
        {
          id = 1218,
          name = "",
          type = "S",
          shape = "rectangle",
          x = 6039.37,
          y = 395.5,
          width = 25,
          height = 25,
          rotation = 0,
          gid = 5,
          visible = true,
          properties = {}
        },
        {
          id = 1219,
          name = "",
          type = "S",
          shape = "rectangle",
          x = 6133.12,
          y = 395.5,
          width = 25,
          height = 25,
          rotation = 0,
          gid = 5,
          visible = true,
          properties = {}
        },
        {
          id = 1220,
          name = "",
          type = "S",
          shape = "rectangle",
          x = 6228.2,
          y = 394.833,
          width = 25,
          height = 25,
          rotation = 0,
          gid = 5,
          visible = true,
          properties = {}
        },
        {
          id = 1221,
          name = "",
          type = "S",
          shape = "rectangle",
          x = 6196.95,
          y = 394.833,
          width = 25,
          height = 25,
          rotation = 0,
          gid = 5,
          visible = true,
          properties = {}
        },
        {
          id = 1222,
          name = "",
          type = "S",
          shape = "rectangle",
          x = 6165.7,
          y = 394.833,
          width = 25,
          height = 25,
          rotation = 0,
          gid = 5,
          visible = true,
          properties = {}
        },
        {
          id = 1224,
          name = "",
          type = "G",
          shape = "rectangle",
          x = 5662.11,
          y = 357.348,
          width = 46,
          height = 38.0833,
          rotation = 0,
          gid = 6,
          visible = true,
          properties = {}
        },
        {
          id = 1225,
          name = "",
          type = "C",
          shape = "rectangle",
          x = 5775,
          y = 331.25,
          width = 25,
          height = 25,
          rotation = 0,
          gid = 1,
          visible = true,
          properties = {}
        },
        {
          id = 1226,
          name = "",
          type = "F",
          shape = "rectangle",
          x = 4093.75,
          y = 781.25,
          width = 1505.07,
          height = 159.25,
          rotation = 0,
          gid = 5,
          visible = true,
          properties = {}
        },
        {
          id = 1227,
          name = "",
          type = "PU2",
          shape = "rectangle",
          x = 4728.75,
          y = 528.75,
          width = 25,
          height = 25,
          rotation = 0,
          gid = 12,
          visible = true,
          properties = {}
        },
        {
          id = 1228,
          name = "",
          type = "C",
          shape = "rectangle",
          x = 3018.75,
          y = 275,
          width = 25,
          height = 25,
          rotation = 0,
          gid = 1,
          visible = true,
          properties = {}
        }
      }
    }
  }
}
