return {
  version = "1.1",
  luaversion = "5.1",
  tiledversion = "0.17.1",
  orientation = "orthogonal",
  renderorder = "right-down",
  width = 500,
  height = 50,
  tilewidth = 25,
  tileheight = 25,
  nextobjectid = 1237,
  properties = {},
  tilesets = {
    {
      name = "tiles",
      firstgid = 1,
      tilewidth = 25,
      tileheight = 25,
      spacing = 0,
      margin = 0,
      tileoffset = {
        x = 0,
        y = 0
      },
      properties = {},
      terrains = {},
      tilecount = 14,
      tiles = {
        {
          id = 0,
          image = "tiledFiles/tiles/coinTile.png",
          width = 25,
          height = 25
        },
        {
          id = 1,
          image = "tiledFiles/tiles/darkTile.png",
          width = 25,
          height = 25
        },
        {
          id = 2,
          image = "tiledFiles/tiles/endGameTile.png",
          width = 25,
          height = 25
        },
        {
          id = 3,
          image = "tiledFiles/tiles/endZeroGravityTile.png",
          width = 25,
          height = 25
        },
        {
          id = 4,
          image = "tiledFiles/tiles/fatalTile.png",
          width = 25,
          height = 25
        },
        {
          id = 5,
          image = "tiledFiles/tiles/groundTile.png",
          width = 25,
          height = 25
        },
        {
          id = 6,
          image = "tiledFiles/tiles/lightTile.png",
          width = 25,
          height = 25
        },
        {
          id = 7,
          image = "tiledFiles/tiles/portal1Tile.png",
          width = 25,
          height = 25
        },
        {
          id = 8,
          image = "tiledFiles/tiles/portal2Tile.png",
          width = 25,
          height = 25
        },
        {
          id = 9,
          image = "tiledFiles/tiles/portal3Tile.png",
          width = 25,
          height = 25
        },
        {
          id = 10,
          image = "tiledFiles/tiles/portal4Tile.png",
          width = 25,
          height = 25
        },
        {
          id = 11,
          image = "tiledFiles/tiles/powerUpTile.png",
          width = 25,
          height = 25
        },
        {
          id = 12,
          image = "tiledFiles/tiles/spikeTile.png",
          width = 25,
          height = 25
        },
        {
          id = 13,
          image = "tiledFiles/tiles/startZeroGravityTile.png",
          width = 25,
          height = 25
        }
      }
    },
    {
      name = "tiles",
      firstgid = 15,
      tilewidth = 25,
      tileheight = 25,
      spacing = 0,
      margin = 0,
      tileoffset = {
        x = 0,
        y = 0
      },
      properties = {},
      terrains = {},
      tilecount = 14,
      tiles = {
        {
          id = 0,
          image = "tiledFiles/tiles/coinTile.png",
          width = 25,
          height = 25
        },
        {
          id = 1,
          image = "tiledFiles/tiles/darkTile.png",
          width = 25,
          height = 25
        },
        {
          id = 2,
          image = "tiledFiles/tiles/endGameTile.png",
          width = 25,
          height = 25
        },
        {
          id = 3,
          image = "tiledFiles/tiles/endGameTile.png",
          width = 25,
          height = 25
        },
        {
          id = 4,
          image = "tiledFiles/tiles/fatalTile.png",
          width = 25,
          height = 25
        },
        {
          id = 5,
          image = "tiledFiles/tiles/groundTile.png",
          width = 25,
          height = 25
        },
        {
          id = 6,
          image = "tiledFiles/tiles/lightTile.png",
          width = 25,
          height = 25
        },
        {
          id = 7,
          image = "tiledFiles/tiles/portal1Tile.png",
          width = 25,
          height = 25
        },
        {
          id = 8,
          image = "tiledFiles/tiles/portal2Tile.png",
          width = 25,
          height = 25
        },
        {
          id = 9,
          image = "tiledFiles/tiles/portal3Tile.png",
          width = 25,
          height = 25
        },
        {
          id = 10,
          image = "tiledFiles/tiles/portal4Tile.png",
          width = 25,
          height = 25
        },
        {
          id = 11,
          image = "tiledFiles/tiles/powerUpTile.png",
          width = 25,
          height = 25
        },
        {
          id = 12,
          image = "tiledFiles/tiles/spikeTile.png",
          width = 25,
          height = 25
        },
        {
          id = 13,
          image = "tiledFiles/tiles/startZeroGravityTile.png",
          width = 25,
          height = 25
        }
      }
    }
  },
  layers = {
    {
      type = "objectgroup",
      name = "Object Layer 1",
      visible = true,
      opacity = 1,
      offsetx = 166,
      offsety = 128,
      draworder = "topdown",
      properties = {},
      objects = {
        {
          id = 283,
          name = "",
          type = "G",
          shape = "rectangle",
          x = -466,
          y = 875,
          width = 1087.6,
          height = 303.25,
          rotation = 0,
          gid = 6,
          visible = true,
          properties = {}
        },
        {
          id = 994,
          name = "",
          type = "EG",
          shape = "rectangle",
          x = 6689.5,
          y = 537.5,
          width = 25,
          height = 327.25,
          rotation = 0,
          gid = 3,
          visible = true,
          properties = {}
        },
        {
          id = 1096,
          name = "",
          type = "L",
          shape = "rectangle",
          x = 725,
          y = 518.75,
          width = 165.25,
          height = 25,
          rotation = 0,
          gid = 7,
          visible = true,
          properties = {}
        },
        {
          id = 1097,
          name = "",
          type = "D",
          shape = "rectangle",
          x = 906.25,
          y = 406.25,
          width = 75,
          height = 25,
          rotation = 0,
          gid = 12,
          visible = true,
          properties = {}
        },
        {
          id = 1098,
          name = "",
          type = "L",
          shape = "rectangle",
          x = 1075,
          y = 331.25,
          width = 77.75,
          height = 25,
          rotation = 0,
          gid = 7,
          visible = true,
          properties = {}
        },
        {
          id = 1101,
          name = "",
          type = "D",
          shape = "rectangle",
          x = 1237.5,
          y = 237.5,
          width = 172.25,
          height = 25,
          rotation = 0,
          gid = 12,
          visible = true,
          properties = {}
        },
        {
          id = 1104,
          name = "",
          type = "C",
          shape = "rectangle",
          x = 1625,
          y = 71.75,
          width = 25,
          height = 25,
          rotation = 0,
          gid = 1,
          visible = true,
          properties = {}
        },
        {
          id = 1108,
          name = "",
          type = "G",
          shape = "rectangle",
          x = 1862.5,
          y = 897,
          width = 202.5,
          height = 831.25,
          rotation = 0,
          gid = 6,
          visible = true,
          properties = {}
        },
        {
          id = 1109,
          name = "",
          type = "G",
          shape = "rectangle",
          x = 1487.5,
          y = 147,
          width = 252.75,
          height = 25,
          rotation = 0,
          gid = 6,
          visible = true,
          properties = {}
        },
        {
          id = 1110,
          name = "",
          type = "F",
          shape = "rectangle",
          x = 618.75,
          y = 897,
          width = 1247.58,
          height = 165.75,
          rotation = 0,
          gid = 5,
          visible = true,
          properties = {}
        },
        {
          id = 1113,
          name = "",
          type = "G",
          shape = "rectangle",
          x = 4627.75,
          y = 209.5,
          width = 2762.75,
          height = 280.25,
          rotation = 0,
          gid = 6,
          visible = true,
          properties = {}
        },
        {
          id = 1123,
          name = "",
          type = "F",
          shape = "rectangle",
          x = 1973.25,
          y = 843.75,
          width = 1505.07,
          height = 159.25,
          rotation = 0,
          gid = 5,
          visible = true,
          properties = {}
        },
        {
          id = 1124,
          name = "",
          type = "G",
          shape = "rectangle",
          x = 1456.25,
          y = -215.5,
          width = 1210.75,
          height = 187.5,
          rotation = 0,
          gid = 6,
          visible = true,
          properties = {}
        },
        {
          id = 1125,
          name = "",
          type = "C",
          shape = "rectangle",
          x = 2358.25,
          y = 133.75,
          width = 25,
          height = 25,
          rotation = 0,
          gid = 1,
          visible = true,
          properties = {}
        },
        {
          id = 1126,
          name = "",
          type = "G",
          shape = "rectangle",
          x = 1571.5,
          y = 147,
          width = 168.75,
          height = 68.75,
          rotation = 0,
          gid = 6,
          visible = true,
          properties = {}
        },
        {
          id = 1138,
          name = "",
          type = "G",
          shape = "rectangle",
          x = 4356.25,
          y = 1053.25,
          width = 106.25,
          height = 559.5,
          rotation = 0,
          gid = 6,
          visible = true,
          properties = {}
        },
        {
          id = 1140,
          name = "",
          type = "S",
          shape = "rectangle",
          x = 4395.75,
          y = 493.75,
          width = 25,
          height = 25,
          rotation = 0,
          gid = 5,
          visible = true,
          properties = {}
        },
        {
          id = 1141,
          name = "",
          type = "S",
          shape = "rectangle",
          x = 4364.5,
          y = 493.75,
          width = 25,
          height = 25,
          rotation = 0,
          gid = 5,
          visible = true,
          properties = {}
        },
        {
          id = 1142,
          name = "",
          type = "S",
          shape = "rectangle",
          x = 4427,
          y = 493.75,
          width = 25,
          height = 25,
          rotation = 0,
          gid = 5,
          visible = true,
          properties = {}
        },
        {
          id = 1144,
          name = "",
          type = "G",
          shape = "rectangle",
          x = 3456.25,
          y = 1009.5,
          width = 725,
          height = 475,
          rotation = 0,
          gid = 6,
          visible = true,
          properties = {}
        },
        {
          id = 1145,
          name = "",
          type = "SZG",
          shape = "rectangle",
          x = 4883.25,
          y = 544.75,
          width = 25,
          height = 335.25,
          rotation = 0,
          gid = 8,
          visible = true,
          properties = {}
        },
        {
          id = 1150,
          name = "",
          type = "EZG",
          shape = "rectangle",
          x = 6433.25,
          y = 537.5,
          width = 25,
          height = 328,
          rotation = 0,
          gid = 4,
          visible = true,
          properties = {}
        },
        {
          id = 1153,
          name = "",
          type = "C",
          shape = "rectangle",
          x = 4414.5,
          y = 418.75,
          width = 25,
          height = 25,
          rotation = 0,
          gid = 1,
          visible = true,
          properties = {}
        },
        {
          id = 1158,
          name = "",
          type = "G",
          shape = "rectangle",
          x = 2659.67,
          y = 131.167,
          width = 309.856,
          height = 529.583,
          rotation = 0,
          gid = 6,
          visible = true,
          properties = {}
        },
        {
          id = 1159,
          name = "",
          type = "G",
          shape = "rectangle",
          x = 2156.25,
          y = 125,
          width = 115.25,
          height = 15.6667,
          rotation = 0,
          gid = 6,
          visible = true,
          properties = {}
        },
        {
          id = 1160,
          name = "",
          type = "G",
          shape = "rectangle",
          x = 2285.17,
          y = 253.75,
          width = 173.25,
          height = 15.6667,
          rotation = 0,
          gid = 6,
          visible = true,
          properties = {}
        },
        {
          id = 1165,
          name = "",
          type = "D",
          shape = "rectangle",
          x = 2502.75,
          y = 405.25,
          width = 182.5,
          height = 25,
          rotation = 0,
          gid = 12,
          visible = true,
          properties = {}
        },
        {
          id = 1166,
          name = "",
          type = "L",
          shape = "rectangle",
          x = 2684,
          y = 405.25,
          width = 116.75,
          height = 25,
          rotation = 0,
          gid = 7,
          visible = true,
          properties = {}
        },
        {
          id = 1167,
          name = "",
          type = "D",
          shape = "rectangle",
          x = 2800.25,
          y = 405.25,
          width = 117,
          height = 25,
          rotation = 0,
          gid = 12,
          visible = true,
          properties = {}
        },
        {
          id = 1171,
          name = "",
          type = "G",
          shape = "rectangle",
          x = 4623.5,
          y = 1065.75,
          width = 2749.5,
          height = 531.5,
          rotation = 0,
          gid = 6,
          visible = true,
          properties = {}
        },
        {
          id = 1172,
          name = "",
          type = "D",
          shape = "rectangle",
          x = 4462.5,
          y = 572,
          width = 165.25,
          height = 37.75,
          rotation = 0,
          gid = 12,
          visible = true,
          properties = {}
        },
        {
          id = 1173,
          name = "",
          type = "L",
          shape = "rectangle",
          x = 4179.75,
          y = 576,
          width = 179.25,
          height = 41.75,
          rotation = 0,
          gid = 7,
          visible = true,
          properties = {}
        },
        {
          id = 1174,
          name = "",
          type = "G",
          shape = "rectangle",
          x = 5267,
          y = 694.816,
          width = 30.0552,
          height = 196.961,
          rotation = 0,
          gid = 20,
          visible = true,
          properties = {}
        },
        {
          id = 1175,
          name = "",
          type = "G",
          shape = "rectangle",
          x = 6008.37,
          y = 684.398,
          width = 30.0552,
          height = 182.535,
          rotation = 0,
          gid = 20,
          visible = true,
          properties = {}
        },
        {
          id = 1176,
          name = "",
          type = "G",
          shape = "rectangle",
          x = 5836.85,
          y = 661.555,
          width = 30.0552,
          height = 240.241,
          rotation = 0,
          gid = 20,
          visible = true,
          properties = {}
        },
        {
          id = 1177,
          name = "",
          type = "G",
          shape = "rectangle",
          x = 6037.22,
          y = 693.615,
          width = 30.0552,
          height = 182.535,
          rotation = 0,
          gid = 20,
          visible = true,
          properties = {}
        },
        {
          id = 1178,
          name = "",
          type = "G",
          shape = "rectangle",
          x = 5357.17,
          y = 665.963,
          width = 30.0552,
          height = 196.961,
          rotation = 0,
          gid = 20,
          visible = true,
          properties = {}
        },
        {
          id = 1179,
          name = "",
          type = "G",
          shape = "rectangle",
          x = 5116.73,
          y = 740.5,
          width = 30.0552,
          height = 196.961,
          rotation = 0,
          gid = 20,
          visible = true,
          properties = {}
        },
        {
          id = 1180,
          name = "",
          type = "G",
          shape = "rectangle",
          x = 5447.33,
          y = 638.312,
          width = 30.0552,
          height = 196.961,
          rotation = 0,
          gid = 20,
          visible = true,
          properties = {}
        },
        {
          id = 1181,
          name = "",
          type = "G",
          shape = "rectangle",
          x = 5236.95,
          y = 703.232,
          width = 30.0552,
          height = 196.961,
          rotation = 0,
          gid = 20,
          visible = true,
          properties = {}
        },
        {
          id = 1182,
          name = "",
          type = "G",
          shape = "rectangle",
          x = 5417.28,
          y = 649.132,
          width = 30.0552,
          height = 196.961,
          rotation = 0,
          gid = 20,
          visible = true,
          properties = {}
        },
        {
          id = 1183,
          name = "",
          type = "G",
          shape = "rectangle",
          x = 5206.89,
          y = 711.647,
          width = 30.0552,
          height = 196.961,
          rotation = 0,
          gid = 20,
          visible = true,
          properties = {}
        },
        {
          id = 1184,
          name = "",
          type = "G",
          shape = "rectangle",
          x = 5297.06,
          y = 683.996,
          width = 30.0552,
          height = 196.961,
          rotation = 0,
          gid = 20,
          visible = true,
          properties = {}
        },
        {
          id = 1185,
          name = "",
          type = "G",
          shape = "rectangle",
          x = 5893.75,
          y = 661.956,
          width = 30.0552,
          height = 217.399,
          rotation = 0,
          gid = 20,
          visible = true,
          properties = {}
        },
        {
          id = 1186,
          name = "",
          type = "G",
          shape = "rectangle",
          x = 5176.84,
          y = 721.265,
          width = 30.0552,
          height = 196.961,
          rotation = 0,
          gid = 20,
          visible = true,
          properties = {}
        },
        {
          id = 1187,
          name = "",
          type = "G",
          shape = "rectangle",
          x = 5477.39,
          y = 626.29,
          width = 30.0552,
          height = 196.961,
          rotation = 0,
          gid = 20,
          visible = true,
          properties = {}
        },
        {
          id = 1189,
          name = "",
          type = "G",
          shape = "rectangle",
          x = 5387.22,
          y = 657.548,
          width = 30.0552,
          height = 196.961,
          rotation = 0,
          gid = 20,
          visible = true,
          properties = {}
        },
        {
          id = 1190,
          name = "",
          type = "G",
          shape = "rectangle",
          x = 5864.9,
          y = 684.798,
          width = 30.0552,
          height = 252.864,
          rotation = 0,
          gid = 20,
          visible = true,
          properties = {}
        },
        {
          id = 1191,
          name = "",
          type = "G",
          shape = "rectangle",
          x = 5979.51,
          y = 670.773,
          width = 30.0552,
          height = 182.535,
          rotation = 0,
          gid = 20,
          visible = true,
          properties = {}
        },
        {
          id = 1192,
          name = "",
          type = "G",
          shape = "rectangle",
          x = 5507.44,
          y = 613.066,
          width = 32.81,
          height = 196.961,
          rotation = 0,
          gid = 20,
          visible = true,
          properties = {}
        },
        {
          id = 1193,
          name = "",
          type = "G",
          shape = "rectangle",
          x = 5951.45,
          y = 656.747,
          width = 30.0552,
          height = 182.535,
          rotation = 0,
          gid = 20,
          visible = true,
          properties = {}
        },
        {
          id = 1194,
          name = "",
          type = "G",
          shape = "rectangle",
          x = 5923.41,
          y = 683.196,
          width = 30.0552,
          height = 225.814,
          rotation = 0,
          gid = 20,
          visible = true,
          properties = {}
        },
        {
          id = 1195,
          name = "",
          type = "G",
          shape = "rectangle",
          x = 5327.11,
          y = 675.581,
          width = 30.0552,
          height = 196.961,
          rotation = 0,
          gid = 20,
          visible = true,
          properties = {}
        },
        {
          id = 1196,
          name = "",
          type = "G",
          shape = "rectangle",
          x = 5146.78,
          y = 729.68,
          width = 30.0552,
          height = 196.961,
          rotation = 0,
          gid = 20,
          visible = true,
          properties = {}
        },
        {
          id = 1197,
          name = "",
          type = "G",
          shape = "rectangle",
          x = 5567.55,
          y = 592.628,
          width = 247.655,
          height = 196.961,
          rotation = 0,
          gid = 20,
          visible = true,
          properties = {}
        },
        {
          id = 1198,
          name = "",
          type = "G",
          shape = "rectangle",
          x = 5807.99,
          y = 649.132,
          width = 30.0552,
          height = 240.241,
          rotation = 0,
          gid = 20,
          visible = true,
          properties = {}
        },
        {
          id = 1199,
          name = "",
          type = "G",
          shape = "rectangle",
          x = 5537.5,
          y = 601.044,
          width = 30.0552,
          height = 196.961,
          rotation = 0,
          gid = 20,
          visible = true,
          properties = {}
        },
        {
          id = 1200,
          name = "",
          type = "S",
          shape = "rectangle",
          x = 5177,
          y = 524.75,
          width = 25,
          height = 25,
          rotation = 0,
          gid = 5,
          visible = true,
          properties = {}
        },
        {
          id = 1201,
          name = "",
          type = "S",
          shape = "rectangle",
          x = 5148.08,
          y = 532.75,
          width = 25,
          height = 25,
          rotation = 0,
          gid = 5,
          visible = true,
          properties = {}
        },
        {
          id = 1202,
          name = "",
          type = "S",
          shape = "rectangle",
          x = 5116.83,
          y = 545.417,
          width = 25,
          height = 25,
          rotation = 0,
          gid = 5,
          visible = true,
          properties = {}
        },
        {
          id = 1203,
          name = "",
          type = "S",
          shape = "rectangle",
          x = 5207.25,
          y = 516.75,
          width = 25,
          height = 25,
          rotation = 0,
          gid = 5,
          visible = true,
          properties = {}
        },
        {
          id = 1204,
          name = "",
          type = "S",
          shape = "rectangle",
          x = 5236.83,
          y = 507.417,
          width = 25,
          height = 25,
          rotation = 0,
          gid = 5,
          visible = true,
          properties = {}
        },
        {
          id = 1205,
          name = "",
          type = "S",
          shape = "rectangle",
          x = 5297.34,
          y = 487.084,
          width = 25,
          height = 25,
          rotation = 0,
          gid = 5,
          visible = true,
          properties = {}
        },
        {
          id = 1206,
          name = "",
          type = "S",
          shape = "rectangle",
          x = 5267.42,
          y = 498.75,
          width = 25,
          height = 25,
          rotation = 0,
          gid = 5,
          visible = true,
          properties = {}
        },
        {
          id = 1207,
          name = "",
          type = "S",
          shape = "rectangle",
          x = 5327.59,
          y = 478.75,
          width = 25,
          height = 25,
          rotation = 0,
          gid = 5,
          visible = true,
          properties = {}
        },
        {
          id = 1208,
          name = "",
          type = "S",
          shape = "rectangle",
          x = 5356.83,
          y = 470.417,
          width = 25,
          height = 25,
          rotation = 0,
          gid = 5,
          visible = true,
          properties = {}
        },
        {
          id = 1209,
          name = "",
          type = "S",
          shape = "rectangle",
          x = 5477.83,
          y = 432.417,
          width = 25,
          height = 25,
          rotation = 0,
          gid = 5,
          visible = true,
          properties = {}
        },
        {
          id = 1210,
          name = "",
          type = "S",
          shape = "rectangle",
          x = 5537.34,
          y = 410.084,
          width = 25,
          height = 25,
          rotation = 0,
          gid = 5,
          visible = true,
          properties = {}
        },
        {
          id = 1211,
          name = "",
          type = "S",
          shape = "rectangle",
          x = 5508.42,
          y = 423.75,
          width = 25,
          height = 25,
          rotation = 0,
          gid = 5,
          visible = true,
          properties = {}
        },
        {
          id = 1212,
          name = "",
          type = "S",
          shape = "rectangle",
          x = 5418,
          y = 452.75,
          width = 25,
          height = 25,
          rotation = 0,
          gid = 5,
          visible = true,
          properties = {}
        },
        {
          id = 1214,
          name = "",
          type = "S",
          shape = "rectangle",
          x = 5387.08,
          y = 460.75,
          width = 25,
          height = 25,
          rotation = 0,
          gid = 5,
          visible = true,
          properties = {}
        },
        {
          id = 1215,
          name = "",
          type = "S",
          shape = "rectangle",
          x = 5448.25,
          y = 441.75,
          width = 25,
          height = 25,
          rotation = 0,
          gid = 5,
          visible = true,
          properties = {}
        },
        {
          id = 1216,
          name = "",
          type = "S",
          shape = "rectangle",
          x = 5635.12,
          y = 397.75,
          width = 25,
          height = 25,
          rotation = 0,
          gid = 5,
          visible = true,
          properties = {}
        },
        {
          id = 1217,
          name = "",
          type = "S",
          shape = "rectangle",
          x = 5603.87,
          y = 397.75,
          width = 25,
          height = 25,
          rotation = 0,
          gid = 5,
          visible = true,
          properties = {}
        },
        {
          id = 1218,
          name = "",
          type = "S",
          shape = "rectangle",
          x = 5572.62,
          y = 397.75,
          width = 25,
          height = 25,
          rotation = 0,
          gid = 5,
          visible = true,
          properties = {}
        },
        {
          id = 1219,
          name = "",
          type = "S",
          shape = "rectangle",
          x = 5666.37,
          y = 397.75,
          width = 25,
          height = 25,
          rotation = 0,
          gid = 5,
          visible = true,
          properties = {}
        },
        {
          id = 1220,
          name = "",
          type = "S",
          shape = "rectangle",
          x = 5761.45,
          y = 397.083,
          width = 25,
          height = 25,
          rotation = 0,
          gid = 5,
          visible = true,
          properties = {}
        },
        {
          id = 1221,
          name = "",
          type = "S",
          shape = "rectangle",
          x = 5730.2,
          y = 397.083,
          width = 25,
          height = 25,
          rotation = 0,
          gid = 5,
          visible = true,
          properties = {}
        },
        {
          id = 1222,
          name = "",
          type = "S",
          shape = "rectangle",
          x = 5698.95,
          y = 397.083,
          width = 25,
          height = 25,
          rotation = 0,
          gid = 5,
          visible = true,
          properties = {}
        },
        {
          id = 1224,
          name = "",
          type = "G",
          shape = "rectangle",
          x = 5190.25,
          y = 365.75,
          width = 62.5,
          height = 56.25,
          rotation = 0,
          gid = 6,
          visible = true,
          properties = {}
        },
        {
          id = 1225,
          name = "",
          type = "C",
          shape = "rectangle",
          x = 5306,
          y = 337.5,
          width = 25,
          height = 25,
          rotation = 0,
          gid = 1,
          visible = true,
          properties = {}
        },
        {
          id = 1226,
          name = "",
          type = "F",
          shape = "rectangle",
          x = 3627,
          y = 868.75,
          width = 1505.07,
          height = 159.25,
          rotation = 0,
          gid = 5,
          visible = true,
          properties = {}
        },
        {
          id = 1227,
          name = "",
          type = "PU2",
          shape = "rectangle",
          x = 4262,
          y = 528.75,
          width = 25,
          height = 25,
          rotation = 0,
          gid = 12,
          visible = true,
          properties = {}
        },
        {
          id = 1228,
          name = "",
          type = "C",
          shape = "rectangle",
          x = 2550,
          y = 275,
          width = 25,
          height = 25,
          rotation = 0,
          gid = 1,
          visible = true,
          properties = {}
        },
        {
          id = 1229,
          name = "",
          type = "L",
          shape = "rectangle",
          x = 3012.5,
          y = 452,
          width = 116.75,
          height = 25,
          rotation = 0,
          gid = 7,
          visible = true,
          properties = {}
        },
        {
          id = 1230,
          name = "",
          type = "D",
          shape = "rectangle",
          x = 3202,
          y = 529,
          width = 171.5,
          height = 25,
          rotation = 0,
          gid = 12,
          visible = true,
          properties = {}
        },
        {
          id = 1231,
          name = "",
          type = "G",
          shape = "rectangle",
          x = 1875,
          y = -46.75,
          width = 150,
          height = 25,
          rotation = 0,
          gid = 6,
          visible = true,
          properties = {}
        },
        {
          id = 1232,
          name = "",
          type = "L",
          shape = "rectangle",
          x = 1740,
          y = 18.25,
          width = 77.75,
          height = 25,
          rotation = 0,
          gid = 7,
          visible = true,
          properties = {}
        },
        {
          id = 1233,
          name = "",
          type = "P3",
          shape = "rectangle",
          x = 1883.5,
          y = -65.5,
          width = 50,
          height = 162.5,
          rotation = 0,
          gid = 10,
          visible = true,
          properties = {}
        },
        {
          id = 1234,
          name = "",
          type = "C",
          shape = "rectangle",
          x = 1955.25,
          y = -76.25,
          width = 25,
          height = 25,
          rotation = 0,
          gid = 1,
          visible = true,
          properties = {}
        },
        {
          id = 1235,
          name = "",
          type = "G",
          shape = "rectangle",
          x = 2935.25,
          y = 209.5,
          width = 1242.5,
          height = 280.25,
          rotation = 0,
          gid = 6,
          visible = true,
          properties = {}
        },
        {
          id = 1236,
          name = "",
          type = "G",
          shape = "rectangle",
          x = 4159,
          y = 97,
          width = 487.5,
          height = 168.75,
          rotation = 0,
          gid = 6,
          visible = true,
          properties = {}
        }
      }
    }
  }
}
