return {
  version = "1.1",
  luaversion = "5.1",
  tiledversion = "0.17.1",
  orientation = "orthogonal",
  renderorder = "right-down",
  width = 500,
  height = 50,
  tilewidth = 25,
  tileheight = 25,
  nextobjectid = 1158,
  properties = {},
  tilesets = {
    {
      name = "tiles",
      firstgid = 1,
      tilewidth = 25,
      tileheight = 25,
      spacing = 0,
      margin = 0,
      tileoffset = {
        x = 0,
        y = 0
      },
      properties = {},
      terrains = {},
      tilecount = 14,
      tiles = {
        {
          id = 0,
          image = "G:/Feevale/Mapas projeto/tiles/coinTile.png",
          width = 25,
          height = 25
        },
        {
          id = 1,
          image = "G:/Feevale/Mapas projeto/tiles/darkTile.png",
          width = 25,
          height = 25
        },
        {
          id = 2,
          image = "G:/Feevale/Mapas projeto/tiles/endGameTile.png",
          width = 25,
          height = 25
        },
        {
          id = 3,
          image = "G:/Feevale/Mapas projeto/tiles/endZeroGravityTile.png",
          width = 25,
          height = 25
        },
        {
          id = 4,
          image = "G:/Feevale/Mapas projeto/tiles/fatalTile.png",
          width = 25,
          height = 25
        },
        {
          id = 5,
          image = "G:/Feevale/Mapas projeto/tiles/groundTile.png",
          width = 25,
          height = 25
        },
        {
          id = 6,
          image = "G:/Feevale/Mapas projeto/tiles/lightTile.png",
          width = 25,
          height = 25
        },
        {
          id = 7,
          image = "G:/Feevale/Mapas projeto/tiles/portal1Tile.png",
          width = 25,
          height = 25
        },
        {
          id = 8,
          image = "G:/Feevale/Mapas projeto/tiles/portal2Tile.png",
          width = 25,
          height = 25
        },
        {
          id = 9,
          image = "G:/Feevale/Mapas projeto/tiles/portal3Tile.png",
          width = 25,
          height = 25
        },
        {
          id = 10,
          image = "G:/Feevale/Mapas projeto/tiles/portal4Tile.png",
          width = 25,
          height = 25
        },
        {
          id = 11,
          image = "G:/Feevale/Mapas projeto/tiles/powerUpTile.png",
          width = 25,
          height = 25
        },
        {
          id = 12,
          image = "G:/Feevale/Mapas projeto/tiles/spikeTile.png",
          width = 25,
          height = 25
        },
        {
          id = 13,
          image = "G:/Feevale/Mapas projeto/tiles/startZeroGravityTile.png",
          width = 25,
          height = 25
        }
      }
    }
  },
  layers = {
    {
      type = "objectgroup",
      name = "Object Layer 1",
      visible = true,
      opacity = 1,
      offsetx = 166,
      offsety = 128,
      draworder = "topdown",
      properties = {},
      objects = {
        {
          id = 283,
          name = "",
          type = "G",
          shape = "rectangle",
          x = 153.5,
          y = 878.25,
          width = 268,
          height = 303.25,
          rotation = 0,
          gid = 6,
          visible = true,
          properties = {}
        },
        {
          id = 994,
          name = "",
          type = "EG",
          shape = "rectangle",
          x = 5643.75,
          y = 537.5,
          width = 25,
          height = 259.25,
          rotation = 0,
          gid = 3,
          visible = true,
          properties = {}
        },
        {
          id = 1096,
          name = "",
          type = "L",
          shape = "rectangle",
          x = 525,
          y = 525,
          width = 300,
          height = 25,
          rotation = 0,
          gid = 7,
          visible = true,
          properties = {}
        },
        {
          id = 1097,
          name = "",
          type = "D",
          shape = "rectangle",
          x = 706.25,
          y = 406.25,
          width = 75,
          height = 25,
          rotation = 0,
          gid = 12,
          visible = true,
          properties = {}
        },
        {
          id = 1098,
          name = "",
          type = "L",
          shape = "rectangle",
          x = 875,
          y = 331.25,
          width = 77.75,
          height = 25,
          rotation = 0,
          gid = 7,
          visible = true,
          properties = {}
        },
        {
          id = 1100,
          name = "",
          type = "D",
          shape = "rectangle",
          x = 902.75,
          y = 543.75,
          width = 293.75,
          height = 25,
          rotation = 0,
          gid = 12,
          visible = true,
          properties = {}
        },
        {
          id = 1101,
          name = "",
          type = "D",
          shape = "rectangle",
          x = 1037.5,
          y = 237.5,
          width = 140.25,
          height = 25,
          rotation = 0,
          gid = 12,
          visible = true,
          properties = {}
        },
        {
          id = 1102,
          name = "",
          type = "P1",
          shape = "rectangle",
          x = 1312.5,
          y = 125,
          width = 50,
          height = 75,
          rotation = 0,
          gid = 10,
          visible = true,
          properties = {}
        },
        {
          id = 1103,
          name = "",
          type = "G",
          shape = "rectangle",
          x = 1256.25,
          y = 840.75,
          width = 1459,
          height = 312.5,
          rotation = 0,
          gid = 6,
          visible = true,
          properties = {}
        },
        {
          id = 1104,
          name = "",
          type = "C",
          shape = "rectangle",
          x = 1425,
          y = 43.75,
          width = 25,
          height = 25,
          rotation = 0,
          gid = 1,
          visible = true,
          properties = {}
        },
        {
          id = 1105,
          name = "",
          type = "G",
          shape = "rectangle",
          x = 1256.25,
          y = 315.75,
          width = 159,
          height = 75,
          rotation = 0,
          gid = 6,
          visible = true,
          properties = {}
        },
        {
          id = 1106,
          name = "",
          type = "G",
          shape = "rectangle",
          x = 1412.5,
          y = 362.5,
          width = 71.5,
          height = 84.25,
          rotation = 0,
          gid = 6,
          visible = true,
          properties = {}
        },
        {
          id = 1107,
          name = "",
          type = "G",
          shape = "rectangle",
          x = 1481.25,
          y = 362.5,
          width = 59,
          height = 53,
          rotation = 0,
          gid = 6,
          visible = true,
          properties = {}
        },
        {
          id = 1108,
          name = "",
          type = "G",
          shape = "rectangle",
          x = 1662.5,
          y = 284.5,
          width = 546.5,
          height = 325,
          rotation = 0,
          gid = 6,
          visible = true,
          properties = {}
        },
        {
          id = 1109,
          name = "",
          type = "G",
          shape = "rectangle",
          x = 1284,
          y = 143.75,
          width = 193.75,
          height = 21.75,
          rotation = 0,
          gid = 6,
          visible = true,
          properties = {}
        },
        {
          id = 1110,
          name = "",
          type = "F",
          shape = "rectangle",
          x = 418.75,
          y = 781.25,
          width = 840.25,
          height = 50,
          rotation = 0,
          gid = 5,
          visible = true,
          properties = {}
        },
        {
          id = 1113,
          name = "",
          type = "G",
          shape = "rectangle",
          x = 2206.25,
          y = 284.5,
          width = 4040.25,
          height = 156.25,
          rotation = 0,
          gid = 6,
          visible = true,
          properties = {}
        },
        {
          id = 1114,
          name = "",
          type = "G",
          shape = "rectangle",
          x = 2368.75,
          y = 531.25,
          width = 152.75,
          height = 109.25,
          rotation = 0,
          gid = 6,
          visible = true,
          properties = {}
        },
        {
          id = 1115,
          name = "",
          type = "G",
          shape = "rectangle",
          x = 2690.25,
          y = 397,
          width = 250,
          height = 115.75,
          rotation = 0,
          gid = 6,
          visible = true,
          properties = {}
        },
        {
          id = 1116,
          name = "",
          type = "G",
          shape = "rectangle",
          x = 2868.75,
          y = 675,
          width = 3390.25,
          height = 140.75,
          rotation = 0,
          gid = 6,
          visible = true,
          properties = {}
        },
        {
          id = 1117,
          name = "",
          type = "D",
          shape = "rectangle",
          x = 2368.75,
          y = 425,
          width = 25,
          height = 140.5,
          rotation = 0,
          gid = 12,
          visible = true,
          properties = {}
        },
        {
          id = 1118,
          name = "",
          type = "L",
          shape = "rectangle",
          x = 2662.5,
          y = 528.25,
          width = 25,
          height = 93.75,
          rotation = 0,
          gid = 7,
          visible = true,
          properties = {}
        },
        {
          id = 1119,
          name = "",
          type = "G",
          shape = "rectangle",
          x = 2662.5,
          y = 434.5,
          width = 27.75,
          height = 153.25,
          rotation = 0,
          gid = 6,
          visible = true,
          properties = {}
        },
        {
          id = 1120,
          name = "",
          type = "G",
          shape = "rectangle",
          x = 2918.75,
          y = 437.5,
          width = 25,
          height = 153.25,
          rotation = 0,
          gid = 6,
          visible = true,
          properties = {}
        },
        {
          id = 1122,
          name = "",
          type = "D",
          shape = "rectangle",
          x = 2918.75,
          y = 534.5,
          width = 25,
          height = 100,
          rotation = 0,
          gid = 12,
          visible = true,
          properties = {}
        },
        {
          id = 1123,
          name = "",
          type = "F",
          shape = "rectangle",
          x = 2715.25,
          y = 843.75,
          width = 206.25,
          height = 159.25,
          rotation = 0,
          gid = 5,
          visible = true,
          properties = {}
        },
        {
          id = 1124,
          name = "",
          type = "G",
          shape = "rectangle",
          x = 1256.25,
          y = -40.5,
          width = 952.75,
          height = 237.5,
          rotation = 0,
          gid = 6,
          visible = true,
          properties = {}
        },
        {
          id = 1125,
          name = "",
          type = "C",
          shape = "rectangle",
          x = 1593.75,
          y = 318.75,
          width = 25,
          height = 25,
          rotation = 0,
          gid = 1,
          visible = true,
          properties = {}
        },
        {
          id = 1126,
          name = "",
          type = "G",
          shape = "rectangle",
          x = 1362.5,
          y = 128.25,
          width = 115.25,
          height = 50,
          rotation = 0,
          gid = 6,
          visible = true,
          properties = {}
        },
        {
          id = 1127,
          name = "",
          type = "C",
          shape = "rectangle",
          x = 2806.25,
          y = 450,
          width = 25,
          height = 25,
          rotation = 0,
          gid = 1,
          visible = true,
          properties = {}
        },
        {
          id = 1128,
          name = "",
          type = "S",
          shape = "rectangle",
          x = 1850,
          y = 531.25,
          width = 25,
          height = 25,
          rotation = 0,
          gid = 5,
          visible = true,
          properties = {}
        },
        {
          id = 1129,
          name = "",
          type = "S",
          shape = "rectangle",
          x = 1875,
          y = 531.25,
          width = 25,
          height = 25,
          rotation = 0,
          gid = 5,
          visible = true,
          properties = {}
        },
        {
          id = 1130,
          name = "",
          type = "S",
          shape = "rectangle",
          x = 1900,
          y = 531.25,
          width = 25,
          height = 25,
          rotation = 0,
          gid = 5,
          visible = true,
          properties = {}
        },
        {
          id = 1131,
          name = "",
          type = "S",
          shape = "rectangle",
          x = 1925,
          y = 531.25,
          width = 25,
          height = 25,
          rotation = 0,
          gid = 5,
          visible = true,
          properties = {}
        },
        {
          id = 1132,
          name = "",
          type = "G",
          shape = "rectangle",
          x = 1662.5,
          y = 362.5,
          width = 115.25,
          height = 403,
          rotation = 0,
          gid = 6,
          visible = true,
          properties = {}
        },
        {
          id = 1133,
          name = "",
          type = "G",
          shape = "rectangle",
          x = 2034,
          y = 362.5,
          width = 175,
          height = 403,
          rotation = 0,
          gid = 6,
          visible = true,
          properties = {}
        },
        {
          id = 1134,
          name = "",
          type = "C",
          shape = "rectangle",
          x = 1887.5,
          y = 425,
          width = 25,
          height = 25,
          rotation = 0,
          gid = 1,
          visible = true,
          properties = {}
        },
        {
          id = 1135,
          name = "",
          type = "G",
          shape = "rectangle",
          x = 1334,
          y = 362.5,
          width = 81.25,
          height = 121.75,
          rotation = 0,
          gid = 6,
          visible = true,
          properties = {}
        },
        {
          id = 1138,
          name = "",
          type = "G",
          shape = "rectangle",
          x = 3477.75,
          y = 537.5,
          width = 150,
          height = 46.75,
          rotation = 0,
          gid = 6,
          visible = true,
          properties = {}
        },
        {
          id = 1139,
          name = "",
          type = "S",
          shape = "rectangle",
          x = 3581.25,
          y = 493.75,
          width = 25,
          height = 25,
          rotation = 0,
          gid = 5,
          visible = true,
          properties = {}
        },
        {
          id = 1140,
          name = "",
          type = "S",
          shape = "rectangle",
          x = 3518.75,
          y = 493.75,
          width = 25,
          height = 25,
          rotation = 0,
          gid = 5,
          visible = true,
          properties = {}
        },
        {
          id = 1141,
          name = "",
          type = "S",
          shape = "rectangle",
          x = 3487.5,
          y = 493.75,
          width = 25,
          height = 25,
          rotation = 0,
          gid = 5,
          visible = true,
          properties = {}
        },
        {
          id = 1142,
          name = "",
          type = "S",
          shape = "rectangle",
          x = 3550,
          y = 493.75,
          width = 25,
          height = 25,
          rotation = 0,
          gid = 5,
          visible = true,
          properties = {}
        },
        {
          id = 1143,
          name = "",
          type = "PU1",
          shape = "rectangle",
          x = 3193.75,
          y = 525,
          width = 25,
          height = 25,
          rotation = 0,
          gid = 12,
          visible = true,
          properties = {}
        },
        {
          id = 1144,
          name = "",
          type = "G",
          shape = "rectangle",
          x = 2875,
          y = 847,
          width = 184,
          height = 312.75,
          rotation = 0,
          gid = 6,
          visible = true,
          properties = {}
        },
        {
          id = 1145,
          name = "",
          type = "SZG",
          shape = "rectangle",
          x = 4031.25,
          y = 540.75,
          width = 25,
          height = 256.25,
          rotation = 0,
          gid = 8,
          visible = true,
          properties = {}
        },
        {
          id = 1146,
          name = "",
          type = "PU4",
          shape = "rectangle",
          x = 1525,
          y = 443.75,
          width = 25,
          height = 25,
          rotation = 0,
          gid = 12,
          visible = true,
          properties = {}
        },
        {
          id = 1147,
          name = "",
          type = "PU3",
          shape = "rectangle",
          x = 2300,
          y = 400,
          width = 25,
          height = 25,
          rotation = 0,
          gid = 12,
          visible = true,
          properties = {}
        },
        {
          id = 1149,
          name = "",
          type = "G",
          shape = "rectangle",
          x = 4481.25,
          y = 537.5,
          width = 215.25,
          height = 71.75,
          rotation = 0,
          gid = 6,
          visible = true,
          properties = {}
        },
        {
          id = 1150,
          name = "",
          type = "EZG",
          shape = "rectangle",
          x = 5281.25,
          y = 537.5,
          width = 25,
          height = 253,
          rotation = 0,
          gid = 4,
          visible = true,
          properties = {}
        },
        {
          id = 1151,
          name = "",
          type = "G",
          shape = "rectangle",
          x = 4690.25,
          y = 534.5,
          width = 68.75,
          height = 156.25,
          rotation = 0,
          gid = 6,
          visible = true,
          properties = {}
        },
        {
          id = 1152,
          name = "",
          type = "G",
          shape = "rectangle",
          x = 5068.75,
          y = 459.5,
          width = 121.5,
          height = 56.25,
          rotation = 0,
          gid = 6,
          visible = true,
          properties = {}
        },
        {
          id = 1153,
          name = "",
          type = "C",
          shape = "rectangle",
          x = 3537.5,
          y = 418.75,
          width = 25,
          height = 25,
          rotation = 0,
          gid = 1,
          visible = true,
          properties = {}
        },
        {
          id = 1154,
          name = "",
          type = "C",
          shape = "rectangle",
          x = 4900,
          y = 412.5,
          width = 25,
          height = 25,
          rotation = 0,
          gid = 1,
          visible = true,
          properties = {}
        },
        {
          id = 1155,
          name = "",
          type = "P2",
          shape = "rectangle",
          x = 5068.75,
          y = 406.25,
          width = 50,
          height = 75,
          rotation = 0,
          gid = 10,
          visible = true,
          properties = {}
        },
        {
          id = 1156,
          name = "",
          type = "G",
          shape = "rectangle",
          x = 5068.75,
          y = 331.25,
          width = 121.5,
          height = 47,
          rotation = 0,
          gid = 6,
          visible = true,
          properties = {}
        },
        {
          id = 1157,
          name = "",
          type = "C",
          shape = "rectangle",
          x = 5143.75,
          y = 381.25,
          width = 25,
          height = 25,
          rotation = 0,
          gid = 1,
          visible = true,
          properties = {}
        }
      }
    }
  }
}
